### ISSUE TITLE
Naming Issues and inconsistency

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#1019]
- [ ] Refining Arcana = Mending Arcana (When choosing races this is a QoL update to help them make their decision.) 
- [x] Longbows = Bows (Made by Essence of Bows.) I don't believe the Essence is in-game but this will be confusing as well when it is. 
- [x] Casting = Fishing. Two different names can confuse the players.
- [x] Just saw in the guild discord, someone posted a picture of Talisman of the Infinite Forest - couldn’t help but notice the Lightening spelling in the item information should be Lightning ⚡️ 😉.

**Comment by PatrickKaHoTang** [comment]
For Talisman of the Infinite Forest, the intended purpose of the "Lightening" tooltip is for a special that may be implemented at a later date. It was for reducing ammunition weight. The spelling would be correct if it's to "lighten" the weight.

**Comment by davidjreese** [comment]
Refining is an agriculture skill... not sure why the person sedit it was Refining Arcana -> Mending Arcana. Updated the friendly names of the skills to match the common language in game.
