### ISSUE TITLE
Review Jerome's quest; Durable Ore from mining quest can get stuck in player's backpack

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#1024]
If player takes Jerome quest for durable ore and has the quest (presumably no drop item) in their pack along with mined durable ore, Jerome takes the mined ore and player is left with the no drop quest item stuck in their pack.

Need to look at the quest to see what should be done here or how it's even getting into their pack.

**Comment by PatrickKaHoTang** [comment]
I recall the original quest obtaining Durable Ore for Jerome left of Dexmor. At the end of the quest, I believe it gave a Durable Blacksmith Hammer as the quest reward.

The mined Durable Ore could be renamed as something else so it doesn't conflict with the quest Durable Ore? Would also have to change for Distillation

**Comment by davidjreese** [comment]
i rewrote these so it doesn't have any of that nonsense
