### ISSUE TITLE
Ettin/Storm Giant AI Changes

### ISSUE THREAD

**Issue by Galdelonian** [IronWillGames/Dransik#1046]
Ettins are giants that hurl boulders. They really shouldn't run. I believe the AI for Ettins should be similar to dragons. They should hurl boulders and run at you until they get in melee range then attack in melee. This will make it easier for newer players to fight them since they're a primarily Krythan mob and the quests lower level players will be doing for Ettins will be more reasonable.

I suggest Storm Giants to throw ranged attacks and stand still similar to Purple Ghosts. They don't have to attack in melee like ettins. This will make Storm Giant lair more reasonable.

These changes could get players ready to fight dragons later on. Kind of like a "training."

**Comment by davidjreese** [comment]
fixed
