### ISSUE TITLE
[Dransik 2.0] Picking up item off the ground leaves duplicate copy behind 

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#106]
### Picking up item off the ground leaves duplicate copy behind 

1. Log into a character
2. Kill a monster and drag the item onto your character
3. Notice that the item you dragged is still shown as a copy on the ground that can be interacted with

These items can also be interacted with from tiles away, even if you are not beside them. Also, unable to drag items on top of the same tile as one of these broken duplicate items. Found out that this issue occurs when you are picking up another of an item you already have in your backpack, such as gold. 

#### Expected:
When picking up an item, it should disappear from the ground as well.

#### Actual:
After picking up items off the ground ,a copy remains that can be interacted with.

**Comment by davidjreese** [comment]
Think I fixed all cases of this visual artificat.
