### ISSUE TITLE
[Dransik 2.0] Unable to drag different items on top of each other while on the ground

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#107]
### Unable to drag different items on top of each other while on the ground

1. Log into a character
2. Kill a monster that drops 2 different items
3. Move one item to a different tile
4. Attempt to move that item back on top of the other item
5. Notice that you are unable to place an item on top of another item

#### Expected:
Items on the ground should be stackable on the same tile.

#### Actual:
Unable to stack items on the ground on the same tile.

**Comment by davidjreese** [comment]
Think I fixed all cases of this visual artificat.
