### ISSUE TITLE
[Dransik 2.0] Attack and Miss sprites showing as Holy Helm and Brick

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#108]
### Attack and Miss sprites showing as Holy Helm and Brick

1. Log into a character
2. Walk around and find a monster
3. Get hit by the monster
4. Notice that when you are hit, the sprite shows a Holy Helm, and when they miss, it shows a Brick

#### Expected:
When hit, should show the hit sprite animation. When miss, should show the miss sprite animation.

#### Actual:
When hit, shows a Holy Helm. When miss, shows a Brick.

**Comment by davidjreese** [comment]
@athacus 

Can you put screenshots / descirptions of what HIT and MISS should be?

I am just not sure what the icons were supposed to look like. For some reason I felt like the Helm was something I saw on the current Dransik client

**Comment by athacus** [comment]
@davidjreese 

Hit
![image](https://user-images.githubusercontent.com/112193703/195408451-6a612e83-0b14-4557-b5f9-e5a8d99f3e73.png)

Miss
![image](https://user-images.githubusercontent.com/112193703/195408544-0ed8a166-831c-4437-ab05-80821d7322ab.png)

There is also another hit image, I think it's either Critical Hit or Elemental Damage Hit. I don't have an image of that one. Might be a bit tougher to get unless screen recording while attacking. Maybe you'll be able to see it in your sprite files.

**Comment by davidjreese** [comment]
hah - super helpful. i wonder what i got wrong. thanks!

**Comment by davidjreese** [comment]
fixed
