### ISSUE TITLE
Character Creation [Dransik 2.0]

### ISSUE THREAD

**Issue by genkelvor** [IronWillGames/Dransik#109]
When creating a character and selecting your race if you choose male 
the avatar for Brimlock male is showing a human male should be this avatar male
![0BC8](https://user-images.githubusercontent.com/49921293/194661359-c1dc593b-8f57-4e57-8b6c-88976e9f8c3a.gif)

Night Elf is showing a Brimlock female should be this avatar for male
![0BD0](https://user-images.githubusercontent.com/49921293/194661288-ac35e061-6a1c-4a6e-bade-ac795384abf9.gif)

if you switch over to Female 
the avatar for female Brimlock is shows a male Brimlock it should be 
![0BCC](https://user-images.githubusercontent.com/49921293/194662119-d4472a47-aefd-4544-91a4-8f4a534ddada.gif)

**Comment by davidjreese** [comment]
Thanks, i fat fingered those for sure. fixed
