### ISSUE TITLE
[Dransik 2.0] Unable to CTRL click identify items and stacks of items

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#110]
### Unable to CTRL click identify items and stacks of items

1. Log into a character
2. Hold CTRL and click any item in your backpack or bank, such as Gold
3. Notice that it doesn't tell you what the item is, and if it's a stack, it doesn't tell you how many in the stack

#### Expected:
When CTRL clicking an item, should list details of the item, or tell you how many in the stack.

#### Actual:
When CTRL clicking an item, nothing happens.

**Comment by AESeryth** [comment]
Shift is the default now. Should probably be changed back to Ctrl.  Same with TAB and `/~ for targeting.

**Comment by athacus** [comment]
Oh didn't know, thanks for the heads up!

**Comment by davidjreese** [comment]
I made things match default Dransik mappings but also left newer smarter mappings in for new users.

CTRL click is now default on Windows, on Mac, it is COMMAND (META) click since CTRL clicking is like a right click on mac.
