### ISSUE TITLE
Ranged Monsters.

### ISSUE THREAD

**Issue by Frostavenger** [IronWillGames/Dransik#1109]
So 2 things here. 1st If you go into Fog of war areas ranged monsters cant shoot you and need to run to you. They will get to melee range shoot you then run 1 tile back then 1 tile in and shoot. This WAS very nice for killing ettins that move at light speed and kite you better then a player... Thus leading you into a army of like 20 more. Thus making it so killing any fast moving RANGED only monsters is WAY to deadly for what its worth. I think if there is RANGED only monsters they need to move slow as rocks not player speed.

**Comment by davidjreese** [comment]
fixed
