### ISSUE TITLE
Backpack [Dransik 2.0]

### ISSUE THREAD

**Issue by genkelvor** [IronWillGames/Dransik#111]
After creating a character the items in your bag will spawn in random locations which can be off the line of the backpack will have to use the resize option with backpack to see it and move it to a new area.

Also with Backpacks if you close and reopen you backpack it will cause items to go invisible till you relog

**Comment by davidjreese** [comment]
Fixed the close/open empty issue.

**Comment by davidjreese** [comment]
Server sends down the 'initial location' and it is sometimes outside the frame... so I added check to see if the item is outside the frame and reposition it inside.
