### ISSUE TITLE
[Dransik 2.0] Unable to CTRL click players to see their equipment

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#112]
### Unable to CTRL click players to see their equipment

1. Log into a character
2. Find a player and CTRL click them
3. Notice that no window shows up to show their equipment

#### Expected:
When CTRL clicking players, should show their equipment.

#### Actual:
When CTRL clicking players, nothing happens.

**Comment by davidjreese** [comment]
Fixed - used default mappins. on Mac, it is COMMAND (Meta) key on Windows it is CTRL
