### ISSUE TITLE
[Dransik 2.0] Unable to see my own name, but switch is on to show my own name (random)

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#113]
### Unable to see my own name, but switch is on to show my own name (random)
For some random way, not sure how it happened, but the switch is on to show my own name, but I don't see my own name.

#### Expected:
When switch is set to show own name, should show own name.

#### Actual:
When switch is set to show own name, randomly it does not show own name.

**Comment by davidjreese** [comment]
I cannot get this to happen in my build. Can you confirm it is still happening @athacus ? any additional repro steps/

**Comment by athacus** [comment]
@davidjreese Yeah it's a weird scenario that happened randomly to me as an edge case. If I can figure out a way to reproduce it continuously, I will post it.

**Comment by athacus** [comment]
@davidjreese Okay I found a way to reproduce.

1. Log into a character
2. Press ESC to open the Settings menu
3. Click on Options
4. Switch Show My Name to OFF
5. Switch Show My Name to ON
6. Close the Options and Settings menu
7. Press B to close the backpack
8. Notice that your name has now vanished, while the Show My Name switch is set to ON. At this point you need to reset the game in order for it to work properly again.

**Comment by athacus** [comment]
@davidjreese I am noticing now that closing my Backpack hides my name and it won't come back until I relog. Seems to be related to this issue.

**Comment by davidjreese** [comment]
hah - perfect. found it. thanks
