### ISSUE TITLE
[Dransik 2.0] Turning off Show My Name, hides all names on screen

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#114]
### Turning off Show My Name, hides all names on screen

1. Log into a character
2. Ensure Show My Name is set to On
3. Find an NPC or player and notice their name on screen
4. Press ESC to open the settings window
5. Click on Options
6. Set Show My Name to Off
7. Notice that all names on screen vanish

#### Expected:
When setting Show My Name to Off, should only hide my name.

#### Actual:
When setting Show My Name to Off, it hides all names on screen.

**Comment by davidjreese** [comment]
fixed
