### ISSUE TITLE
[Dransik 2.0] Changing areas at night time stacks your self lighting

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#118]
Things like dying, going in and out of caves, etc will increase the brightness around your character over and over.

![light](https://user-images.githubusercontent.com/112813257/194671107-2cf068a2-6b9f-44d6-a8d7-e64edc74cc7f.jpg)

**Comment by davidjreese** [comment]
nice one - fixed. player light is a special case and wasn't being handled for multiple calls.
