### ISSUE TITLE
[Dransik 2.0] Input mapping window shows close button has "Close Help"

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#119]
### Input mapping window shows close button has "Close Help"

1. Log into a character
2. Press ESC to option the Settings window
3. Click on Input
4. Click on any keybinding to open the mapping window
5. Notice that the close button says "Close Help" instead of something like "Close Mapping"

#### Expected:
The Input Mapping window close button should show something instead of "Close Help".

#### Actual:
The Input Mapping window close button shows "Close Help".

**Comment by davidjreese** [comment]
indeed!
