### ISSUE TITLE
Double clicking Richard of Jeel (NPC in Hothbra) prevents you from using anything else afterward until relog

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#12]

**Comment by hgesler** [comment]
Verify this is still happening after latest patch 9.8.22

**Comment by AESeryth** [comment]
Still happening. After clicking him there's no feedback but when I using items in my backpack it just says the "--ReUse is ready" and I can't open doors or talk to NPCs, set my spawn, toggle torches, etc.

**Comment by hgesler** [comment]
Got a fix for this. Was no conversation scope if you weren't on his quest so player was stuck in ontalk with no way to listen rip lol
