### ISSUE TITLE
[Dransik 2.0] The "Look" hotkey doesn't work unless it's the same as the Use hotkey

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#123]
The default of Shift+Left Click works but if you change either Use or Look, Look will no longer work.  When both hotkeys are the same (with or without modifiers like shift) Look will work.   The default I doesn't work unless you also change Use to I.

Use works no matter what Look is set to.

**Comment by davidjreese** [comment]
I fixed this and broke look and identify apart. Identify might be messed up but wont interfere with look
