### ISSUE TITLE
[Dransik 2.0] Characters with the Item Identification skill can't Look at anything

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#124]
Trying to use the Look hotkey (Default i AND shift+left click) doesn't work once you have the Item Identification skill. It uses the Item Identification skill instead.

In the old client, the i key was used only for the Item Identification skill and did nothing until you had that skill learned.  In the new client the i key was one of the defaults for Look but it should only be a separate key for Item Identification.  

Item Identification also isn't supported yet. It crashes your client on success.  You can learn the skill at 88,1509,0 by clicking the "Loop and Twigg" item on the floor and talking to the guy there.

**Comment by davidjreese** [comment]
I fixed this and broke them apart. Identify might be messed up but wont interfere with look
