### ISSUE TITLE
[Dransik 2.0] Shift, Alt, and Ctrl modifiers on hotkeys don't do anything

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#125]
After setting a hotkey to Shift, Alt, or Ctrl + something the hotkey will work regardless of holding the modifier key.

For example, setting Target Protection to Shift+P and Player Info to P has the same effect as setting both to P - only Player Info will work.

**Comment by davidjreese** [comment]
Fixed - a couple of things.

Works: Backpack B and SHIFT-P works as does P for player all independently

There are some combinations of things that might not work and given the system complexity with some interactions.
