### ISSUE TITLE
[Dransik 2.0] Opening and closing your Player Info causes items in your backpack to move

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#127]
https://user-images.githubusercontent.com/112813257/194680333-45dbed43-8de5-4963-a770-083d04101c9d.mp4

Most of these items only start dancing after I equip and unequip them. Putting them on the floor and picking them back up stops them from moving until I equip/unequip again.

**Comment by davidjreese** [comment]
fixed. will do the stupid thing where its all at 0,0 if the items are 'unstable'. once you move them they stay though
