### ISSUE TITLE
[Dransik 2.0] Scrolling in merchant window causes Close button to stop working

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#128]
### Scrolling in merchant window causes Close button to stop working

1. Log into a character
2. Find a merchant and open the merchant window
3. Scroll down in the window and then try to click the close button
4. Notice that the merchant window will not close

#### Expected:
When scrolling in a merchant window, the close button should work.

#### Actual:
When scrolling in a merchant window, the close button stops working.

**Comment by davidjreese** [comment]
fixed this and other window click issues
