### ISSUE TITLE
[Dransik 2.0] When you are criminal, your name on Player Info window should be grey

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#129]
### When you are criminal, your name on Player Info window should be grey and above your character should be grey

1. Log into a character
2. Find any NPC and attack them
3. Open the Player Info window
4. Notice that the colour of your name does not change to grey when you become a criminal. Your name also does not change above your character avatar.

I noticed that the alignment says Criminal, but everyone in Dransik looks for it in the two places noted above.

#### Expected:
When you become a criminal, your name colour on the Player Info screen should be grey, and also your name above your character.

#### Actual:
When you become a criminal, your name colour on the Player Info screen is Yellow, and your name above your character is Green.

**Comment by davidjreese** [comment]
fixed - window titles and plaques use alignment colors

I was just draing the alignment color for the alignment value in the player stats other player stats
