### ISSUE TITLE
[Dransik 2.0] While fighting guards in Parian, sometimes the avatars randomly change into a chicken

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#130]
### While fighting guards in Parian, sometimes the avatars randomly change into a chicken

1. Log into a character
2. Attack some guards
3. Notice that they sometimes turn into a chicken. You may have to kill them first to start replicating this.

#### Expected:
When fighting guards, they should remain their avatar.

#### Actual:
When fighting guards, they randomly show a chicken avatar.

**Comment by davidjreese** [comment]
Does this still happen?

**Comment by athacus** [comment]
I'll give it a try later today and see if it still does. May have been fixed during one of the builds since.

**Comment by davidjreese** [comment]
were you able to reproduce this?

**Comment by athacus** [comment]
I forgot to try yesterday haha will check today

**Comment by athacus** [comment]
Doesn't seem to happen anymore, going to close.
