### ISSUE TITLE
[Dransik 2.0] Experience bar on Player Info screen shows odd number of experience

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#131]
### Experience bar on Player Info screen shows odd number of experience

1. Log into an existing character that is Level 99
2. Open the Player Info screen
3. Notice that the experience shows something like 7186126900%

This may have only been an issue on my character as it is an existing character that is level 99.

#### Expected:
The experience bar on the Player Info screen should show the accurate number of experience.

#### Actual:
The experience bar on the Player Info screen shows 7186126900%.

**Comment by davidjreese** [comment]
oops - fat fingered a table and removed a level. fixed
