### ISSUE TITLE
[Dransik 2.0] Character name on Player Info screen and above avatar do not show in the colour of the player's alignment

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#132]
### Character name on Player Info screen and above avatar do not show in the colour of the player's alignment

1. Log into a character that has a Holy or Evil alignment
2. Open the Player Info screen
3. Notice that the name colour of your character does not match the colour of the alignment.

#### Expected:
The character name colour on the Player Info screen and above the character should match the player's alignment colour.

#### Actual:
The character name colour on the Player Info screen is Yellow and above the character is Green.

**Comment by davidjreese** [comment]
fixed - window titles and plaques use alignment colors

I was just draing the alignment color for the alignment value in the player stats other player stats
