### ISSUE TITLE
[Dransik 2.0] Opened bottom barrel in Parian weapon shop east of South Parian Bank, then crashed

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#133]
### Opened bottom barrel in Parian weapon shop east of South Parian Bank, then crashed

1. Log into a character
2. Go to the Weapon Shop east of South Parian Bank
3. Go to the bottom barrel by the Blacksmith
4. Click the barrel to open it then move
5. This caused a crash, may not be repeatable

This also caused my character to be unplayable. Next time I logged in, it immediately crashes the game.

#### Expected:
When opening a barrel anywhere, should automatically close when walking away from it.

#### Actual:
When opening a barrel and walking away, sometimes causes crash.

**Comment by athacus** [comment]
It seems this issue is related to some golden torches near the church in parian, unrelated to the barrel.

**Comment by davidjreese** [comment]
@athacus - Can you give me a location (x,y,map). I have no idea where anything is.

**Comment by athacus** [comment]
@davidjreese 3461,3052 should initiate a crash right outside the church.

**Comment by athacus** [comment]
Confirmed this is working as expected now, closing.
