### ISSUE TITLE
[Dransik 2.0] While identifying someone's gear, if they change it, inspecting an item shows the new details but old sprite

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#134]
### While identifying someone's gear, if they change it, inspecting an item shows the new details but old sprite

1. Log into a character
2. Find another player and identify their gear
3. Notice which items they are wearing
4. Have them change their gear
5. Identify their gear after it has changed
6. Notice that the identified text does not match the sprite

In my particular instance, GM Seryth was wearing a Lightning Sword and he changed it to a Dark Sword. When identifying the gear, it showed the properties of the Dark Sword

#### Expected:
When identifying a player's gear after they change it, should show the correct details for the item they are wearing.

#### Actual:
When identifying a player's gear after they change it, shows the details from the previous item they were wearing.

**Comment by davidjreese** [comment]
Does this work properly in Dransik 1.0?

I ask because, the way Identify item works is independent of other player dialog.. maybe there is some hack I missed to force them to sync up after you initially LOOK at the other player to bring up the other player dialog. 

Was just curious.

**Comment by athacus** [comment]
I think how it works in current dransik is when you identify someone, it opens the window with the context of the gear they were wearing at the time, so it doesn't reference to their actual gear slots behind the scenes. Yes I believe it works as expected in current dransik.

**Comment by davidjreese** [comment]
Fixed - i think, need to test

**Comment by davidjreese** [comment]
i dont think this is actually working as you described on the live client :) i did make it work on this one. its the only way it could work without modifying the protocol.
