### ISSUE TITLE
[Dransik 2.0] When running east of Parian to Beholders/Death Tyrants, causes crash

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#135]
### When running east of Parian to Beholders/Death Tyrants, causes crash

1. Log into a character
2. Run east of Parian near Beholders/Death Tyrants
3. You should crash

#### Expected:
When running east of Parian to Beholders/Death Tyrants, should not crash.

#### Actual:
When running east of Parian to Beholders/Death Tyrants, causing crashes.

**Comment by davidjreese** [comment]
@athacus - Can you give me a location (x,y,map). I have no idea where anything is.

**Comment by athacus** [comment]
@davidjreese 3598, 3057. Run east of this area, crashed around there.

**Comment by davidjreese** [comment]
fixed i think (wasnt happening on my build)
