### ISSUE TITLE
[Dransik 2.0] Bank is broken, can't put items inside, can't see any items

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#136]
### Bank is broken, can't put items inside, can't see any items

1. Log into a character
2. Go to the bank and talk to the banker to open the bank window
3. Once the bank window is open, notice that nothing shows up inside
4. Drop an item in the bank
5. Notice that your bank still shows as empty, but the item is gone

#### Expected:
The bank should work as an extra container to hold items, and should be able to see items you deposit.

#### Actual:
The bank is not functional, and depositing items causes them to vanish.

**Comment by davidjreese** [comment]
fixed
