### ISSUE TITLE
[Dransik 2.0] When running into Shallox castle in Winterland, causes crash

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#137]
### When running into Shallox castle in Winterland, causes crash

1. Log into a character
2. Go to the Shallox castle boss area in Winterland
3. Go inside the middle of the castle
4. You should crash

#### Expected:
Shallox castle should be fully functional.

#### Actual:
Going inside Shallox castle causes crashing.

**Comment by davidjreese** [comment]
@athacus - Can you give me a location (x,y,map). I have no idea where anything is.

**Comment by davidjreese** [comment]
fixed i think (wasnt happening on my build)
