### ISSUE TITLE
[Dransik 2.0] Prevent game window clicks if click on gui window that is on the game window

### ISSUE THREAD

**Issue by Jabelius** [IronWillGames/Dransik#138]
![image](https://user-images.githubusercontent.com/1352768/194740120-f38b088a-f063-4278-822c-12d0342de37c.png)
If you click the X button it will close the GUI window but will open another right away.

**Comment by davidjreese** [comment]
Fixed this everywhere i think. Also fixed the bring to top of windows when you click on the empty area.
