### ISSUE TITLE
[Dransik 2.0] Change default keybindings to match current Dransik keybindings

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#140]
## Change default keybindings to match current Dransik keybindings

Some of the default keybindings do not match the current Dransik keybindings. This will be a pain for old players, and we should match the current Dransik keybindings as close as possible.

### Non-matching default keybindings that need adjusting:
Use - Right Click
Look - CTRL + Left Click
Target Cycle - Tab
Target Prot - F4
Chat - T
Skills - F

Since T maps to Time, we can move Time to a different keybinding. The T key has always been the chat key in Dransik.

**Comment by davidjreese** [comment]
Done - but I left in new more modern / intuitive keys for new players to have an easier time.
