### ISSUE TITLE
[Dransik 2.0] Deleting a character continues to show character details in slot after deletion

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#141]
### Deleting a character continues to show character details in slot after deletion

1. Open the client and select a server
2. On the character listing, delete a character
3. Notice that the character details are still contained in the slot

NOTE: If you click on the slot after deletion, it will open the Create Character screen.

#### Expected:
After deleting a character, the character details in the slot for the character should be clear.

#### Actual:
After deleting a character, the character details still exist in the character slot.

**Comment by davidjreese** [comment]
fixed this (i think) ... none of my characters are old enough :). let me know if this is fixed
