### ISSUE TITLE
[Dransik 2.0] Raise the maximum purchase quantity from the store

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#142]
### Raise the maximum purchase quantity from the store

The current maximum purchase quantity for potions is 10 at a time. In current Dransik, it is 50 at a time and people often find that is too low. We should raise this to 999 at a time if possible, so people can buy all their potions in one go.

**Comment by davidjreese** [comment]
fixed and made the shop dialog allow typing in the value as well
