### ISSUE TITLE
[Dransik 2.0] The music that plays in Parian has some LOUD horns

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#144]
One part of the song has the horns blasting my left ear.

https://user-images.githubusercontent.com/112813257/194983708-ad6c367c-8616-4cb4-976b-f65791fc0b10.mp4

**Comment by davidjreese** [comment]
Where is Parian again? X/Y map?

**Comment by AESeryth** [comment]
3458,3070,0

**Comment by davidjreese** [comment]
LOL - I am listening to this. It is the music - We could not use that music track, but thats about it. I don't know it needs to be removed. I have my music volume at a reasonable level and its not bad.

What do you think? what about you @hgesler ?

**Comment by hgesler** [comment]
It doesn't sound too bad to me, it does get a bit loud but 🤷 givin me dem minstrel vibes 💃 🎵 

I tried with headphones to see and yes there is a part of the track where a horn plays on left side. With music up half it's not out of control though. Maybe I'm getting old and losing my hearing 😂
