### ISSUE TITLE
[Dransik 2.0] Stores are not sorting by price in ascending order by default

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#146]
### Stores are not sorting by price in ascending order by default

1. Log into a character
2. Find a store like the Weapon Shop in any town (2727,2184)
3. Open the store window
4. Notice that the store's items are not sorted by Price in Ascending order by default

#### Expected:
The stores should be sorted by Price in Ascending order by default, to follow current Dransik's pattern.

#### Actual:
The stores are sorted by name alphabetically by default.

**Comment by davidjreese** [comment]
fixed
