### ISSUE TITLE
[Dransik 2.0] The skills window inner background is spilling out of it's container

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#147]
### The skills window inner background is spilling out of it's container

1. Log into a character
2. Press F to open the skills window
3. Notice that the skills window inner background goes beyond the size of the outer container edges

#### Expected:
The skills window inner background should stay within the edges of the outer container.

#### Actual:
The skills window inner background spills out of it's outer container.

**Comment by davidjreese** [comment]
fixed
