### ISSUE TITLE
[Dransik 2.0] Map progression not persisted after logging in (old characters)

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#148]
### Map progression not persisted after logging in (old characters)

1. Log into a character
2. Walk around and reveal some of the map
3. Log off
4. Log back into the same character
5. Notice that your map progression did not save

NOTE: This issue seems to be only happening on older characters, not ones created recently.

#### Expected:
The map progression will be saved and loaded when logging in.

#### Actual:
The map progression is not saved after logging out and logging in.

**Comment by davidjreese** [comment]
believe this is fixed now with my recent changes. detect app exit as well as controlled logout.
