### ISSUE TITLE
[Dransik 2.0] Dragging and dropping an item around in your backpack quickly, causes only transparent version to show

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#149]
### Dragging and dropping an item around in your backpack quickly, causes only transparent version to show

1. Log into a character
2. Pick up gold in your backpack and drop it quickly
3. Notice the gold is replaced by a transparent version. Once you drag and drop this transparent version, it goes back to full coloured version

NOTE: Only seems to occur when you drag the item only a couple pixels away from it's original position.

#### Expected:
Dragging and dropping an item in your backpack quickly, should move the item and show only the full coloured version.

#### Actual:
Dragging and dropping an item in your backpack quickly, moves the item but shows only the transparent version of the item.

**Comment by athacus** [comment]
Also seems to happen the same way in the Bank. Seems to be related to dragging items inside of any container.

**Comment by AESeryth** [comment]
If you drop any item onto another item (or too close even if not visually on it) it'll be turn transparent and not finish moving. 

Stacks of the same item work but nothing else.

**Comment by davidjreese** [comment]
got this i think
