### ISSUE TITLE
[Dransik 2.0] Chat Console and Combat Console X buttons not working

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#150]
### Chat Console and Combat Console X buttons not working

1. Log into a character
2. Click on the X button in the Chat Console
3. Notice that it does not close the Chat Console
4. Click on the X button in the Combat Console
5. Notice that it does not close the Combat Console

Maybe these windows aren't able to be closed and just need to remove the X icon?

#### Expected:
If the window has an X button, it should be able to be closed.

#### Actual:
The Chat Console and Combat Console windows have X buttons that do not close the window.

**Comment by davidjreese** [comment]
Fixed T/Enter will pop up console chat.

Options menu to open the Combat console if you close it with X
