### ISSUE TITLE
[Dransik 2.0] The animation speed of most everything seems to be slower than usual

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#151]
### The animation speed of most everything seems to be slower than usual

The animation speed of NPCs, items, character avatar, and even tiles seem to move at a slow pace. I believe increasing them by 2x or maybe 3x would bring it closer to the animation speed in current Dransik.

For example, it seems to be random, but it can take like 5-10 seconds for my avatar animation to complete a rotation.

**Comment by davidjreese** [comment]
more than doubled it - i thin it is looking closer to right now.. let me know what you think
