### ISSUE TITLE
[Dransik 2.0] Torches are not animating

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#152]
### Torches are not animating

1. Log into a character
2. Go to New Korelth bank located at 331,1471
3. Notice that the torches on the wall are not animating

Seems to be an issue for all torches I have come across.

#### Expected:
The torches should be animating and emanating light when it's dark.

#### Actual:
The torches are not animating, but they are emanating light when it's dark.

**Comment by davidjreese** [comment]
ugh, this one sucks

**Comment by davidjreese** [comment]
found it - fixed. what a hack. was easy to make it not a hack... not sure why is was done that way in the old client
