### ISSUE TITLE
[Dransik 2.0] Unable to sell items to stores

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#154]
### Unable to sell items to stores

1. Log into a character
2. Have an armor piece in your backpack that can be sold to the armor store, for example, Small Shield
3. Go to the New Korelth Armor Shop located at 337,1445
4. Click on the merchant to open the Buy/Sell window
5. Click Sell to open the Sell window
6. Click on the Small Shield item in the Sell window
7. Notice that clicking on the item does not queue the item up for sale. There is no way to increase the quantity, or know which items you will be choosing to sell. The quantity +/- icons do not function.

Maybe highlighting an item slot's background to know which items will be sold? Or another side pane in the Sell window that shows all of the items that are currently queued for sale?

#### Expected:
Should be able to sell an item to the store, and know which items will be queued for sale.

#### Actual:
Unable to sell the items to the store, and unable to know which items will be queued for sale.

**Comment by davidjreese** [comment]
I have the totals and colors being better showing what is sold. I also have the rows that are going to be bought or sold showing a different color. I think this is pretty good along with the size of window fix. let me know.
