### ISSUE TITLE
[Dransik 2.0] The merchant window is too small to list all the contents

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#155]
### The merchant window is too small to list all the contents

1. Log into a character
2. Go to the New Korelth Armor Shop located at 334,1445
3. Click on the merchant to open the Buy/Sell window
4. Click on Buy to open the Buy window
5. Scroll down to the bottom to see more items
6. Notice that the Item Names are spilling over into the Quantity column, and the Price column does not have enough room to show the full price of the items

Example
![image](https://user-images.githubusercontent.com/112193703/195453974-2e0ea326-9b6f-4eb7-8a0e-d90ee5f510ec.png)

Potential issue for Sell window as well, but that is not currently operational.

#### Expected:
The column values in the merchant Buy/Sell window should be contained within their columns.

#### Actual:
The column values in the merchant Buy/Sell window spill over into other columns, or become cut off by the container size.

**Comment by davidjreese** [comment]
fixed

**Comment by davidjreese** [comment]
also fixed the color coding and signs to be more natural for the mode you are in
