### ISSUE TITLE
[Dransik 2.0] Volume sliders in Sound window spilling over window container

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#156]
### Volume sliders in Sound window spilling over window container

1. Log into a character
2. Press ESC to open the Settings window
3. Click on Sound to open the Sound window
4. Notice that the sliders for Music Volume and Sound Volume are spilling past the container of the Sound window

Example
![image](https://user-images.githubusercontent.com/112193703/195455417-d9532564-9edd-44bc-a5bf-3a490ed60a07.png)

#### Expected:
The sliders for Music Volume and Sound Volume should be container within the Sound window container.

#### Actual:
The sliders for Music Volume and Sound Volume spill past the container of the Sound window.

**Comment by davidjreese** [comment]
i fixed several of these... missed that one. i wonder why this happened on a few of those help boxes. fixed now.
