### ISSUE TITLE
Exit game [Dransik 2.0]

### ISSUE THREAD

**Issue by genkelvor** [IronWillGames/Dransik#157]
Could we make it when you click the exit button it would take you back to character select? and from there have an option to go back to server select,

Also when you do click exit and it take you to server select and try to connect back to the server it wont let you connect will just stay on the connecting screen.

**Comment by davidjreese** [comment]
i agree - its unreal that the server doesn't already support this... i am going to update the server for this one

**Comment by davidjreese** [comment]
Backing out works now along with the current logout timer that ran in usecode( nobody ever saw is my guess). can also back out to server select.
