### ISSUE TITLE
[Dransik 2.0] Client allows attacking through Fog of War

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#158]
The client appears to let you target and use ranged attacks through walls or into the fog of war.  

The server will take your arrows but not allow the actual attack when attacking through walls or similar objects.

Targeting and attacking in the forest both work as if the fog wasn't there.

**Comment by davidjreese** [comment]
How are you selecting the targets?

**Comment by davidjreese** [comment]
How are you selecting the targets?

**Comment by davidjreese** [comment]
Fixed this, fog of war is now working properly with things in it (even when disabled).
