### ISSUE TITLE
[Dransik 2.0] Clickable link in Help window does not open browser to dransik.com

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#159]
### Clickable link in Help window does not open browser to dransik.com

1. Log into a character
2. Press ESC to open the Settings menu
3. Click Help to open the Help window
4. At the top of the window, click on https://dransik.com
5. Notice that clicking the link does not open a browser window to https://dransik.com

Speaking of Dransik.com, the site could use some updated content, and an updated copyright. Currently shows 2008 copyright.

#### Expected:
Clicking the dransik.com link in the Help window should open the browser to dransik.com.

#### Actual:
Clicking the dransik.com link in the Help window does not open a browser.

**Comment by davidjreese** [comment]
fixed - @moneybill is going to make a new Dransik site before we launch the new client.
