### ISSUE TITLE
[Dransik 2.0] Names of fallen monsters remain after they die

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#160]
### Names of fallen monsters remain after they die

1. Log into a character
2. Find some monsters and kill them using tab target
3. Notice after they die, the names remain on screen in a grey coloured font

Example:
![image](https://user-images.githubusercontent.com/112193703/195476883-a7dd0bfa-59f7-4cff-b0d5-2f3bd3168df1.png)

#### Expected:
After killing monsters, their names should no longer render.

#### Actual:
After killing monsters, their names continue to show on screen.

**Comment by davidjreese** [comment]
fixed, was an issue caused my a fix for something else.
