### ISSUE TITLE
[Dransik 2.0] After paging GM, message displayed twice in Chat Console

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#161]
### After paging GM, message displayed twice in Chat Console

1. Log into a character
2. Press ESC to open the Settings menu
3. Click on Help to open the Help window
4. Type some text in the text box and click Page GM
5. Notice in the Chat Console, 2 messages are displayed

Your GM page has been sent.
Your GM page has been sent. Please wait patiently for a GM to respond.

Example:
![image](https://user-images.githubusercontent.com/112193703/195477077-e319380e-6ca6-4ee7-a69a-8bf2e0f26e20.png)

#### Expected:
When sending a page to the GMs, the message should only appear once in the Chat Console.

#### Actual:
When sending a page to the GMs, two different messages appear in the Chat Console.

### Additional issue:
Also, I noticed some weirdness when I typing the word "test" into the text box, since it is also bound to the Chat window. Pressing T while in that text box on the Help window, also opens the chat box for input on the Chat Console. While the Help window is open, should probably eliminate focus to the Chat Console, so it doesn't start typing there too.

**Comment by davidjreese** [comment]
fixed
