### ISSUE TITLE
[Dransik 2.0] Spelling issue on Help window

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#162]
![image](https://user-images.githubusercontent.com/112193703/195477631-add90403-ac10-4a62-a4bd-1b96bdd040a7.png)

The Help window has an issue with spelling. The textbox should say:
If you are in need of in game **assistance**, type your **message** here and press the Page GM button below.

The two highlighted words are misspelled.

**Comment by davidjreese** [comment]
fixed!
