### ISSUE TITLE
[Dransik 2.0] When shift+dragging to split a stack of gold, issue in quantity dialog

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#163]
### When shift+dragging to split a stack of gold, issue in quantity dialog

1. Log into a character
2. Take a pile of gold and shift+drag it to split it
3. When the quantity dialog pops up, click on the text box to get to the end of the quantity
4. Press the backspace key to go back a number
5. Notice that pressing the backspace key removes the last number in the text box, then moves your cursor to the front of the text box

NOTE: If there is a space at the front of the number in the quantity text box, pressing backspace at the end of the text box does not jump the cursor to the front of the text box.

#### Expected:
When pressing the backspace key in the quantity dialog, should remove the last number in the text box and the cursor should stay at the end of the text box.

#### Actual:
When pressing the backspace key in the quantity dialog, the last number in the text box is removed but the cursor is moved to the front of the text box.

**Comment by davidjreese** [comment]
think i have this fixed - some tricky business making all the control stay in sync with garbage input and valid input.
