### ISSUE TITLE
[Dransik 2.0] Able to click through mage in potion shop and interact with chest behind counter

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#164]
### Able to click through mage in potion shop and interact with chest behind counter

1. Log into a character
2. Go to the New Korelth Potion Shop located at 356,1483
3. Notice the chests behind the counter with the mage shop keepers
4. Click and drag the chest onto your avatar
5. Notice that the chest now becomes a transparent version, and remains on the ground

![image](https://user-images.githubusercontent.com/112193703/195478795-7bfad576-3379-4d98-a022-19129e1a6209.png)

#### Expected:
Player should not be able to drag ground items unless they are within 1 tile of the item.

#### Actual:
Player can drag the ground chests from 2 tiles away behind the counter, even underneath the mage that is standing on it.

**Comment by davidjreese** [comment]
fixed this i think.
