### ISSUE TITLE
[Dransik 2.0] NPC name showing overtop of black fog when NPC is off screen

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#165]
### Map progression not persisted after logging in

1. Log into a character
2. Find an NPC in the black fog in the town of Jeel located at 277,836
3. Move your character so the NPC is just off screen
4. Notice that the NPC's name shows up above the black fog, even though they are off screen

Example:
![image](https://user-images.githubusercontent.com/112193703/195479959-71afd7d3-de8e-43f1-9b0a-21e4430d1ec8.png)

#### Expected:
When NPCs are off screen, their names should not show up on screen, and should not show up above the black fog.

#### Actual:
When NPCs are off screen, their names show up above the black fog.

**Comment by davidjreese** [comment]
fixed, was there in a build after messing with name plaque for player vanishing
