### ISSUE TITLE
[Dransik 2.0] Clicking on potions to use them while moving, causes laggy movement

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#166]
### Clicking on potions to use them while moving, causes laggy movement

1. Log into a character
2. Purchase some potions from any Potion store
3. Go outside of town and kill some monsters while taking damage
4. Click on the potions in your backpack frantically as you heal your HP and move around
5. Notice that your movement becomes laggy and starts to jolt around. If you continue to hold down movement keys, it gets progressively worse

This is very common scenario when fighting monsters or killing players, you'll need to be able to move around smoothly while using potions. There is a slight stutter when you use a potion, which is normal, but could potentially be lowered. It seems like it is queuing up commands to be used and causing some sort of delay.

#### Expected:
When running around and clicking potions at the same time, movement should be smooth.

#### Actual:
When running around and clicking potions at the same time, movement becomes laggy and starts to jolt around the more you hold the movement keys.

**Comment by davidjreese** [comment]
Made a performance enhancement around using, targeting (hover and otherwise). It looks much better from my tests. Let me know
