### ISSUE TITLE
[Dransik 2.0] Unable to hold shift and hover over enemies to target them

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#167]
### Unable to hold shift and hover over enemies to target them

1. Log into a character
2. Press A to turn on Attack mode
3. Find a monster
4. Hold shift and hover over the monster with the mouse
5. Notice that it does not target the monster

In current Dransik, you can hold shift and drag over a monster or player while in Attack mode to target them. This is especially useful when you are a bower and shooting people from a distance. This is true for any kind of NPC, including Guards and etc.

#### Expected:
When holding shift and hovering your mouse cursor over a monster or player, the monster or player should be targeted.

#### Actual:
When holding shift and hovering your mouse cursor over a monster or player, the monster or player does not become targeted.

**Comment by davidjreese** [comment]
I never knew this existed until you told me. man, there are so many ways to target

**Comment by davidjreese** [comment]
i added this in
