### ISSUE TITLE
[Dransik 2.0] When in a guild, unable to see guild tag on player names or in the Player Info window

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#168]
### When in a guild, unable to see guild tag on player names or in the Player Info window

1. Log into a character
2. Create a guild or join a guild
3. Notice that the guild tag is not showing in your name above your character

Guild tags should show up in the Player Info window and also on the Player names in the world.

Examples:

Player Window
![image](https://user-images.githubusercontent.com/112193703/195484315-27e2d067-38f9-4708-97d8-67a9a847d48e.png)

Player Names in World
![image](https://user-images.githubusercontent.com/112193703/195484400-b2f3525d-0671-4226-a9a0-e8d75e153518.png)

#### Expected:
When in a guild, guild tags should show up in the Player Info window and on Player names in the world.

#### Actual:
When in a guild, guild tags do not show up in the Player Info window or on Player names in the world.

**Comment by davidjreese** [comment]
fixed - i have them in the playerinfo panels (yours and other players) but didn't have them in the name plaques.
