### ISSUE TITLE
Show bank capacity similar to weight capacity for backpack

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#169]
### Show bank capacity similar to weight capacity for backpack

The backpack has a weight capacity that shows on the Player Info screen. It would be great if we can see our bank capacity too in the bank window, so we can manage how many items we have in our bank.

**Comment by davidjreese** [comment]
Making this a post 2.0 feature request as it would require some server work too.

**Comment by davidjreese** [comment]
Fixed
