### ISSUE TITLE
[Dransik 2.0] When picking up items off the ground quickly, sometimes items become invisible in backpack

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#171]
### When picking up items off the ground quickly, sometimes items become invisible in backpack

1. Log into a character
2. Find some monsters and slay them
3. Leave all the drops on the ground until you have a bunch of drops around you
4. Start right clicking all the drops around you to pick them up
5. Notice that in random cases, an item you picked up may not be visible in your backpack until you relog

#### Expected:
When picking up items off the ground, they should be visible in your backpack.

#### Actual:
When picking up items off the ground, randomly they become invisible in your backpack.

**Comment by davidjreese** [comment]
Fixed - could not reproduce after my latest rounds of work on the system.
