### ISSUE TITLE
[Dransik 2.0] Pressing T while in the text box on the help screen, changes focus to Chat Console

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#173]
### Pressing T while in the text box on the Help window, changes focus to Chat Console

1. Log into a character
2. Ensure the Chat Console is open and that the text box is not showing
3. Press ESC to open the Settings menu
4. Click Help to open the Help window
5. Click in the text box on the Help window
6. Press T
7. Notice that the focus has shifted to the text box on the Chat Console instead of staying within the Help window text box

By default T is bound to the chat button, which makes sense since it's been that way forever in Dransik. We just need to check when the text box on the Help window is focused, it shouldn't attempt to run the command to focus the Chat Console window.

#### Expected:
When typing T into the text box on the Help window, focus should stay within the text box on the help window.

#### Actual:
When typing T into the text box on the Help window, focus is shifted to the Chat Console.

**Comment by davidjreese** [comment]
fixed
