### ISSUE TITLE
[Dransik 2.0] Unable to target monster on top of items

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#174]
### Unable to target monster on top of items

1. Log into a character
2. Find a monster and kill it until it drops something.
3. Position another monster on top of that item that dropped
4. Attempt to click on the monster while in Attack mode to target it
5. Notice that you are unable to target the monster while it is standing on top of an item. It interacts with the item first, even though the monster is on top of it.

#### Expected:
When a monster is on top of an item, should not be able to pick up the item, and should target the monster instead.

#### Actual:
When a monster is on top of an item, clicking on it interacts with the item underneath instead of targeting the monster.

**Comment by davidjreese** [comment]
I have stable object sorting now and it picking the top one along with monsters on top of objects
