### ISSUE TITLE
[Dransik 2.0] Unable to drag items on top of each other while on the ground

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#175]
### Unable to drag items on top of each other while on the ground

1. Log into a character
2. Drop 2 items on the ground on different tiles
3. Drag 1 item and try to drop it on top of the other item
4. Notice that the item goes back to the same tile, as you can't drop two items on the same tile

#### Expected:
When dropping items on top of each other on the same tile, items should be allowed on top of each other, or combine in a stack if it's a stackable item.

#### Actual:
When dropping items on top of each other on the same tile, items are not allowed to stack, and they stay in their respective squares.

**Comment by davidjreese** [comment]
the current rule is (just confirmed it works right):
if 2nd item is the same type it stacks.
if 2nd item is a different type disallow it. 

Are you saying the 2nd rule should be removed? seemed wrong to stack a bunch of stuff on a tile to me but what do I know?

**Comment by athacus** [comment]
I would say it should function this way. 

If dropping an item on top of an item that can stack, should combine into the stack.
If dropping an item on top of an item that doesn't stack, should just go on top of the item.

In current dransik, yes items drop on top of each other on the same tile. This happens when monsters drop loot, or when a body decays onto the ground. Can also happen if people want to stack items on the same tile.

**Comment by davidjreese** [comment]
good to know. i also know why sometimes you cant combine things. its b/c some other thing is on the tile too... and its selecting that secretly.

**Comment by davidjreese** [comment]
fixed
