### ISSUE TITLE
[Dransik 2.0] When resting in a bed, a couple issues

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#176]
### When resting in a bed, a couple issues

1. Log into a character
2. Bring some gold, and go to a bed to rest, for example located at 349,1452
3. Click on the bed pillow to open the resting window
4. Click on any amount of Stamina Points
5. Notice that your character remains standing outside of the bed while resting in the bed

#### A couple additional issues to note regarding beds:
- The title of the window is called Bed Left, it should probably named something else
- There is some spacing issue in the option 10 Stamina Points - 200 Gold and Full Sleep - 1000 Gold
- The text inside of the box "How long do you wish to sleep?" can be adjusted a few pixels as it touches the outside container border

Examples:
![image](https://user-images.githubusercontent.com/112193703/195747341-b6cca5f6-e88b-41b0-bdef-c61b65e526f7.png)

![image](https://user-images.githubusercontent.com/112193703/195747538-6f0afe65-04bb-4970-9d58-3b75a9e9c692.png)

It seems it is not always reproducible, but the nameplate does always show. After additional testing, I determined that it happens when you sleep in attack mode.

![image](https://user-images.githubusercontent.com/112193703/195748150-58d99fdd-65be-42c4-b0d6-7d077a89ef92.png)

#### Expected:
When sleeping in a bed, your character does not show up outside the bed at the same time.

#### Actual:
When sleeping in a bed, your character shows up outside of the bed as well as animating inside of the bed.

**Comment by davidjreese** [comment]
I didn't even know you could sleep!

**Comment by athacus** [comment]
Haha yes, quickest way to recover your stamina to full

**Comment by davidjreese** [comment]
this is working for me in the current build. can you reproduce it?

**Comment by davidjreese** [comment]
marking as fixed - if youc an repro I can reopen but will need a better repro path. I think the bad text/formatting should be wrrttein up as a different bug WITHOUT the 2.0 label so we can fix that after this is out.
