### ISSUE TITLE
[Dransik 2.0] Dragging items into lights, causes them to brighten

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#177]
### Dragging items into lights, causes them to brighten

1. Log into a character
2. When it's night time, find some torches that are emanating light
3. Drag an item into the light being emanated
4. Notice that the light reflects off the items, causing them to brighten

Example:
![image](https://user-images.githubusercontent.com/112193703/195748589-6ce37c14-4b48-4363-befd-7cf5f9f67a67.png)

#### Expected:
When dragging items around emanating light, should remain the same colour.

#### Actual:
When dragging items around emanating light, the items start to brighten.

**Comment by davidjreese** [comment]
Is this really a bug? Lights brighten items in the world (terrain and objects). Isn't that what is happening here?

**Comment by athacus** [comment]
Hmm, well considering the light in dransik wouldn't brighten items that you are dragging into it, I'd say it is a bug. If the item is on the ground already, that's different. But if you are actively clicking and dragging it, it doesn't function that way in current Dransik.

**Comment by davidjreese** [comment]
Fixed this i believe along with other issues - also player gear that has light adds to overall player light now when equipped.
