### ISSUE TITLE
When attempting to go through a portal shortly after going through a portal, message shows twice

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#178]
### When attempting to go through a portal shortly after going through a portal, message shows twice

1. Log into a character
2. Go to a portal such as New Korelth portal on Krythan located at 584,1492
3. Go through the portal which will take you to Parian portal
4. Attempt to go back through the portal shortly after
5. Notice that the message "You are too weak to reenter the portal" shows twice.

Example
![image](https://user-images.githubusercontent.com/112193703/195749405-f76b3b8f-a2d6-4d7f-9641-af68dfe2131d.png)

#### Expected:
When attempting to go through a portal shortly after going through one, should show the message once each time you try to go through.

#### Actual:
When attempting to go through a portal shortly after going through one, the message shows twice each time you try.

**Comment by davidjreese** [comment]
This is from the server, its a bug in live code. adding to the general list

**Comment by davidjreese** [comment]
This is only happening 1x now. so yay
