### ISSUE TITLE
[Dransik 2.0] After opening a bank window and walking away, the bank window remains open

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#179]
### After opening a bank window and walking away, the bank window remains open

1. Log into a character
2. Go to the bank in New Korelth located at 332,1475
3. Click on the banker to open the bank window
4. Walk away from the banker
5. Notice that your bank window remains open and you can interact with items in your bank

Also, any ground container should close after moving away from it. This is also an issue with Barrels, Bags inside of banks, any kind of container.

#### Expected:
When opening a bank window or any container, should be closed automatically after moving.

#### Actual:
When opening a bank window or any container, remains open after walking away from it.

**Comment by davidjreese** [comment]
fixed
