### ISSUE TITLE
Item Name issue on certain types

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#18]
Clicking on a wall torch in shop north of Kristanna's room - returning "Torch East." This is fixed in AE with desc field in editor. Assuming this option may not exist for Dransik.

**Comment by hgesler** [comment]
See another example, Bed Left

![image](https://user-images.githubusercontent.com/74884462/189427961-8fb6f79e-5e34-4758-a73c-6e90b29bc6ea.png)

**Comment by davidjreese** [comment]
the description property and mechanic was added to types  so this is now fixed.
