### ISSUE TITLE
[Dransik 2.0] Going into a ladder or cave entrance to a location that you haven't been before, causes delay

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#180]
### Going into a ladder or cave entrance to a location that you haven't been before, causes delay

1. Log into a character
2. Go to the entrance to Hell on Krythan side located at 440,1896
3. Enter the cave entrance
4. If you haven't entered here before, the delay is about 3 seconds until it loads the map

Not sure if this one is related to the fact that it needs to load another map, or if because the map is all black in that area. Also noticed this issue when I went into the portal at Dragon Island. This would give an unfair advantage to an enemy if you are stuck loading the map while they are attacking you.

#### Expected:
When going to a new place you haven't been before through a cave or ladder, should load in a reasonable amount of time.

#### Actual:
When going to a new place you haven't been before through a cave or ladder, takes about 3 seconds or so to load before your game responds.

**Comment by davidjreese** [comment]
Hmm, I don't aggressively cache art/textures (lazy load them). I think that it might just take a second to load all the new art tiles and such. Maybe I need to pre-load them.

**Comment by athacus** [comment]
Yes, I think that might help and remove the potential disadvantage of this loading scenario.

**Comment by davidjreese** [comment]
it is about 1 second for me. maybe less. i cached a bunch more art. not sure if there is much else I can do. let me know.
