### ISSUE TITLE
[Dransik 2.0] Bank window not closing automatically

### ISSUE THREAD

**Issue by Jabelius** [IronWillGames/Dransik#181]
After bank is opened it will not close when moving away from banker. You can also drag items to backpack and ground from bank window (should be prevented).

![image](https://user-images.githubusercontent.com/1352768/195759778-a99ad570-edfd-445a-9dcb-e5e5a3d2de2e.png)

**Comment by Jabelius** [comment]
Was duplicate.

**Comment by davidjreese** [comment]
fixed, thanks
