### ISSUE TITLE
[Dransik 2.0] Map progress for current session resetting after entering cave entrance

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#183]
### Map progress for current session resetting after entering cave entrance

1. Log into a character
2. Walk around and reveal some of the map
3. Go to a cave entrance such as Hell entrance on Krythan located at 440,1896
4. Walk around a bit inside Hell
5. Log out
6. Log back into the same character
7. Notice that your map progress has reset for the current session

This may be isolated to places you haven't visited before. Might need to start with a fresh map to replicate.

#### Expected:
The map progression for the current session should not reset after entering a cave entrance.

#### Actual:
The map progression for the current session resets after entering a cave entrance.

**Comment by athacus** [comment]
This issue happens in other ladders, not just Hell entrance:
Banished Knight Castle ladder inside Toxicum 160,1505
Toxicum Entrance 1 from Krythan 172,1490

**Comment by davidjreese** [comment]
Fixed this - trapped exit requests.
