### ISSUE TITLE
Unable to buy items from shops when the quantity exceeds your weight

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#184]
### Unable to buy items from shops when the quantity exceeds your weight

If you attempt to buy potions from a shop in a quantity that will exceed your weight, nothing happens. The dialog closes, but the purchase is not completed. No error message is shown either.

Future improvement to show an error message when the player is trying to buy more items than they can hold.

**Comment by davidjreese** [comment]
Making this a post 2.0 client feature as it requires some changes to the buy/sell client/server exchange.

**Comment by davidjreese** [comment]
think i fixed this with the other container work i did. cofirming

**Comment by davidjreese** [comment]
confirmed
