### ISSUE TITLE
[Dransik 2.0] Strange colour issue happened after coming out of cave entrance

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#185]
### Strange colour issue happened after coming out of cave entrance

1. Log into a character
2. Go to the cave entrance in New Korelth at 348,1445
3. Go inside the cave entrance
4. Go back inside the ladder

The colours changed to this
![image](https://user-images.githubusercontent.com/112193703/195958576-dc31bd61-a0a8-41c9-9a90-d2fe8e617b52.png)

![image](https://user-images.githubusercontent.com/112193703/195958667-bacaac8e-1bc2-4cbb-abe3-de316dcf8e6d.png)

Seems to affect everything, even items on the ground.

**Comment by davidjreese** [comment]
i had that happen too recently. werid

**Comment by davidjreese** [comment]
fixed i am pretty sure - this was messed up. also fixed the flash to daylight bug
