### ISSUE TITLE
[Dransik 2.0] Some (all?) floor and wall tiles don't change with nearby light sources

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#186]
Turning on the light illuminates the doors, signs on the wall, player, and item on the ground but not the floor and walls.  Might be the same as #177 since the contrast between the two is just more noticeable.  Day time will light up the Walls and Floors instantly at 4 am.

![image](https://user-images.githubusercontent.com/112813257/195965019-ddb90b27-43ea-43b8-9bda-ef472aa2201f.png)

![image](https://user-images.githubusercontent.com/112813257/195965026-ec7590af-c9ae-44ba-bb32-c63ebf6d945f.png)

**Comment by davidjreese** [comment]
yep - happened when i fixed zordering to make items stable ins tacks on the ground
