### ISSUE TITLE
[Dransik 2.0] Adding E-pool is limited to the amount left in your current level for each skill

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#187]
For example: at level 2 in a skill I have 85/125 exp. When adding epool I can only ever add 40 exp to that skill.

Leveling up by using Epool also doesn't update the skill window so you have to relog to get the right level displayed.

**Comment by davidjreese** [comment]
I limmited Epool application at 1 level at a time. So you have to click for level 1, then use it again for level 2, etc... this felt like a better (more reasonable) user experience to me than skipping through levels with huge numbers. Unless you disagree, I will leave that part.

I will fis the refresh issue though. shouldn't have to relog.

**Comment by athacus** [comment]
@davidjreese In current Dransik, if you dump a bunch of EXP into epool, it just boosts the level as high as it can go. Today I used 150000 epool into my bows and it went to around level 35. It took me like 5 seconds, but if I wanted to level that up 35 times, would take a couple minutes. I think it should increase as many levels as possible, since that's what people from current Dransik would be used to.

**Comment by davidjreese** [comment]
it seems odd to blow through so many levels at 1x to me. it also makes the UI a lot more obscure. as it is now you can see oh, this much to next level. use I. and now this much to next level. etc..

using it all at once you can't see where you will end up easily in any kind of UI design I can think of that's reasonable. i guess I am wondering if the 35 clicks the random time or two you have to do it is a common use case or more a rare thing even for power players.

**Comment by athacus** [comment]
I think you could also leave this as is for first launch and gather community feedback. Probably couldn't hurt.

**Comment by davidjreese** [comment]
cool - will flag it as such.

**Comment by AESeryth** [comment]
If it's being left as is, the limit needs to be increased by 1. Currently takes two adds to get to the next level.

**Comment by davidjreese** [comment]
reopening to look at the having to do it 2x to get to the next level

**Comment by davidjreese** [comment]
fixed now, spending 'all allowed with slider" will push you to next level. Skill will also refresh locally now after spending
