### ISSUE TITLE
Closing Crafting Window without crafting breaks onlook

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#19]
From Talazar: Whenever you open a crafting window then close it without crafting something and you go to identify something by ctrl + clicking it will only give you the message "you are busy doing something else" and will have to relog to fix it.

**Comment by AESeryth** [comment]
This is likely from the fix for https://github.com/IronWillGames/Dransik/issues/6

That issue would happen without doing anything special. The last log always survived until a milling success.

**Comment by davidjreese** [comment]
This was introduced by me fixing you being able to do 2 things at 1 time (yes - issue #6) (which had other problems). I updated to handle the crafting case when cancelling selection.

I fixed the last log thing elsewhere but at the same time.

**Comment by davidjreese** [comment]
Confirmed this worked on STAGE. Will go out with next server release.
