### ISSUE TITLE
[Dransik 2.0] When attempting to buy 1000 pickaxes, only purchases 1

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#191]
### When attempting to buy 1000 pickaxes, only purchases 1

1. Log into a character
2. Have at least 500,000 gold
3. Go to a merchant that sells pickaxes located at 3475,3069
4. Click on the merchant to open the Buy/Sell window
5. Click on Buy
6. Drag the slider on the pick axe over to 1000
7. Click Buy
8. Notice that only 1 pickaxe was purchased

NOTE: This may be an issue with other items that are not stackable. I think it should stop the player from purchasing since they wouldn't be able to carry that many anyway. Could also do something like buy as many as possible until their container is full. Not sure about the best way before the server side changes that need to be done for the error message with the weight limit. Maybe needs to be tackled at the same time.

Confirmed this seems to happen with other items such as armor in the Armor Shop like Wooden Shield.

**Comment by davidjreese** [comment]
ah, i thought i checked for if it was stackable but probably forgot

**Comment by davidjreese** [comment]
Fixed - stackable treated as singles
