### ISSUE TITLE
[Dransik 2.0] When performing trade skill, reticle for targeting does not show

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#192]
### When performing trade skill, reticle for targeting does not show

1. Log into a character
2. Purchase any kind of trade skill item such as a pickaxe
3. Click on the pickaxe in the backpack
4. Notice that the targeting reticle does not show

Reticle missing
![image](https://user-images.githubusercontent.com/112193703/195996971-80e75e9c-b295-4f7a-8a26-566811084ac0.png)

This is also for things like if you are going to use food from your backpack, basically any usable item from your backpack that requires a target.

#### Expected:
When using a trade skill item such as pickaxe, lumberjack axe, saw etc, should show the targeting reticle.

#### Actual:
When using a trade skill item such as pickaxe, lumberjack axe, saw etc, the targeting reticle is missing.

**Comment by davidjreese** [comment]
Fixed this in last patch
