### ISSUE TITLE
[Dransik 2.0] After learning new skill for the first time, does not show up in Skills window

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#193]
### After learning new skill for the first time, does not show up in Skills window

1. Log into a character that does not have the Magery skill yet
2. Purchase some healing scrolls from any potion shop
3. Find some monsters and take damage
4. Use the healing scroll to heal yourself
5. Notice that you are gaining Magery experience and you have the skill. However, once you click on the skill in the skills window, it does not show

NOTE: Even after relogging, can't see the Magery skill. Might just be this particular skill that is bugged out.

Skills window
![image](https://user-images.githubusercontent.com/112193703/195997254-50607f44-c178-4295-aae4-f96af32080b4.png)

#### Expected:
When learning a new skill, should show up in the skills window.

#### Actual:
When learning a new skill, does not show up in the skills window.

**Comment by davidjreese** [comment]
It is a group node with only 1 skill - The only skill under Magery is Mage Weapons

Magery is a group node. It shouldn't level, should it? Or do group node level in Dransik.

**Comment by athacus** [comment]
Yes in current Dransik, there is a magery skill and you get experience in it by using scrolls. I think that means it should maybe not be a root node, or make them levelable too.

**Comment by davidjreese** [comment]
so it Dransik, magery is s skill that you can level too? It shows a levelbar and whatever?

**Comment by davidjreese** [comment]
This is what it looks like now (can't expand because there are no skills open under it). eventually it will be able to expand' Does that seem right?

![Image](https://user-images.githubusercontent.com/669018/196060792-4105bc4e-0d31-49a6-becf-895468616e69.png)

**Comment by davidjreese** [comment]
I think this is the fix.
