### ISSUE TITLE
[Dransik 2.0] Lighting from item in backpack, giving light to environment

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#194]
### Lighting from item in backpack, giving light to environment

1. Log into a character
2. Have an item in your backpack that produces light
3. Ensure it is night time
4. Unequip the item and put it in the top left corner of your backpack
5. Equip the item
6. Notice that the lighting around where the item previously was is gone

The difference is minimal, but it's noticeable when it happens.

Before:
![image](https://user-images.githubusercontent.com/112193703/195997814-cc2068e2-5afb-48a8-971d-bf37128dd18b.png)

After:
![image](https://user-images.githubusercontent.com/112193703/195997822-092ac09f-f3be-4f80-b6d8-08d314f14ed1.png)

#### Expected:
The lighting for items in the backpack shouldn't affect the environment lighting.

#### Actual:
The lighting for items in the backpack affect the environment lighting.

**Comment by davidjreese** [comment]
Fixed this i believe along with other issues - also player gear that has light adds to overall player light now when equipped.
