### ISSUE TITLE
[Dransik 2.0] Running while attempting to use items in your backpack, causes them to turn transparent

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#195]
### Running while attempting to use items in your backpack, causes them to turn transparent

1. Log into a character
2. Purchase potions or scrolls from any Potion shop
3. Find a monster and take some damage
4. Attempt to run around while using potions or scrolls
5. Notice that sometimes the items become transparent until they are moved again

Example
![image](https://user-images.githubusercontent.com/112193703/195998364-ad685a7b-d8f7-4df5-a950-9c120536ef5d.png)

I think this is something to do with the fact that it is trying to move the items around at the same time as it is using them. This is a common scenario when fighting monsters or fighting people, using potions while moving needs to be fluid.

#### Expected:
When running and using items in your backpack, they should remain in the same position and not change to transparent.

#### Actual:
When running and using items in your backpack, they sometimes turn transparent until they are moved again.

**Comment by davidjreese** [comment]
I found the bug causing them to be stuck transparent. fixed that.
