### ISSUE TITLE
Add a hotbar option for easy item use

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#196]
### Add a hotbar option for easy item use

One of the most requested features is adding a hotbar to the UI for easy use of items such as potions and scrolls. I think now that we are in the new client, adding something like this will be much easier than it was in the old client. Some rules around the hotbar can be:

- If it's an item that's equippable, should equip the item
- If it's an item that's usable, should use the item

**Comment by hgesler** [comment]
This is available in new client
