### ISSUE TITLE
[Dransik 2.0] When shift+dragging to split a stack, quantity window should gain focus

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#197]
### When shift+dragging to split a stack, quantity window should gain focus

1. Log into a character
2. Have some gold in your backpack
3. Hold shift and drag to split the stack
4. Notice that the quantity window pops up, but it does not immediately gain focus

Normally we shift+drag to split a stack and immediately start modifying the quantity. There is an extra click needed to click on the text box to start modifying the quantity.

#### Expected:
When shift+dragging to split a stack, quantity window should gain focus.

#### Actual:
When shift+dragging to split a stack, you need to click on the text box in the quantity window to start modifying it.

**Comment by davidjreese** [comment]
fixed - also made it smart like the new trade and shopkeeper edit boxes where it keeps out bad characters
