### ISSUE TITLE
[Dransik 2.0] When holding CTRL to click an item and check it, does not show identify cursor

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#198]
### When holding CTRL to click an item and check it, does not show identify cursor

1. Log into a character
2. Hold CTRL to click on an item to look at it
3. Notice that the cursor for looking does not show

Example:
![image](https://user-images.githubusercontent.com/112193703/195999224-179316d7-2b09-43d7-a126-b0b0408eef44.png)

Interestingly enough if using the identify skill, it actually uses this cursor:
![image](https://user-images.githubusercontent.com/112193703/195999293-49dc82ac-d460-4633-b400-8d26bd3fbad2.png)

#### Expected:
When holding CTRL to look at an item, the cursor for identifying the item should show.

#### Actual:
When holding CTRL to look at an item, the cursor remains the same mouse cursor.

**Comment by davidjreese** [comment]
I am thinking about this because key mappings could interfere with just looking for CTRL button being pressed. What if someone just maps it to some button, maybe just a mouse press?  looking for a MOD key and seeing if its a MOD key for just the Look command is the only test thing to test for.

**Comment by athacus** [comment]
Yeah I think it would be whichever key you are holding to do the LOOK command would show this cursor. I just mentioned CTRL because that's the standard command in Dransik for performing the LOOK command.

**Comment by davidjreese** [comment]
cursors implemented
