### ISSUE TITLE
Review the message feedback given to players when using various tools/items

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#20]
For example, using bellows does not give player any feedback about what's going on with forge, though the forge does say something when it's cooled off.

I imagine this happens with a lot of the basic tools for crafts/starting area items.

**Comment by hgesler** [comment]
Checked a few tools; did a pass on bellows, oven, cotton.

**Comment by davidjreese** [comment]
closing this based on comments and it being in the fixed column
