### ISSUE TITLE
[Dransik 2.0] When moving an item from your backpack to the bank, shows in a different location

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#201]
### When moving an item from your backpack to the bank, shows in a different location

1. Log into a character
2. Go to a bank located at 3453,3070
3. Talk to the banker to open the bank
4. Attempt to drag an item into your bank
5. Notice that while it's moving into the bank, another copy of the item appears in a different place in your backpack as a transparent version. The same happens when moving an item from your bank into your backpack, it just appears in a different place in the bank.

#### Expected:
When moving an item from your backpack into the bank, the item should move without showing another transparent version.

#### Actual:
When moving an item from your backpack into the bank, another transparent version appears randomly in your backpack during the move.

**Comment by davidjreese** [comment]
This is due to position being said vs new container ordering i believe.

**Comment by davidjreese** [comment]
fixed - some old code needed to be deleted from when I first wrote all that drag stff
