### ISSUE TITLE
[Dransik 2.0] Dragging an item from the ground on top of gold on the ground, puts the item underneath gold

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#203]
### Dragging an item from the ground on top of gold on the ground, puts the item underneath gold

1. Log into a character
2. Find a monster and kill it until it drops two items, one that is gold and one that isn't
3. Drag the item on top of the gold on another square
4. Notice that the item goes underneath the gold

#### Expected:
When dragging an item on top of gold on a square, the item should go on top of the gold.

#### Actual:
When dragging an item on top of gold on a square, the item goes underneath the gold.

**Comment by davidjreese** [comment]
This works as designed. Thinks stack in a standard order now based on their type. i don't think preserving the order of the stack is a gameplay dynamic. does this really matter?

**Comment by athacus** [comment]
I think when you are dragging items onto tiles, they should go in the order they are dragged. I don't know that gold should immediately go under other items. It wouldn't emulate current Dransik functionality. Maybe it's fine to just leave for now and fixed later if needed? But if we want to try and emulate Dransik as much as possible in the Dransik 2.0 version, this would function differently for sure. You could drag items on the same square in any order, and items only stack if you drag an item onto a tile that currently has a stackable item drawing at the top.

**Comment by davidjreese** [comment]
went ahead and implemented it this way, most recent one on top
