### ISSUE TITLE
[Dransik 2.0] Strangeness around experience points

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#204]
### Strangeness around experience points

I noticed a couple things with base experience that need to be adjusted:

- [x] The experience tables seem to have been altered. Currently Level 99 to 100 takes 4.2 billion EXP, when previously it was around 4mil. By hovering over the base experience bar, I can see this. Max level in current Dransik is just under 77 million EXP.
- [x] When attacking monsters with a weapon that has a maxed skill, not gaining experience to my overall level. Tested this by attacking demons in Hell with my Large Blade which is level 100, and my experience needed until next level wasn't going down
- [x] Unable to see my current total experience in the UI for base experience or skill experience, only % until next level. Current Dransik displays how much experience you currently have in base experience and in skill experience while showing a bar for % until next level

How current Dransik shows experience:
![image](https://user-images.githubusercontent.com/112193703/196002078-443efb88-c380-46f4-9762-7501295d6dda.png)

Skills experience in skill window
![image](https://user-images.githubusercontent.com/112193703/196002155-cae54933-b238-4669-b69e-9d032bd98e76.png)

Your total experience is shown under your level. The bar on the right side of the player info is your progress until next level.

I think the experience is adding in the background, and the to next level amount just always shows the amount, not how much is remaining until next level. Probably just need to show the total experience somewhere in the UI, so we can see it is increasing.

**Comment by davidjreese** [comment]
Fixed the UI so that the total values of current experience are shown now for skills and player stats. hover still shows amount to next level

**Comment by davidjreese** [comment]
Thanks, found the issues with the main player experience showing wrong here.

**Comment by davidjreese** [comment]
think i have the exp not showing as you killed things fixed now to with the proper display of experience and such

**Comment by davidjreese** [comment]
confirmed
