### ISSUE TITLE
After dying from hunger, health bar remains at 0

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#205]
### After dying from hunger, health bar remains at 0 

I died from hunger and my health bar still shows 0. This is because I am not regenerating any life, so it hasn't caused it to redraw with the new values. 
![image](https://user-images.githubusercontent.com/112193703/196002519-686b8c72-0d7b-47f3-be6c-df13fc2614d7.png)

There is some adjustments to be made to this Player Info window to line things up better, but was waiting for more functional issues to be resolved first before logging that.

**Comment by davidjreese** [comment]
this is how it is on live right? or doe sit do something different on live server?

**Comment by athacus** [comment]
Yeah I think it is similar on live server right now. But eventually should respawn the character normally with like 75% HP like it usually does, and the bar should update. I think that would be the right fix.

**Comment by davidjreese** [comment]
okay, moving that to regular bug queue. its crazy that its that way in live... sigh

**Comment by davidjreese** [comment]
fixed for next release
