### ISSUE TITLE
[Dransik 2.0] Nameplates above character in game view are hard to see on top of some tiles

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#206]
### Nameplates above character in game view are hard to see on top of some tiles

Depending on the tiles behind my character's nameplate and the alignment I have, it is hard to see my character's name.
![image](https://user-images.githubusercontent.com/112193703/196002655-21709c9b-d7c0-4c79-a964-a27739f2c37a.png)

This character is named Testinator and has a Neutral alignment, so it blends in well with dirt. I think we need to adjust the font for displaying some things, but also how we make the character nameplates more prominent on top of background tiles.

**Comment by davidjreese** [comment]
decreased size of font and added a black outline.
