### ISSUE TITLE
[Dransik 2.0] No auto run command

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#207]
### No auto run command

Current Dransik has an auto run command. It functions like this:

Hold ALT and start to hold a directional key, then let go of ALT. It will continue to run in that direction. I wonder if we can get an auto run command in this version as well. Maybe it auto runs in the direction based on the last directional key you pressed. This also works if holding two directional keys like up + right, down + left, etc. It will run on a diagonal.

**Comment by davidjreese** [comment]
created a input mapping for this and made it default to ALT. tested it a bit. seems to work okay
