### ISSUE TITLE
[Dransik 2.0] Strength bonus not giving extra weight capacity

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#208]
### Strength bonus not giving extra weight capacity

1. Log into a character. 
3. Put on an item that gives extra +20 strength such as Rune Gaunts
4. Notice the strength increases by 20, but the weight limit does not increase

#### Expected:
Your maximum weight limit should increase when wearing items that give extra strength.

#### Actual:
Your maximum weight limit only goes off of base strength.

**Comment by davidjreese** [comment]
is this a bug on live too? it looks like I am doing everything right for weight calculation on client.

**Comment by athacus** [comment]
This one is not a bug on live. Quite common to get extra strength from rune gaunts, greater helm of strength and have more weight capacity.

**Comment by davidjreese** [comment]
and it shows in the UI properly when that happens?

**Comment by athacus** [comment]
Yes that's correct. The weight limit in current UI is calculated based on additional strength. I think the highest I've seen is 600 max.

**Comment by athacus** [comment]
Here is an example of current server. I have 115 strength total, and it calculates to max 495.

![image](https://user-images.githubusercontent.com/112193703/196062975-002e974c-cec3-4179-a7cb-b521e6a0732e.png)

**Comment by davidjreese** [comment]
found it. thanks
