### ISSUE TITLE
[Dransik 2.0] Unable to buy more than 50 potions at a time

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#209]
### Unable to buy more than 50 potions at a time

1. Log into a character
2. Ensure you have at least 10000 gold
3. Go to a potion shop located at 356,1483
4. Click on the potions shop merchant
5. Click Buy to open the Buy window
6. Find the Greater Healing Potions shop item and put in 51 quantity
7. Click Buy
8. Notice that no transaction occurred

Maybe something else is capping this at 50.

**Comment by davidjreese** [comment]
could this be weight?

**Comment by athacus** [comment]
Nope not this time. I attempted with plenty of space available.

**Comment by davidjreese** [comment]
server was enforcing it. made server 1000
