### ISSUE TITLE
[Dransik 2.0] Self lighting stacking to the max after killing monsters

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#211]
### Self lighting stacking to the max after killing monsters

The self lighting seems to stack and progressively go higher as I kill more monsters. Then it reaches max and stays that way, which is quite bright.
![image](https://user-images.githubusercontent.com/112193703/196573595-774f78d2-dbd2-472c-a13a-7479668abbd6.png)

**Comment by davidjreese** [comment]
fixed - equipment that has a light adds a small amount of light and a small increase in the radius and should be capped. Let me know.
