### ISSUE TITLE
Guard spawned on top of another guard in North Parian Bank

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#212]
### Guard spawned on top of another guard in North Parian Bank

1. Log into a character
2. Go to North Parian Bank located at 3438,2959
3. Notice that there is 2 Elite Guards animating on top of each other just outside the bank

Example is red underlined
![image](https://user-images.githubusercontent.com/112193703/196841699-57e34f53-81ea-4957-ac67-23d4f12ecc4a.png)

I was fighting them and I noticed 3 guards come at me instead of 2.

#### Expected:
Guards should not spawn on top of each other.

#### Actual:
This particular instance has 2 guards on top of each other.

**Comment by davidjreese** [comment]
oh man... so sad . server code

**Comment by hgesler** [comment]
Deleted extra placed guard.
