### ISSUE TITLE
[Dransik 2.0] Monsters show grey nameplate after changing target

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#213]
### Monsters show grey nameplate after changing target

1. Log into a character
2. Find 2 monsters
3. Turn on attack mode and target a monster
4. Click on the other monster to target it
5. Notice that the old monster has a grey nameplate while the current targeted one has a red nameplate

Example:
![image](https://user-images.githubusercontent.com/112193703/196842087-aa971a22-08bc-4ab4-b4cb-f208f69fce0c.png)

#### Expected:
After changing monsters, old monsters should not have grey nameplates.

#### Actual:
After changing monsters, old monsters have grey nameplates.

**Comment by davidjreese** [comment]
Thanks - fixed
