### ISSUE TITLE
[Dransik] In Thieve's Choke near hell, there is a weird spot where you can move back and forth to change music

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#215]
### In Thieve's Choke near hell, there is a weird spot where you can move back and forth to change music

1. Log into a character
2. Go to Thieve's Choke at this location 383,1831
3. Notice the music that is playing
4. Move one square to the right
5. Notice that the music changes
6. Move one square to the left
7. Notice that the music changes again

This is a strange place to have a change in music. I think these boundaries should be adjusted.

**Comment by hgesler** [comment]
Made the music continuous for that island from the land bridge
