### ISSUE TITLE
Able to drop items on top of ladders

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#216]
### Able to drop items on top of ladders

1. Log into a character
2. Find a ladder located at 160,1506
3. Drag an item on top of the ladder
4. Notice that you can drop the item on top of the ladder

#### Expected:
When dropping items on a ladder, it should be an invalid location.

#### Actual:
Able to drop items on top of ladders.

**Comment by davidjreese** [comment]
Moved this to the list of bugs for Dransik (server)... seems to be a problem on live version too

**Comment by davidjreese** [comment]
@Dev-Tyrant  i think you fixed this with the solid change right?

**Comment by Dev-Tyrant** [comment]
Confirmed Fixed.
