### ISSUE TITLE
Talk area increases the taller the chat window is.

### ISSUE THREAD

**Issue by douggesler** [IronWillGames/Dransik#220]
Talk area increases the taller the chat window is.

![Image](https://user-images.githubusercontent.com/2902938/197665079-a60fac56-7e0b-44ca-99a7-1636f07414d3.png)

**Comment by davidjreese** [comment]
hah, i never made it that big. i sort of liked having multiple line support. will see if I can keep that but maybe not.

**Comment by davidjreese** [comment]
This was the way I had the anchor setup. I changed it to anchor to the bottom fully so it wont scale based on window
