### ISSUE TITLE
[Dransik 2.0] Close [X] floats down the taller the window is

### ISSUE THREAD

**Issue by douggesler** [IronWillGames/Dransik#221]
The Close [X] floats down the taller the window is

![Image](https://user-images.githubusercontent.com/2902938/197665496-685692d3-d27e-4dd7-81dd-6593edc03f9e.png)

**Comment by davidjreese** [comment]
what window is that. the anchor is set properly and don't see that happening on my machine

**Comment by davidjreese** [comment]
i managed to see it a little bit. maybe something odd about the 9 box rect

**Comment by davidjreese** [comment]
found it - some of the anchors were off by a pixel so that would cause the item to float as the scale gets big or small enough
