### ISSUE TITLE
Feature:Add weight to backpack header?

### ISSUE THREAD

**Issue by douggesler** [IronWillGames/Dransik#222]
Possibly add weight to backpack header
or a fill bar with colors (green good, yellow 90% full, red full)
idk just ideas

![Image](https://user-images.githubusercontent.com/2902938/197665858-c6c1755d-a743-49c2-b8ba-33eaf75113e5.png)

**Comment by davidjreese** [comment]
Good idea, but taking the 2.0 off of it for now so it is in the general but pool. will require a server change.
