### ISSUE TITLE
Conversations need to stick out more

### ISSUE THREAD

**Issue by douggesler** [IronWillGames/Dransik#223]
Conversations need to stick out more.  
maybe blue background or border?
maybe center on game play area

![Image](https://user-images.githubusercontent.com/2902938/197667164-630c869e-c64d-419a-bb8f-983cd2951099.png)

**Comment by AESeryth** [comment]
I think it needs to be centered on or close to the play area or people will lose it in the blackness when their play area is way off to the right for whatever reason.

**Comment by davidjreese** [comment]
made it flash a bit more and keeping it in play area

**Comment by davidjreese** [comment]
made it on edge of player so its hard to miss
