### ISSUE TITLE
Click on Silvest Seaker locks up client input

### ISSUE THREAD

**Issue by douggesler** [IronWillGames/Dransik#224]
Clicked on Silvest Seeker.  His dialog opened, but pushing any button or key did nothing, had lot close Dransik using [x].
I couldn't move any containers with mouse, no mouse clicks, esc and all other keys didn't work

**Comment by davidjreese** [comment]
fixed, wasnt hiding the choices locally after it was sent so if they weren't overwritten by server they stayed up as old value.
