### ISSUE TITLE
[Dransik 2.0] Unable to use well, have to relog to be able to interact (using object, conversations etc)

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#225]
Click on a well
Cursor briefly change to a use reticule, then reverts to green arrow. Receive chat print saying "What would you like to pour water in?"
Not able to select anything to add water to 
Must relog in order to interact with any npc/object after this happens (stuck in usecode somewhere)

**Comment by davidjreese** [comment]
fixed this i believe. let me know if something else breaks - lol
