### ISSUE TITLE
Equipped items don't grant their stat bonus on login

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#226]
Items need to be re-equipped before their stats are applied.  Attack damage will be lower, stat requirements that are only met after gear bonuses aren't met, and you can be overweight when you shouldn't be.

**Comment by davidjreese** [comment]
@AESeryth - do you know if its like this on live Dransik? the client doesn't control this so i think it might be a server bug which means is live too.

**Comment by AESeryth** [comment]
Yes it seems to be happening on live too. Unequipping the item for the first time will remove the stat bonus also even though it wasn't granting one. This means your racial bonus can get wiped out for the session if you log in and remove an item that is supposed to grant the same stat.

**Comment by davidjreese** [comment]
Thanks, this is a core dransik issue - definitely need to fix it though. unreal. will look at it when we start working on the server issues more.

**Comment by AESeryth** [comment]
This seems to work fine on normal players. Might be a GM only thing?

**Comment by davidjreese** [comment]
AHHH - I know why then. YES, GMs when they login don't have their type info sent down like a normal player. That is why you are 'invisible' on login. Its a terrible hack. So after you do a /h it then shows type and such but the state is messed up I think on the server.

Keep this issue open, we need to have a GM login actually go through the same enter game flow properly. I will fix it after we launch this client.

**Comment by davidjreese** [comment]
I believe I fixed this!!!! tst in new biuld
