### ISSUE TITLE
Dragging chest and letting go of it in outpost east of starter town, it disappears from screen

### ISSUE THREAD

**Issue by douggesler** [IronWillGames/Dransik#227]
Dragging chest and letting go of it in outpost east of starter town, it disappears from screen.  Leave and come back, it shows up

![Image](https://user-images.githubusercontent.com/2902938/197669057-8b9de02a-1b83-4fd0-8244-2182f229dbb0.png)

**Comment by davidjreese** [comment]
fixed the visual issue with this. the foot lockers should be locked down in editor
