### ISSUE TITLE
Footchest in East Silvest Guard Outpost can be picked up/removed

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#228]
Both footchests in east silvest guard outpost need to be locked down in the map

**Comment by hgesler** [comment]
It is marked as Locked Down. The other placeable obj in other towns such as Barrels are not marked that way. Going to see what happens when I remove locked down flag.

**Comment by hgesler** [comment]
Footchests are just not going to be placable objs. Since they can be crafted, any placed in world can be moved. Removed them from this area.

**Comment by hgesler** [comment]
Since these are crafted items, they can be picked up like objects even if locked down for some reason. I'm thinking easiest fix is to make a new type for the static obj.

**Comment by davidjreese** [comment]
@Dev-Tyrant is this something we can fix? I just tried and was able to drag the footchest still? not sure if its a collision of types of user chests vs world containers or something else

**Comment by hgesler** [comment]
It’s because it’s also craftable. I tried locking it down or other options but that isn’t working. needs to be new type I guess.Sent from my iPhoneOn Jan 8, 2023, at 7:47 AM, David Reese ***@***.***> wrote:﻿
@Dev-Tyrant is this something we can fix? I just tried and was able to drag the footchest still? not sure if its a collision of types of user chests vs world containers or something else

**Comment by Dev-Tyrant** [comment]
I fixed it with placing a different type
