### ISSUE TITLE
[Dransik 2.0] When using food (spider legs) must click on player; if you click on ground around player you have to relog

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#229]
Click on spider leg, then click on ground. Must relog as client does not register any actions after that point.

**Comment by AESeryth** [comment]
This is happening for all (?) usable items with crosshairs.  I think it's a new issue from a recent build.

**Comment by davidjreese** [comment]
I assume this is dransik 2.0

**Comment by hgesler** [comment]
Closing to merge with bug #218
