### ISSUE TITLE
Silvest quest - Galen's quest for lizard men isn't working

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#23]
"Randomly while killing thiefs and fighters in the valley of the death on silvest it said I gathered all the lizard tails for Galen for the quest by the kobold castle. when I went to Galen he asked if I still was looking for lizard man, but every time I kill a lizard men I never get the tail, I've killed quite afew so far."

**Comment by AESeryth** [comment]
Completing Galen's quest to collect Lizard tails breaks Gornaka's (guy in the Silvest Pub) quest to collect Triddle Blood Sacs. Gornaka will tell you your current progress but you can't get any new updates. This might be related to the Lizard quest breaking.

**Comment by hgesler** [comment]
They were evidently copied from one another somehow and Gornaka was using Galen flag, so you would never be able to complete Gornaka or Galen quest.
