### ISSUE TITLE
[Dransik 2.0] Can't add Epool to Magery skill

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#230]
The old client lets you add epool to magery but the new one doesn't.

![image](https://user-images.githubusercontent.com/112813257/198121706-f6516484-da8f-4154-8d42-cd8fce8efe3b.png)

**Comment by davidjreese** [comment]
okay, so this is the one that is 'special' just magery. i thought there was something about it being locked but there is nothing underneath magery? its just a single top level skill.

**Comment by davidjreese** [comment]
found the magic combo of flags to show exp / level
