### ISSUE TITLE
Morgwang Quest not counting kills for Orcs where they spawn, just in the grassy areas

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#231]
Will have to look into this more, it is checking a zone similar to the Guard Murphy quest #78

**Comment by hgesler** [comment]
Needs to be checked

**Comment by davidjreese** [comment]
This works fine - but not all orcs are counted. Orc Mage's don't count as Orcs as an example

**Comment by hgesler** [comment]
This was in relation to the quest X,Y check in player Gen not including an area of land that was added. This has been fixed. The other issue regarding mages not being counted is a separate issue. I changed to include mages it but it was reverted to be just orcs as per original design.Sent from my iPhoneOn Dec 3, 2022, at 9:56 PM, David Reese ***@***.***> wrote:﻿
This works fine - but not all orcs are counted. Orc Mage's don't count as Orcs as an example

**Comment by davidjreese** [comment]
closing as fixed then
