### ISSUE TITLE
[Dransik 2.0] Adding item to greyed out slot of hotbar causes that to appear greyed out.

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#233]
1. Drag an item like a weapon to any hotbar slot.
2. Move that item to your bank.
3. Drag an item (I used healing potions and gold) to the greyed out slot. Would expect it to replace that item, but instead it is also greyed out even though its in my bp and can be used.

**Comment by davidjreese** [comment]
good catch. fixed
