### ISSUE TITLE
[Dransik 2.0] Using an item from bp on a placed item or npc in the world will make its name appear

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#234]
Could be a feature, but sure feels like a bug as the items were not designed to have type names displayed.

1. Click on a raw food item - I used triddle meat.
2. Click on any object in a building I tried on oven, and on chair.
3. Notice the name is displayed above the object in red.

I bring you..."Chair North"
![image](https://user-images.githubusercontent.com/74884462/198734569-a997dfd6-41dd-46bd-aeae-f21fe1661e68.png)

**Comment by davidjreese** [comment]
I changed this to be a feature - if you click on something now it shows the name. if you click on another object it shows that name instead. (in white). fades out on deselect
