### ISSUE TITLE
[Dransik 2.0] Play area/game window can get pushed up past top window border, cannot fix without deleting config

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#235]
![image](https://user-images.githubusercontent.com/74884462/198751435-d5c09b8d-2fc6-4496-8dab-b7fa08f9bca5.png)

Not a HUGE deal as I can delete my players .cfg file, but easy to reproduce and was done unintentionally.

1. With play area in default location of top left corner, resize the play area bigger using the slide adjust button on top left side to most zoomed/biggest size
2. Grab the top bar somewhere in the brown area and move the mouse up. Play area jumps up to an out of bounds location. Can't fix in full screen mode. Have to delete .cfg.

**Comment by davidjreese** [comment]
fixed, i made sure it only goes offscreen on the bottom so you can mess with the titlebar controls still
