### ISSUE TITLE
[Dransik 2.0] Big FPS loss when turning on the HP floater or Show My Name setting

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#236]
The game goes from a steady 165 fps (capped there for me) to 130 with either the HP floater or the Show My Name, and then down to around 65 fps with both of those on at the same time.  

No other UI elements that I've found affect FPS too much.

**Comment by davidjreese** [comment]
I cached the expensive part of this operation so I think it solved any problems.
