### ISSUE TITLE
[Dransik 2.0] Spam Using an item then walking will make you laggy until you stand still

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#238]
Here I spam click the torch then start walking. The lag only stops when I stand still for a second. Other players see me walking normally.

This happens with items in your backpack, changing gear quickly with hotkeys, and probably any other way of Using items quickly.

https://user-images.githubusercontent.com/112813257/198755726-adf6a15a-a609-4aac-9a86-3a04a7478f98.mp4

**Comment by AESeryth** [comment]
This also happens when holding shift and hovering over multiple monsters quickly.

**Comment by davidjreese** [comment]
Made a performance enhancement around using, targeting (hover and otherwise). It looks much better from my tests. Let me know
