### ISSUE TITLE
[Dransik 2.0] Font size in books is too large

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#241]
The title can overlap onto the next page and the text of the pages gets cut off.

![image](https://user-images.githubusercontent.com/112813257/198914022-fe4c3483-3977-4f1a-8c49-8ab9c957abe4.png)

Old:
![image](https://user-images.githubusercontent.com/112813257/198914173-1e3f43bd-730e-4672-a4b8-023d86c9d2d5.png)

**Comment by davidjreese** [comment]
updated this with a normal font
