### ISSUE TITLE
Log out isn't interrupted by movement, combat, etc

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#242]
After clicking Exit Game you can move, fight, talk to NPCs, etc and after the 10 seconds, you'll be logged out anyway. 

Log out should emulate current client which is basically you can't do anything once you logout (close the client). 
1. Just putting player in stasis at start (would force them to watch)
2. Could try to detect move / use / attack and interrupt (not sure this is possible  without a lot of work).

**Comment by davidjreese** [comment]
This one is a bigger change than new client aunch. Going to move it to the general pool and fix it after the client.

**Comment by davidjreese** [comment]
putting player in stasis at start of logout ... will see what happens.

**Comment by davidjreese** [comment]
this works pretty well i think.
