### ISSUE TITLE
Review Type names that are now being displayed with left click inspect

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#244]
Some items in the world have odd names that were not designed to be shown.

![image](https://user-images.githubusercontent.com/74884462/199085239-d4bddc1e-3c1e-4069-92db-12aaf6f5de0f.png)

![image](https://user-images.githubusercontent.com/74884462/199085264-c166b90e-2ed4-4ff7-ac5f-1f5d99a0fb42.png)

**Comment by davidjreese** [comment]
No way to detect this by code. Can we just go through the types as they come along or we do editor work and fix the data. if so you can leave this ticket and assign to general pool for when design work happens to prioritize it

**Comment by hgesler** [comment]
This is ultimately going to require some editor work, _could also_ be a code change too. Thankfully not too many types in Dransik, but changing a type name might need to be changed elsewhere in script if its referenced. That would be all editor/data.

Other option is to add a "description" field to types similar to what AE uses, which would require some implementation from one of you guys. Then not as much chance for messing up type names referenced elsewhere.

**Comment by davidjreese** [comment]
this is all fixed now
