### ISSUE TITLE
OnEquip of an item that fails to equip should not move the item to default bp location

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#246]
When attempting to equip an item that you do not meet req for, the item is moved in backpack to the default position (top left corner) of bp. It properly prints the message, I think it'd be better if the item stays where it is in bp.

**Comment by davidjreese** [comment]
This isn't possible without some major garbage... can you confirm it works properly live? I think this is some server work which I would rather do after the new client launches.

**Comment by hgesler** [comment]
Ah, yeah if it has to wait that's fine - I'm fairly certain this is also
live.

**Comment by davidjreese** [comment]
This was fixed recently
