### ISSUE TITLE
[Dransik 2.0] When moving items in backpack, original item/location is colored in again before moving to the new item location

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#247]
When moving an item in bp (or in world also I guess?) a faint ghost image of the item is shown in the original's location, which is handy. 

Minor detail here but I noticed that when moving items in the backpack, I noticed that the coloration of the ghost/original item location is restored very briefly before the item then moves to the new location. Not sure if it's _necessarily_ a bug, but it does stick out some.

![image](https://user-images.githubusercontent.com/74884462/199093977-729d5585-3aef-4220-ac90-574f025abb18.png)

![image](https://user-images.githubusercontent.com/74884462/199094017-9ed73c25-aed5-48c2-a9b6-377b41d213d7.png)

![image](https://user-images.githubusercontent.com/74884462/199094051-8a3a283f-31c7-4c4d-a0ee-644ce15abfea.png)

![image](https://user-images.githubusercontent.com/74884462/199094076-bad62915-6e81-4e9b-a55a-4a9725996969.png)

**Comment by davidjreese** [comment]
fixed, this is one of those thigns that can break anytime I mess with cursors state. thing Its more right now
