### ISSUE TITLE
Silvest quest - Mordred in the Silvest Inn, Quest broken

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#25]
"Mordred in the Silvest Inn he has me on a quest to get his family heirloom from the thief fort in the undead valley, by getting a key from the thiefs and fighters that spawn outside there, when i got the key I talked to him again and told me I should be able to get in to get the heirloom from the bookcase but I cant get the door to open when i go to the door thats in the bedroom thru the passage it says "Unsure how to open this door" or something like that (Quest text is also spelled wrong they spelled it Hierloom when it should be Heirloom)"

**Comment by hgesler** [comment]
Was using Set instead of SetFlag.

Cleaned up this quest and offered alternate ending - you can take the golden shield or just get more exp.
