### ISSUE TITLE
Weird visual when sleeping in beds

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#251]
![image](https://user-images.githubusercontent.com/74884462/199374975-6576fad8-b1a5-41bb-997b-703f257f15a9.png)

**Comment by hgesler** [comment]
Ahhh I'm a ghost 👻

**Comment by hgesler** [comment]
the name of the obj Sleeper probably needs updated or something, wonder if I can use SetName on it.

**Comment by davidjreese** [comment]
Fixed - will only see your ghost self if you are a GM now.
