### ISSUE TITLE
[Dransik 2.0] Music not changing from intro music while in Toxicum

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#252]
### Music not changing from intro music while in Toxicum

1. Log into a character
2. Go to the Toxicum entrance location at 175,1492
3. Notice the music playing
4. Go inside the ladder
5. Log out of the game
6. Log back into the game
7. Notice that the intro music carries over from the login screen and keeps playing 

The music should resume playing the Toxicum music instead of the intro music from the login screen.

**Comment by hgesler** [comment]
There was no music regions painted in the dungeon or toxicum island. Added music track for that place.
