### ISSUE TITLE
Message received when purchasing Items needs extra space between quant and product name

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#253]
![image](https://user-images.githubusercontent.com/74884462/199711045-ce33911c-eda3-4e14-9d1e-ea10efc78009.png)

**Comment by hgesler** [comment]
Confirmation on use of product has same problem.

![image](https://user-images.githubusercontent.com/74884462/199711245-b2f9ab3f-b64c-4d4d-80ba-615be8622ce9.png)

**Comment by hgesler** [comment]
This is still happening

**Comment by davidjreese** [comment]
Fixed this
