### ISSUE TITLE
[Dransik 2.0] the tooltip on most of the buttons in settings menu say "Quit Dransik"

### ISSUE THREAD

**Issue by marmotini** [IronWillGames/Dransik#254]
![image](https://user-images.githubusercontent.com/72478718/199761451-10ab5d26-06b7-4a8f-b51d-8717682868e6.png)

![image](https://user-images.githubusercontent.com/72478718/199762012-a4244efb-2744-4d3b-be61-ff829b3c4f51.png)

**Comment by hgesler** [comment]
lol, subtle hint? GO AWAY, WE DON'T WANT ANY

**Comment by davidjreese** [comment]
Fixed all the tooltip messages in the options menu (and submenus) to be relevant to what is going on.
