### ISSUE TITLE
Follower window is emptied if follower leaves play area

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#259]
1. Tame a creature (I tamed a wolf somewhere near 590,45,0) 
2. Bring up follower window C
3. Walk fast enough or around obstacles so that the wolf is off screen briefly.
4. Notice the follower window is now empty as if you have lost the follower, however, if you close/open the window it restores that follower info. The follower is still under your control.

Expected: Followers should not clear from the follower window for being off screen

**Comment by davidjreese** [comment]
@hgesler - this is a limitation of Dransik server. And, the follower menu on live Dransik near as I can tell can't deal with it well either.

I am removing the 2.0 label on this and moving it to the post launch fix list.

The needed to change is to add some more robust client/server communication on client 'death' or 'removal' vs just being too far away.

**Comment by davidjreese** [comment]
Fixed
