### ISSUE TITLE
Some new monsters can't be Tab or Shift targetted with Target Protection on

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#26]
Rabid Snow Wolf
Shadlox The Chilled

Still need to check some others

**Comment by hgesler** [comment]
What is the difference on these new creatures? Assuming they're missing some setting in their stat block or type

**Comment by hgesler** [comment]
They didn't have mass/weight set so I just added some values that looked appropriate.

**Comment by hgesler** [comment]
That did not fix it.

**Comment by AESeryth** [comment]
This is fixed on the test server.

**Comment by davidjreese** [comment]
Woohoo! Fixed - Ithanks
