### ISSUE TITLE
[Dransik 2.0] Character creation name field

### ISSUE THREAD

**Issue by EJaynes** [IronWillGames/Dransik#261]
Character creation name field awkward. I'm not sure what character limit is set to for a new player's name, but this window gets a bit janky. Could do without the vertical scroll bar if you can push the horizontal scroll bar external from the text field itself.

![image](https://user-images.githubusercontent.com/108539164/200055801-73bcd740-15b4-4f7d-87d3-c74a2cedb489.png)

**Comment by davidjreese** [comment]
yup, broke when i put in the new bigger font
