### ISSUE TITLE
[Dransik 2.0] Unable to remap Joypad 1 (B button) to anything because it's force bound to Esc menu

### ISSUE THREAD

**Issue by marmotini** [IronWillGames/Dransik#263]
For example, in my Input settings I want to set the B button on my Xbox controller to toggle attack mode (as well as Q on my keyboard), so I have this setting:
![image](https://user-images.githubusercontent.com/72478718/200080710-a8a74716-4932-4076-9091-2c8264f52ab0.png)

But when I press B on my controller, it is instead toggling the Esc menu. If I bind to any other controller button it works fine, it's just the B (Joypad 1) button that is forcibly bound to Esc and I can't change that to be anything else since it doesn't show up as one of the Input settings options.

**Comment by davidjreese** [comment]
Should I just remove the 'controller bringing up the menu by default' or is there a better button I should use by default for that?

**Comment by davidjreese** [comment]
Changed it to a better key for Joypads

![Image](https://user-images.githubusercontent.com/669018/204141233-b04ce776-5e2b-4a23-a237-ae2a764b1e65.png)

**Comment by marmotini** [comment]
Hmm maybe can just remove the controller B button from bringing up the menu by default, since things in the menu would need a mouse to interact with anyways
