### ISSUE TITLE
Anna Bell kill 20 rats quest in Silvest not working

### ISSUE THREAD

**Issue by marmotini** [IronWillGames/Dransik#264]
I killed way over 20 rats (counted each one to double check too) and when I talk to Anna Bell again afterwards she just says:

![image](https://user-images.githubusercontent.com/72478718/200094423-a7cd52ea-e114-4efb-9843-98f10e36969b.png)
![image](https://user-images.githubusercontent.com/72478718/200094431-8c779f75-0591-40f6-923c-01c239fbb047.png)

**Comment by hgesler** [comment]
Did you get an update in the chat about them at all?

**Comment by marmotini** [comment]
no updates at all in the chat, only the first message saying that I picked up the quest

**Comment by hgesler** [comment]
Maybe try again; there was a script issue last week you may have gotten stomped on. Or try on a fresh char. I didn't have any issues with it.

**Comment by marmotini** [comment]
tried it with another character and it did work on that one! and tried it with that first character again and still didn't work there, maybe something got messed up with that first character somehow when I was logged into that one during the script issue
