### ISSUE TITLE
[Dransik 2.0] Using a potion after targeting, causes target to hide but keeps target

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#265]
### Using a potion after targeting, causes target to hide but keeps target

1. Log into a character
2. Find a monster and target it
3. Notice that the target shows around the monster and the health bar shows too
4. Use some potions in your backpack
5. The target no longer shows, but the monster is still targeted

Moving close to the monster will still attack it, just can't see the active target.

#### Expected:
Using a potion should not hide the target on the monster.

#### Actual:
Using a potion causes the target to be hidden, but still keep the target.

**Comment by davidjreese** [comment]
Ah... I see - thanks

**Comment by davidjreese** [comment]
Fixed
