### ISSUE TITLE
[Dransik 2.0] Objects in BP become transparent and drag scale can be challenging

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#266]
When I am running around using potions and fighting monsters, sometimes the potions try to move in the backpack, causing them to go transparent until the next time they get moved. After moving them, all is good again.

Also, able to continue using the potions while they appear transparent.

Considerations

- [x] Stop all the transparent draw bugs
- [x] FIgure out some 'right way' to handle the scale of the drag object (since it can go to and from windows of different scale).

**Comment by davidjreese** [comment]
NOTE:  THis happens when moving from bank to backpack if the items (or stack) will cause you to become overweight. The item goes back to where it was but is ghosted.

**Comment by davidjreese** [comment]
- I think I found a pretty good middle ground for the drag scaling issue to make it easy to place but still big enough to see when dragging.

**Comment by davidjreese** [comment]
Found and fixed the transparent bug too
