### ISSUE TITLE
[Dransik 2.0] Can only have 1 skill floater open at a time

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#267]
Unsure if this is a bug, but I was trying to open various skill floaters and realized I can only have 1 open at a time.

1. Open skill window.
2. Press the lock button on a skill to open the floating skill bar (I did a melee skill - Blunts)
3. Open floater for a different skill (Large blades) and notice that it doesn't appear together, it replaces the currently open floating skill bar.

I would expect to be able to have multiple skill bars open simultaneously.

**Comment by davidjreese** [comment]
not sure when this broke or if it every worked right. fixed
