### ISSUE TITLE
[Dransik 2.0] Movement feels delayed and not smooth

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#271]
I've been running around killing monsters, and it often feels like my movement is delayed. If I let go of my movement keys after holding them, my character runs another 1 or 2 tiles before it stops. I think movement is pretty critical because we often have to juke around our enemies to get cuts, or avoid cuts when killing. It would be great to see a smoother movement system.

**Comment by davidjreese** [comment]
I think the movement is much better than live Dransik. I am not sure what to do with this. It uses the same movement system in general but I made it responsive to single taps. There is a possibility that a movement is 'in-flight' after you depress a key so an extra step (or two depending on latency may happen).

I am going to post some people on the test server to get some more feedback before attempting anything or closing it.

**Comment by athacus** [comment]
Yeah I think the best idea is to get some pvp combat going on test and get some feedback. Can go from there.

**Comment by davidjreese** [comment]
Closing this out - will reopen or create a new issue if needed.
