### ISSUE TITLE
[Dransik 2.0] The filter buttons in store window have incorrect tooltip

### ISSUE THREAD

**Issue by marmotini** [IronWillGames/Dransik#272]
![image](https://user-images.githubusercontent.com/72478718/200437420-b2555c3a-7673-4e9e-a733-e0c2cf17e47f.png)

The tooltip always says "Filter to only ____" but those buttons are actually toggling whether those categories are included or not, maybe should be "Exclude ____" and "Include ____" depending on button state

**Comment by davidjreese** [comment]
fixed!
