### ISSUE TITLE
Suggestion: add a chat console message that explains when you're over encumbered and can't pick up anything else

### ISSUE THREAD

**Issue by marmotini** [IronWillGames/Dransik#273]
I was suddenly not able to pick up loot off the ground and it seemed like it was bugged, and only after a few minutes of furiously clicking everything and trying to drag loot into my backpack and relogging, did I realize that it's because I hit the weight limit.

**Comment by davidjreese** [comment]
This is good, we need to add this to the base Dransik post new client launch

**Comment by davidjreese** [comment]
this is fixed now. part of the containers weight and info rewrite
