### ISSUE TITLE
[Dransik 2.0] Global Music Volume level settings need adjusted to use full range of slider

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#275]
When I have my computer's sound turned up to 100%, and I'm adjust the music, I cannot begin to hear the music until it is at the 60% mark. It scales quite quickly. Additional bug with Sound FX levels changing the music levels as well.

**Comment by hgesler** [comment]
Possibly related bug: https://github.com/IronWillGames/Dransik/issues/276

**Comment by davidjreese** [comment]
Created a master volume so it is now separate from sound volume.

Clamped lower bound on volume decibel ranges into more audible spectrum.
