### ISSUE TITLE
[Dransik 2.0] Sound FX volume slider also changing Music volume output

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#276]
Turn both sound and music up to 100%. Turn down the sound slider to 50-60%. Notice the music also decreases in volume but the slider remains unchanged.

**Comment by davidjreese** [comment]
Yes, this is actually master volume... i don't know if I can change each sound effects themselves... will either figure that out or update the name of the control

**Comment by davidjreese** [comment]
Created a master volume so it is now separate from sound volume.

Clamped lower bound on volume decibel ranges into more audible spectrum.
