### ISSUE TITLE
[Dransik 2.0] my HP bar goes crazy and doesn't reflect my actual HP (instead show's the monster's HP) when I bandage myself while attacking a monster

### ISSUE THREAD

**Issue by marmotini** [IronWillGames/Dransik#277]
https://user-images.githubusercontent.com/72478718/201420934-4e467171-98f1-4b07-ada1-0d92a3b1e306.mp4

**Comment by davidjreese** [comment]
lol - video is so helpful. thanks

**Comment by davidjreese** [comment]
That was a weird one. Think I got this fixed now. Let me know otherwise
