### ISSUE TITLE
Guild quest issue - Book 3 brazier can become bugged

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#278]
The brazier in the left room, 3rd from top can become bugged. Perhaps a quality/health/res value issue since a server restart seems to fix it. Sometimes logging can fix it - but not always. I'm assuming the player's id is maybe stored in mem and when that gets cleared or brazier values get cleared it works properly.

**Comment by hgesler** [comment]
Did a major port of this script to match AEs. Tested with group of 5 yesterday; we made it through 1x, but no one was ported out at the end. After fixing that need to test 2x.

**Comment by davidjreese** [comment]
@douggesler fixed this
