### ISSUE TITLE
[Dransik 2.0] Double clicking a book quickly will print same book contents/text twice

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#279]
Teleport to Lord Kargoth book at 457,872,1
Double click the book
Notice the same text is entered in the book; one on the left page, and identical on the right page.

![image](https://user-images.githubusercontent.com/74884462/201494067-e5858906-c662-42cd-82a3-8b7b5e4be121.png)

**Comment by davidjreese** [comment]
this is technically a server bug... it sends the same page 2x when double clicking. happens on live but client might not show it.

fixed it anyway on client (stupid server)
