### ISSUE TITLE
[Dransik 2.0] Macro check always results in failure even if I select correct answer

### ISSUE THREAD

**Issue by marmotini** [IronWillGames/Dransik#282]
First time it happened I thought I was either dumb or maybe clicked the wrong one, so the next time I made sure to take a picture of the question before I clicked a choice. I clicked NO on this one and it then said "You cannot craft for 24 game hours." The first time it happened I think I clicked YES on a different question and it said I was wrong also but pretty sure I was right. So seems like any of the choices picked is resulting in wrong answer

![image](https://user-images.githubusercontent.com/72478718/202569909-d4f8849a-a448-40c6-b0dc-bb6343022725.png)

![image](https://user-images.githubusercontent.com/72478718/202569952-6ddb3730-3a2b-4e19-a71d-13169b34d8fd.png)

**Comment by davidjreese** [comment]
i think this is fixed... jeeez we gotta change macro checking and penalty

**Comment by davidjreese** [comment]
Fixed and verified
