### ISSUE TITLE
Walking on top of stairs while an npc is on the stairs causes the stairs to disappear until relog; can still interact

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#283]
Cannot reproduce very reliably; was in cellar in silvest killing rats, Went above ground by running into it (OnTouch) and it ported me upstairs, but the stairs going back down were gone. Clicking on the spot where they were brought them back/teleported as expected. Just a visual issue. Doesn't seem to happen every time.

**Comment by davidjreese** [comment]
Do you have a location for the stairs?

**Comment by hgesler** [comment]
637,379,0

**Comment by hgesler** [comment]
![image](https://user-images.githubusercontent.com/74884462/204418319-835a6d1f-21c6-48de-97e8-47354a0f2eee.png)
this shows same stairs below ground; ran across it horizontally and a rat ran on top of it as well. stairs have disappeared. where center mouse is located in this shot is where stairs should be.

![image](https://user-images.githubusercontent.com/74884462/204418456-b8c3aa6d-bd2a-4212-89a3-3c71dad0806f.png)
notice they are gone; however, I can click the spot where they were and am able to use the (still invisible) stairs.

**Comment by hgesler** [comment]
![image](https://user-images.githubusercontent.com/74884462/204418623-d65ebbfe-b468-4a40-aa6a-110cf271bafd.png)

**Comment by hgesler** [comment]
Relogging and I am able to reproduce; somehow made stairs above those disappear:
![image](https://user-images.githubusercontent.com/74884462/204418894-d404a1de-679f-4f18-9748-a3c903664fb1.png)

**Comment by hgesler** [comment]
![image](https://user-images.githubusercontent.com/74884462/204418968-38a65e0d-5564-41f0-92fb-9ee50cf33fa1.png)

**Comment by hgesler** [comment]
Seems related to if an NPC runs on top of it and you also click or walk over it

**Comment by davidjreese** [comment]
This was a good bug. A more fundamental problem. I see what is happening. Will figure out the best fix.

**Comment by davidjreese** [comment]
Fixed!
