### ISSUE TITLE
Targeting when creature on edge of screen or off screen drops target

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#30]
From codecks: Target sometimes is bugged ( when target being on the edges of the screen or leaving ur screen for second) and u wont swing or it and u need to retarget.

**Comment by AESeryth** [comment]
Seems to be fixed by the new client but I don't have a 100% reproduction for this one.

**Comment by davidjreese** [comment]
flagging this as fixed. if it shows up again, will look
