### ISSUE TITLE
Make the Newbie Training Much Better

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#304]
Phase 1 - popups on trying to open the door before talking to Krystana or using Orb, echo instructions in chat. Tell player to go talk to lumberjack quest guy or how to start crafting, explain the professions and what they mean? make the newbie area more interesting.

**Comment by hgesler** [comment]
Was thinking about this earlier this fall, could place the triggers/invis objects and tie a popup to onbump or ontouch whichever is called there.

**Comment by davidjreese** [comment]
Much of this was done! Other tickets have other things
