### ISSUE TITLE
Voidway Teleporter is broken at Tower Inversa

### ISSUE THREAD

**Issue by Dev-Tyrant** [IronWillGames/Dransik#306]

**Comment by Dev-Tyrant** [comment]
- adding DEBUG Print
- removing Offset and adding Location coordinates to test.

**Comment by Dev-Tyrant** [comment]
Reopening the first gate causes players to enter the wall if they run into it at an angle.

**Comment by hgesler** [comment]
This is still causing issues. Main portal located near 1774,3358,0.

**Comment by hgesler** [comment]
Still causing issues for players. Ticket ref with more info 21154.

**Comment by davidjreese** [comment]
I fixed all this
