### ISSUE TITLE
Guild Quest issue on 2nd book when choosing an incorrect dialogue

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#31]
When speaking to wraith NPC under Hothbra, if incorrect dialog is entered, it removes you from zone & unable to return until you suicide which causes a client crash. Relogging didn't solve, only dying > crash > relog.

Related:
https://github.com/IronWillGames/Dransik/issues/36

We gotta fix these damn guild quests bugs... another post about it today and several more PMs

**Comment by hgesler** [comment]
Time for me to hate life

**Comment by davidjreese** [comment]
@douggesler @hgesler @Dev-Tyrant this is fixed right?

**Comment by Dev-Tyrant** [comment]
I would assume so, @douggesler put in a fix back in December for the guild quests.

**Comment by hgesler** [comment]
Not sure we just fixed book 3, wasn’t aware anything was wrong w 2Sent from my iPhoneOn Jan 8, 2023, at 10:52 AM, Shane Davis ***@***.***> wrote:﻿
I would assume so, @douggesler put in a fix back in December for the guild quests.

**Comment by davidjreese** [comment]
This bug is so old... i am closing it out. I know a lot of people get to book 3 and I haven't seen this rerported

**Comment by ghost** [comment]
this was prolly related to the new client and the stasis it would provide after the quest failure via dialog,
