### ISSUE TITLE
Players not showing up crim

### ISSUE THREAD

**Issue by nevermd** [IronWillGames/Dransik#330]
I logged in next to Hulnar and there was a crim player there.  He later told me he had killed Hulnar prior to my logging in.  His name appeared green to me and stayed green even though he hit me.  I hit another uncrim player a few minutes later and turned crim.  I haven't had a chance to reproduce this but possibly an issue with player name color when you log in with them on screen.

**Comment by davidjreese** [comment]
Duplicate Issue: https://github.com/IronWillGames/Dransik/issues/341
