### ISSUE TITLE
Unable to craft tools with Blacksmith Forging

### ISSUE THREAD

**Issue by Dev-Tyrant** [IronWillGames/Dransik#332]
![image](https://user-images.githubusercontent.com/74842329/205780066-ad67bcd7-c383-4f0a-8987-29ae7a43a8b7.png)

I have the required level to craft it, 

![image](https://user-images.githubusercontent.com/74842329/205780153-a74638a2-a3e6-4eba-b35d-187e2f771052.png)

**Comment by davidjreese** [comment]
fixed
