### ISSUE TITLE
[2.0] Unable to purchase more then 100 scrolls

### ISSUE THREAD

**Issue by genkelvor** [IronWillGames/Dransik#333]
unable to purchase more then 100 healing scrolls, minor healing scrolls
and
scroll of Rejuvenation, scroll of mass healing and scroll of regeneration can only buy 1 at a time.

**Comment by davidjreese** [comment]
This worked for me. I just bought 200 - did you have enough money, would it have made you overweight?

![Image](https://user-images.githubusercontent.com/669018/206050088-27074036-f58a-40b9-b36b-8b4d6a1236ac.png)

**Comment by Cherrybooze** [comment]
healing scrolls max buy is still 99
