### ISSUE TITLE
[2.0] opening shop crash

### ISSUE THREAD

**Issue by genkelvor** [IronWillGames/Dransik#335]
if you open a show and you're in browsing area for items if you click the shop keeper again it will crash you and will not let me back into the game just keeps crashing everytime I try to reconnect

**Comment by davidjreese** [comment]
I haven't been able to reproduce this.

**Comment by davidjreese** [comment]
Going to close this - I fixed a bunch of things that can cause crashes. more might be there, will treat them as new
