### ISSUE TITLE
[Dransik 2.0] Must click on border of Hotbar to bring in front of other UI elements

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#338]
1. Open Backpack and one Hotbar (any).
2. Place the backpack UI over the hotbar so that the hotbar can be seen on either side and underneath the backpack.
3. Click the LEFT side of the hotbar (anywhere, but for ex the green area under the #). Notice that it snaps to the front as expected.
4. Repeat step 2
5. This time click on the RIGHT side of hotbar (in an empty or occupied - = slot). Notice that it does not snap to front.

It is possible to click the very small 1 pixel border on the Hotbar (this extends around the numbers) to bring it to the front. I'd expect that clicking anywhere in hotbar should snap to front.

**Comment by davidjreese** [comment]
fixed
