### ISSUE TITLE
Mega Backpack in Token Shop not functional

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#34]
From codecks (Talazar) Mega Backpack in Token Shop not functional

Unsure of what the issue is - I'm also not sure what Mega Backpack is supposed to do. Besides have more space. Which is odd because dransik backpack doesn't have slots...is it a weight restriction being lifted?

**Comment by AESeryth** [comment]
Long ago there was a limit to how many items you could have as a free player and buying the backpack unlocked it for you.  I'm not sure exactly how/if it used to work but it might not be relevant anymore.

**Comment by hgesler** [comment]
Does this need to be removed or what.

**Comment by hgesler** [comment]
Mega Backpack is still working.

**If you are not VIP** (aka a FREE player), you are restricted to 250 items in your pack. That INCLUDES quantities in stacks, with exception of gold.
**With VIP**, you can have 250 items in your pack, but stacks are counted 1 for every 100 quantity in the stack (with the exception of gold)
**With Mega Backpack** (which requires VIP), you have a limit of 500 items in your pack and same rules apply as for VIP players.
