### ISSUE TITLE
Tower of Inverna (Boss' Broken)

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#356]
Vic and other players reported timer being broken

Boss is broken btw
In the new tower
Hasnt respawned in 3 hours

Yep, both boss and grinder not spawning at all

**Comment by Dev-Tyrant** [comment]
You need to kill the placeholder to have a chance for the Boss to spawn. 

Also - grinder isn't a spawnable entity, it resides only on one level of the tower, the players must find it
