### ISSUE TITLE
Fourth book teleports are bugged. Some sends you back to hell and some send you inside mountain.

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#36]
Fourth book teleports are bugged. Some sends you back to hell and some send you inside mountain.

[suggested by Tabea Urbgen](https://discordapp.com/channels/695812967463256084/724274768169140224/939878745035141130)

Related

https://github.com/IronWillGames/Dransik/issues/31

We gotta fix these damn things. I dunno why they are so fragile

**Comment by davidjreese** [comment]
@douggesler Here is that bug

**Comment by davidjreese** [comment]
Closing - we dont think this is happening anymore and wasn't able to reproduce
