### ISSUE TITLE
Treasure System Overhaul

### ISSUE THREAD

**Issue by Dev-Tyrant** [IronWillGames/Dransik#376]
Editor Treasure system overhaul, needs to be designed

RED: Individual Treasure for a creature, ie. Snake Meat drops from Snake creatures, or a boss drops a certain item
(currently doesn't work)

BLUE: Treasure Type Table, which can be used to design Tiered Treasure tables for supporting loot distribution 

NPC Data Screen:
![image](https://user-images.githubusercontent.com/74842329/206912907-012a504f-460b-4415-8574-0b6f61d44e19.png)

Treasure Table Editor: 
![image](https://user-images.githubusercontent.com/74842329/206912997-2a6070a1-7162-4b55-b616-8c228fb8fcce.png)
(currently, the max item in the table is 16, any chance to increase that?

**Comment by Dev-Tyrant** [comment]
@davidjreese Is this something you can tackle?

**Comment by davidjreese** [comment]
yeah, i can look at it

**Comment by davidjreese** [comment]
Increased treasure table to allow 64 items per table

**Comment by davidjreese** [comment]
NPCs have their own treasure list now on NPC Dialog - both treasure lists will be rolled against individually
