### ISSUE TITLE
New Gather Resource System - Spawn

### ISSUE THREAD

**Issue by Dev-Tyrant** [IronWillGames/Dransik#378]
"System to spawn resources as ""nodes"" for players to gather from. 
No way to macro, more engaging when finding resources. 
Rare resources spawn in any encounter table. "

![image](https://user-images.githubusercontent.com/74842329/206913210-d647f019-63ba-4448-a7d1-a59fae7738bf.png)

Currently, you can only choose NPCs from the Encounter List, which makes sense. 
The Editor would need to allow me to choose Resources, or maybe a new field type: Node
Then when using the Encounter table, I can choose NPC or Resources to paint and define spawn location, amount, and frequent spawn.
![image](https://user-images.githubusercontent.com/74842329/206913364-838b4980-7b90-4953-886f-fdc5feb52619.png)

**Comment by davidjreese** [comment]
This was released already
