### ISSUE TITLE
Tailoring - Crafting System

### ISSUE THREAD

**Issue by Dev-Tyrant** [IronWillGames/Dransik#379]
Design Tailoring System. 
There is the base work for Scissors with cloth. 
Cloth to be made from cotton using the loom. 
Just need the ability to get the crafting table menu to popup, and able to fill in items in the menu for Trade Object Editor. 
Items to make: 
Bandages, New Bandages(Disease, Poison Healing), Tissues, Cloth Armor, RP Items

Blocker: 
Editor doesn't allow to add of a new Trade Skill: 
![image](https://user-images.githubusercontent.com/74842329/206913520-9d977b2c-03d4-49bf-9f5f-ce1334cba384.png)

**Comment by Dev-Tyrant** [comment]
@davidjreese Can you add new skill: 
"Tailoring": CraftingType.Tailoring,

**Comment by davidjreese** [comment]
I fixed this and I added ability to delete crafting plus removed all the server/client hard coding
