### ISSUE TITLE
Crafting with 0 Stamina causes you to lose resource you are crafting with when you take damage from hunger

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#38]
From codecks: If you attempt to craft something while you have 0 STA and you get that 10 damage due to hunger you will get a message in red saying your status has changed and lose the resource you was using to craft with.

**Comment by hgesler** [comment]
Not able to reproduce without way to set stamina easily

**Comment by davidjreese** [comment]
Lets fix this with item upgrade/crafting rework

**Comment by ghost** [comment]
this is part of the macro prevention/Duplication bug   that check prevented duping

**Comment by ghost** [comment]
it was part of the Scale dupe fix

**Comment by davidjreese** [comment]
this doesnt happen with new crafting switch
