### ISSUE TITLE
Alchemy - Crafting System

### ISSUE THREAD

**Issue by Dev-Tyrant** [IronWillGames/Dransik#380]
//=================================================
//
//	Alchemy.use
//	by Shane Davis @2020
//
//  1. Invisibility Potion(placeholder) on well created blue potion
//	2. Add Starter Ingredient (Droppabled)
//	3. Add Completion Ingredient (Farm Skill related)
//	4. Add Incomplete Vial to Cauldron
//	5. Click Cauldron
//=================================================

Started the groundwork on this, need to complete the design and test it.

**Comment by davidjreese** [comment]
@hgesler - moved this from @douggesler  to you  and put it in progress as its needed to complete the upgrade system

**Comment by davidjreese** [comment]
@hgesler - i think this is done vai your work. close it out?

**Comment by davidjreese** [comment]
I am closing this one out @hgesler - v1 is done.
