### ISSUE TITLE
Chests open on top of one another

### ISSUE THREAD

**Issue by nevermd** [IronWillGames/Dransik#382]
If you have multiple chests in your bank then each one you open appears on top of the first one.  This gets annoying if you have 'Lock Gui' turned on bc then you have to go into settings and turn it off in order to move the chest windows.  Can you either revert back to them opening in a random location (like old Dransik) or better yet keep the location of each chest window locked?

**Comment by davidjreese** [comment]
when you move a container it will remember the location and use the locations in that order. so if you open 
Chest A then it goes to container 1 position, Bag B goes to container 2 positions, and so forth. This way you can define a prescribed layout.

**Comment by ghost** [comment]
bank hack work again eh
