### ISSUE TITLE
Client pause during Combat/Skill interactions

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#386]
Player having issues with sound causing a 1 sec delay in the client/pause.

_"even if i example smelth iron etc. always when i interact with something in game it makes 1sec freezing delay for game window, music, moving etc. that would be great to find solution quikly, i think its the most annoying and its easy to die when go hunting."_

I'm not having this issue in testing.

1. Player has music turned up. FPS / Ping at ~50-60 / 100.
2. Player is smelting iron ore at a town. 
3. Whenever he clicks the forge to smelt, the sound track pauses noticeably . His fps drops. 

This does not seem to happen with conversations, just in combat/skill interactions. Trying to narrow down if it's experience gain or an issue with UI. See private thread here: https://discord.com/channels/695812967463256084/1052012421595799693

https://drive.google.com/file/d/181-2v5ZMfasw90d7bt9hjvfw4qS7FZdU/view

**Comment by hgesler** [comment]
He said he moved the game install to his main hard drive (has two drives, one for games one for everything else) and the issue went away. Not sure this is something we need to support?

**Comment by davidjreese** [comment]
I put the music back on it's own thread. I had disabled this because it was causing a crash (the one where it would just sometimes crash when on the server select screen and other places). I fixed the source code in the midi player and submitted a bug + my fix to the author.
