### ISSUE TITLE
Issue when equipping item from the bank then equipping another item after in the same slot

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#387]
When equipping an item from the bank, then equipping another item after in the same slot, the tooltip for the previous item is still showing. Can also get to a state where no item is showing, but you can hover over and see the tooltip.

Broken Tooltip:
![image](https://user-images.githubusercontent.com/112193703/207758758-d0c833ef-8c8e-49fe-af12-8fc9f56f8781.png)

No Item Tooltip:
![image](https://user-images.githubusercontent.com/112193703/207758779-5b9d08d2-faa2-4738-ab03-d4fd36fb2096.png)

To reproduce:

1. Equip an item such as a chest armor.
2. Open the bank and equip a second chest armor by left clicking.
3. Notice that the correct sprite would be showing.
4. Equip the first chest armor from your backpack that was replaced.
5. Hover over the chest armor on your character to see that the tooltip is showing incorrectly now.

**Comment by davidjreese** [comment]
this is fixed, you cant equip from the bank anymore
