### ISSUE TITLE
Items that give attributes like Strength/Constitution does not show the relevant details in the tooltip

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#388]
Items such as Armor of Great Health or Rune Gauntlets do not show the bonus attributes they provide. I noticed the tooltips specify resistance information. This should also be expanded to show bonus attributes given.

Armor of Great Health gives +20 Con and Rune Gauntlets give +20 Str, this is not reflected in the tooltips.

![image](https://user-images.githubusercontent.com/112193703/207759688-3c88d469-1b23-4ac2-b0ba-29ec2a7eca92.png)

**Comment by davidjreese** [comment]
@hgesler or @Dev-Tyrant fixed this already
