### ISSUE TITLE
Purchasing from Shops with full bank / backpack causes client disconnect

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#389]
From Discord

actually that bug what i found out that it occurs when your bank and backpack is full of stock and game says you that your amount of items is full, after that when you try to go buy anything game instantly crashes, its not only carpentry shop, its others too

_middle parian bank when you try to buy something in lumberjack shop, game instantly crashes.

**Comment by davidjreese** [comment]
I could not reproduce this... will keep trying

**Comment by davidjreese** [comment]
I believe this is fixed. havent been able to repro. part of container amount work i did
