### ISSUE TITLE
Unable to interact with merchants when Fog of War is turned off and they aren't in visibility range

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#394]
If you turn off the Fog of War and try to interact with a merchant outside of the visibility range, it will do nothing. This is the same issue with banks. If you can see the merchant/banker and you are within 2 tiles of them, you should be able to interact with them.

**Comment by davidjreese** [comment]
I think my Fog of War changes in latest build have this working right now. Is there a location you can tell me where I can test this? Or test it and let me know?

**Comment by davidjreese** [comment]
confirmed
