### ISSUE TITLE
+ daggers only show "Dagger" in the tooltip instead of +5 Dagger etc

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#395]
It seems that the tooltip for + weapons only show the name without the + included. +5 Dagger shows Dagger etc. It should show the whole name of the item. There maybe some logic surrounding these special characters causing them to not render.

**Comment by athacus** [comment]
Confirmed same for swords, axes etc.

**Comment by davidjreese** [comment]
FIxed in another issue
