### ISSUE TITLE
After completing quest for Clate in Jeel, experience gained shows at -25536

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#401]
I finished the quest for Clate in Jeel to kill 40 skeletons. After completing the quest, the combat window showed a negative experience amount. The experience was not subtracted, just a visual error.

Clate is located in the Jeel pub at 288,846
![image](https://user-images.githubusercontent.com/112193703/208280221-1bf785a3-c6cb-49e7-b450-ae281bf5c78a.png)

**Comment by Dev-Tyrant** [comment]
UseCode looks correct.
