### ISSUE TITLE
Large Blades quest in Hothbra is bugged

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#403]
The Large Blades quest in Hothbra isn't doable. When I talk to Raglnak, he doesn't let me start the quest. He just says the dialog below:

Raglnak can be found at 506, 1069
![image](https://user-images.githubusercontent.com/112193703/208280724-a995b25b-3232-4bac-b42a-24ccabdf7f16.png)

**Comment by Dev-Tyrant** [comment]
Making sure Q_TRAIN_SWORD is TRUE and Q_TRAIN_SWD_COMPLETE is FALSE
