### ISSUE TITLE
Axes quest in Varg gives a low amount of experience compared to others of its kind

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#404]
The Axes quest in Varg gives a low amount of experience. After killing 20 monsters, it gives 1000 experience to the Axes skill. Compared to other quests in Silvest even where they give you 10000 epool or 25000 epool, this seems like a small amount of experience.

**Comment by Dev-Tyrant** [comment]
Epool for quests have been adjusted on Silvest.
