### ISSUE TITLE
Update Warrior, Archer and Mage Build Attributes

### ISSUE THREAD

**Issue by Dev-Tyrant** [IronWillGames/Dransik#408]
Hijacking this ticket about DEX for criticals as a bigger task of creating reasonable builds for the 3 modes of combat

### Discord discussion we had about it
https://discord.com/channels/695812967463256084/704769329744445502/1058047056800919654

### Attaching image for a good baseline

<img width="358" alt="Screen Shot 2023-01-02 at 4 48 55 PM" src="https://user-images.githubusercontent.com/669018/210282992-aef1f134-1d68-4353-ab6e-849827b194ff.png">

### More discussions on it

![image](https://user-images.githubusercontent.com/669018/210283009-d4ab27f2-734f-4f3c-a1ba-151584c90597.png)

**Comment by Dev-Tyrant** [comment]
### ReDesign
Melee: 3.0% chance to crit every 20 dex (base attr) max: 15%
Range: 2.0% chance to crit every 20 dex (base attr) max: 10%

### Original Desc
crit chance from dex. 
melee and ranged chance needs to be different

Like maybe if dex gave 5% chance to crit every 20 dex for melee and 2.5% for ranged every 20 dex
critting at like a 40% chance with 200 dex that you can get
15% chance to crit with 60 dex as a warrior, might actually be worth losing 400hp for right?

**Comment by Cherrybooze** [comment]
15% crit at 100 dex is useless, this will not make dex at all attractive vs con., the numbers should be higher due how valuable con is.

the original quote of 5% per 20 dex is from project rogue, which has players running around with 200-300 dex, as every item gives innate stats.

**Comment by davidjreese** [comment]
The final changes for Mage/Warrior/Archer are done. Isn't these exactly but borrowed from these ideas and others. Will tune it moving forward. All 3 classes exist and are distnct
