### ISSUE TITLE
Suggestion: If item in shop window is a non-collectable, could it be a one time click to add/remove?

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#409]
For items that don't stack like weapons/armor (not marked collectable in editor I think) would be nice to be able to just click to select/deselect rather than the quantity buttons/slider.

![image](https://user-images.githubusercontent.com/74884462/208328080-df89edba-2311-4c55-9be1-838716d6c4e5.png)

**Comment by davidjreese** [comment]
clicking the row now adds/remove the max quantity of the item.

also, remove the slider and  + / - buttons from non collectables
