### ISSUE TITLE
Desc on Power Hour - Personal says that it gives the "Server" an hour of inc exp

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#410]
Update prod desc on web to say player/individual or your character, etc

![image](https://user-images.githubusercontent.com/74884462/208328604-b48a41ab-3eeb-43c0-a543-db2b934d2de1.png)

**Comment by hgesler** [comment]
This is printed when clicking "Details" button

**Comment by hgesler** [comment]
"increased experienced gained"

**Comment by davidjreese** [comment]
Changed it to personal power hour in details usecode.
