### ISSUE TITLE
Kristanna's intro text should also be printed to char - easy to skip

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#42]
Kristanna's intro text should also be printed to char - easy to skip.
Add some basic commands to this print that have color to make them more readable/attractive to eye than plain grey text.

**Comment by davidjreese** [comment]
@hgesler @Dev-Tyrant This is done (for now anyway right)?

**Comment by hgesler** [comment]
Yes, the entire first area could use another pass as mentioned in #304 but for now this is fine
