### ISSUE TITLE
Complete misc armor sets with missing gear

### ISSUE THREAD

**Issue by Dev-Tyrant** [IronWillGames/Dransik#420]
submitted by fireflylonewolf:
It would be wonderful if the sets could be completed.  The **sand set** is missing the **helmet**.  The **Santa set** is missing the **gloves** and **legs**.  The **spider silk** is missing the **helmet**.  The **serpent set** is missing the **gaunts**.  

(JUST NEED ART FOR THE ONES UNCHECKED)
- [x] HELM: Sand Cloth Hood
- [x] ARMS: Holiday Gloves
- [x] LEGS: Holiday Leggings
- [x] HELM: Spidersilk Hood
- [x] ARMS: Serpent Gaunlets

**Comment by davidjreese** [comment]
I added these to the types

**Comment by PatrickKaHoTang** [comment]
Completed providing stats to these items

**Comment by davidjreese** [comment]
Adding these to drop tables now.

**Comment by davidjreese** [comment]
note, i dont see anything in the game that drops the holiday stuff or lets you get it? @Dev-Tyrant - should this drop from the Christmas area? or part of some scripted gift exchange for item logic?

**Comment by davidjreese** [comment]
This is done!
