### ISSUE TITLE
Unable to claim in token shop

### ISSUE THREAD

**Issue by genkelvor** [IronWillGames/Dransik#429]
When clicking use on berserker potions nothing happens they wouldnt go into my bag and if I get it again I get a message saying "You cannot use that product at this time. please try again in a few minutes." not sure what has caused this I've relogged afew times and still not able to.

This seems to only be happening on one of my accounts but if I switch I can use it.

![image](https://user-images.githubusercontent.com/49921293/209486819-242ff337-efaa-40a6-8e37-d0dda99e04c2.png)

**Comment by davidjreese** [comment]
Is this still happening @genkelvor ?

**Comment by davidjreese** [comment]
Closing this out.  If  you are still having this problem with the new post easter build, let me know.
