### ISSUE TITLE
Quests dont give accurate Exp/epool

### ISSUE THREAD

**Issue by genkelvor** [IronWillGames/Dransik#434]
When completing a quest it will say experience gained in the combat console box that isn't correct to the amount of experience you actually gain compared to exp and epool, I put a before and after picture below.
![image](https://user-images.githubusercontent.com/49921293/209610102-bb308207-546a-44e3-9491-66ab75830111.png)
![image](https://user-images.githubusercontent.com/49921293/209610135-5b5ce871-1d05-4ecb-be3f-3d95696fbce8.png)

**Comment by Dev-Tyrant** [comment]
Potentially the bonus exp from Power Hours being added?

**Comment by davidjreese** [comment]
This is fixed now i believe with new engine
