### ISSUE TITLE
Updated Shop Editor

### ISSUE THREAD

**Issue by Dev-Tyrant** [IronWillGames/Dransik#440]
![image](https://user-images.githubusercontent.com/74842329/209692583-b77c9177-3723-4026-8902-98646f4af78c.png)

Add a section that will be the default shop offering when selling items, so we don't need to go to each shop and set the inventory and quantity.

**Comment by Dev-Tyrant** [comment]
Also.. while you are in the Shop Editor code.. can you blast out the corrupted shop.. i can't delete it

![image](https://user-images.githubusercontent.com/74842329/209693036-f49d5574-4f4c-4117-b4fc-c31a3a6eb9dc.png)

**Comment by davidjreese** [comment]
This is a dupe of the other one which I fixed.
