### ISSUE TITLE
Crafting odd crafting message

### ISSUE THREAD

**Issue by genkelvor** [IronWillGames/Dransik#455]
While I had the dark forging crafting window open I got a message "you begin to forge a Jewel..."

![image](https://user-images.githubusercontent.com/49921293/209729837-8aadf553-38de-4242-b9b4-d6d2a40e3f05.png)

Note: tested this again, this happens when I leave the forging window open for a certain amount of time but after you get the message it will crash you off the server.

**Comment by hgesler** [comment]
Cannot reproduce. Seems to be fixed. If more info/repro available please reopen.
