### ISSUE TITLE
Gnoll Race

### ISSUE THREAD

**Issue by genkelvor** [IronWillGames/Dransik#456]
Details on character creation say that Gnolls get +10 Mining +10 str +10 Large blades and small blades, but its not giving the +10 to mining everything else you get tho.

![image](https://user-images.githubusercontent.com/49921293/209737651-b33c4227-bdaa-4681-ab14-f648ad635382.png)

**Comment by Dev-Tyrant** [comment]
fixed in this bug report: https://github.com/IronWillGames/Dransik/issues/504
