### ISSUE TITLE
Mobs are "dying" and they aren't dropping loot

### ISSUE THREAD

**Issue by Dev-Tyrant** [IronWillGames/Dransik#461]
I am unable to reproduce, but multiple players are reporting

**Comment by davidjreese** [comment]
@Dev-Tyrant you may have fixed this assigning to you

**Comment by Cherrybooze** [comment]
this is most likely triggered by bosses killing themselves with aoe, if monster dies from non player source, it does not drop loot. @Dev-Tyrant

**Comment by davidjreese** [comment]
this is fixed right @Dev-Tyrant
