### ISSUE TITLE
Mouseover Object, should display Object Properties: Name instead of Object Name

### ISSUE THREAD

**Issue by Dev-Tyrant** [IronWillGames/Dransik#464]
![image](https://user-images.githubusercontent.com/74842329/210118544-811f7f19-03a0-47f0-8e3b-7e8eaac5213e.png)

![image](https://user-images.githubusercontent.com/74842329/210118549-0c89d595-019b-47bb-a139-674282bcd12e.png)

**Comment by davidjreese** [comment]
this is fixed now
