### ISSUE TITLE
Changes to the Shop Editor not saving

### ISSUE THREAD

**Issue by Dev-Tyrant** [IronWillGames/Dransik#470]
In the Game Editor, the Shop Editor isn't saving changes.

**Comment by davidjreese** [comment]
@Dev-Tyrant - I thought I fixed this but can't remember. Can you confirm?

**Comment by Dev-Tyrant** [comment]
It is acting funky, if you add items.. and close editor and reopen.. now there are new items that are shifted over to Object List that were set in the 'Object to Buy/Sell'

Also - there is a corrupt SHOP, that is under Wep&Arms

![image](https://user-images.githubusercontent.com/74842329/228710582-030b7680-b7a0-436d-9c22-ae23cd99277c.png)

**Comment by davidjreese** [comment]
Fixed - and fixed some flaws in the way it worked to stop corruption from happening.
