### ISSUE TITLE
When creating new char, racial and profession bonuses appear in skill window with no information

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#49]
Maybe a little confusing as to what they are, esp with the lack of info on create screen regarding their bonuses.

I would say either show that it's a bonus on top of 0 skill, or remove it.

![image](https://user-images.githubusercontent.com/74884462/189367314-aa62ee69-61ba-4857-9a09-bf1d0e6ece5e.png)

**Comment by Dev-Tyrant** [comment]
![image](https://user-images.githubusercontent.com/74842329/205427687-21823b85-2589-4163-8f26-2439a0be1f9e.png)
New UI resolves this issue
