### ISSUE TITLE
Unable to craft Demon Seekers

### ISSUE THREAD

**Issue by Dev-Tyrant** [IronWillGames/Dransik#515]

**Comment by davidjreese** [comment]
I moved this to you for now @hgesler - I know they are craftable b/c people have confirmed it so this may not be a but, but I think its super unclear and complex. Perhaps better recipe books for how to do these things and I can add the book log so people can review recipes as part of the crafting rework

**Comment by Galdelonian** [comment]
Demon Seekers craft at 75 Carpentry from 5 Demon Bones for a "set" of Demon Seekers. You can also craft Demon Shards at 50 Carpentry for 2 Demon Bones. Please don't hold me to those numbers but if you have 100 you'll definitely be able to craft both. I have 100 Carpentry on Atreus.

https://youtu.be/MAuX1KeIDWc

**Comment by davidjreese** [comment]
i refactored all of them

this works and with book system maybe we can put the recipe in a book?
