### ISSUE TITLE
Item drag sprite scale

### ISSUE THREAD

**Issue by Astariz** [IronWillGames/Dransik#522]
The scale of an item changes size when moving them in the game world, bank, and backpack if your scaling is anything but the second notch on the affected window size slider. For example, my backpack/bank sliders are set to 4 and when trying to organize items, the size changes make it difficult to align anything.

1 - Items grow
2 - Items stay the same
3+ - Items shrink

![Screenshot 2023-01-11 094906](https://user-images.githubusercontent.com/80979216/211880498-0b687381-b0f3-4f16-b45f-c76901108a3c.png)

**Comment by hgesler** [comment]
This should be resolved with slots in containers and the new client fixes.
