### ISSUE TITLE
Crafting ban and Macro checks

### ISSUE THREAD

**Issue by genkelvor** [IronWillGames/Dransik#529]
Lower the amount of time you would be on a crafting ban for failing the macro check, 24 in game hours is 1 irl hour which is abit much, I've failed myself trying to and since I'm normally watching someone and just hitting reuse while doing it im not paying attention to the box that pops up and when it pops up the buttons to select the answer are normally in the path of where im mining, lumber jacking or farming so maybe move the the box to pop up some where else?

**Comment by davidjreese** [comment]
Made this not an issue if you have VIP and show the time in minutes. Hopefully, this is good enough

**Comment by ghost** [comment]
macro check cracker is still a thing,
