### ISSUE TITLE
Unresponsive cursor (probably stuck in usecode script somewhere)

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#53]
From codecks: Cursor became unable to interact with anything upon click. Happened after I heal scrolled while targeting a criminal, and possibly pressing f9 screenshot.

**Comment by davidjreese** [comment]
I haven't seen this in ages - need something more specific or perhaps its been fixed.

**Comment by davidjreese** [comment]
closing as fixed - can reopen a new one if needed
