### ISSUE TITLE
Deleting Char and using that char slot  resulted in a bunk player obj?

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#540]
Loaded new client and went to test the char create process; to do so I had to delete one of my 4 test chars. After deleting the top player, I clicked in the blank spot to make a new char. The game immediately loaded with no char create screen and I was stuck with what appeared to be a bunk player object; there was no map drawn, no play area, no chat. Just interface windows open that were blank. Had to force close client. When I relogged I was able to use that slot/create a char successfully.

**Comment by hgesler** [comment]
Unable to reproduce

**Comment by davidjreese** [comment]
Closing as not reproducable - i tried several times
