### ISSUE TITLE
Cooked Snake Meat (Value 729) is an invalid food type.

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#544]
Tried to eat "Cooked Snake Meat." Could not.

![image](https://user-images.githubusercontent.com/74884462/223218926-19d29a13-d711-4d5f-a55b-f8d0747ec70e.png)

**Comment by hgesler** [comment]
Need to add to the block of shared food script (was in two separate scripts, merged types > one, but did not merge in nfoodvalue.

**Comment by davidjreese** [comment]
@hgesler - did you fix this? I think so but didn't want to close it without having you confirm.

**Comment by hgesler** [comment]
Yes it is fixed.Sent from my iPhoneOn Mar 22, 2023, at 11:29 AM, David Reese ***@***.***> wrote:﻿
@hgesler - did you fix this? I think so but didn't want to close it without having you confirm.
