### ISSUE TITLE
Being hit by an invisible npc in Silvest tavern cellar

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#546]
Went to rat cellar in Silvest Tavern and am being attacked by invisible creature. "Mysterious forces leach you..."

![image](https://user-images.githubusercontent.com/74884462/223222748-24ca4e59-fe40-459d-a65c-c899d2c4765a.png)

**Comment by hgesler** [comment]
Next time I went down a rat was there and I was able to kill it.

**Comment by hgesler** [comment]
Had this happen again, while I was in a different part of the cellar, but this time the rat did appear after a few hits. Is it lighting that is not showing the creature or something? It seemed to appear once it got near me, though that didn't happen for the first invis rat.

**Comment by davidjreese** [comment]
Fixed
