### ISSUE TITLE
"Red" gear unequips on login

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#549]
I'm not sure exactly what is happening here and if it's related to these types or all gloves, however, a few times now after a disconnect/crash my red gloves are in the top left slot of backpack when I login, and I know they were equipped when I was disconnected/crashed. It's just that slot.

**Comment by hgesler** [comment]
It seems to be happening when I log out to server select or close client then go back in. If I just log out to char select they are not unequipped.

1. Spawn Red Gloves and equip them.
2. Log out to char select and back in on that char. They should still be equipped.
3. Log out to server select screen and back in on that char. Notice they are unequipped.

**Comment by hgesler** [comment]
Before logout:

![image](https://user-images.githubusercontent.com/74884462/223449706-ed87a29f-69d1-4905-9327-6d7d03983e1f.png)

After logging in:

![image](https://user-images.githubusercontent.com/74884462/223449856-b0c51318-75be-4529-b4b0-abd042d579e0.png)

**Comment by hgesler** [comment]
It is also pushing whatever is in slot 1 to the end when it is forced into that slot.

**Comment by hgesler** [comment]
This is not happening on my GM char with red gloves equipped.

**Comment by hgesler** [comment]
This is happening with all red armor items: Red Hat, Red Tunic, Red Trousers, Red Gloves. Not happening with Red Lantern.

**Comment by davidjreese** [comment]
fixed!
