### ISSUE TITLE
Dragging last log of a stack while milling it resulted in a visual artifact left behind in that slot

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#551]
I used my saw on 1 log in my backpack. During the sawing process I accidentally drug the log with my mouse left click, then after sawing was complete the "ghost" log was left in that slot. Things draw underneath it, it has no tooltip as shown in ss.

![image](https://user-images.githubusercontent.com/74884462/223468238-f06e4de4-3c39-4927-b65b-0469d2cf2964.png)

![image](https://user-images.githubusercontent.com/74884462/223468321-3b129bee-bc65-4623-be20-eaafb841db87.png)

**Comment by davidjreese** [comment]
Happens on live too. Removing the Phase 2 label, but will keep in the list to fix.

**Comment by davidjreese** [comment]
fixed
