### ISSUE TITLE
Dragging item on ground sometimes results in invisible item

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#552]
Working on repro case for this. Happens when dragging things and some latency perhaps. A draw issue only.

A few times now I've had a bat wing etc on the ground that I moved and something went awry with the left click move; the item is on the ground with a counter/quant on it, but it is invisible. I can tooltip over it. See image below. Possibly related to #551 

![image](https://user-images.githubusercontent.com/74884462/223494519-a31b260b-3095-40da-af82-ca0edd24fe3e.png)
![image](https://user-images.githubusercontent.com/74884462/223495048-6725a2d4-ebec-46b8-a2ad-6d75119db5c7.png)

**Comment by davidjreese** [comment]
Think I got this. Let me know if you see it anymore
