### ISSUE TITLE
Have a blank slot in backpack that can't be filled with any object

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#553]
![image](https://user-images.githubusercontent.com/74884462/223504342-8168fe74-da2a-482c-8143-392bc12326c6.png)
Not sure how this happened. I cannot put anything there or see anything in that slot.

**Comment by davidjreese** [comment]
Can you use a GM tool on it to get a type id?

**Comment by hgesler** [comment]
This is in my player char backpack - if you want to look on your GM lmk I can log.

**Comment by davidjreese** [comment]
Heidi, closing this one - reopen it if it keeps happening. I think this was fixed with some of the quantity and type stuff that was broken in earlier build.
