### ISSUE TITLE
Silvest Monster Drops (Trade skills)

### ISSUE THREAD

**Issue by genkelvor** [IronWillGames/Dransik#561]
on silvest for trade skills starting out, how about we renamed goblin pirates to Goblin Miners (or just create a new miner newb monster)  have them have a chance to drop ore and kobolds can drop cotton, fighters/thiefs can drop logs that way we can cover hunting and crafting in one thing for players, and maybe incorporate it into the trade skill quests to go kill them for missing trade skill supplies or something. this would promote the new directions we are going with trade skills

**Comment by davidjreese** [comment]
What do you think of this suggestion? Moving to  in-progress so we can decide to (or not to) do it as part of the crafting upgrade system?

**Comment by hgesler** [comment]
I think I’m some cases it’s fine but can’t be only or best source for materials. Probably best to approach with a mix - gives crafters incentive to hunt and hunters something to offer crafters.Sent from my iPhoneOn Feb 23, 2024, at 9:36 AM, David Reese ***@***.***> wrote:﻿
What do you think of this suggestion? Moving to  in-progress so we can decide to (or not to) do it as part of the crafting upgrade system?

**Comment by davidjreese** [comment]
I think with the changes with resource generators, skill system, and crafting enhancements along with new player training this is pretty good now. much better than it was before. alchemy and those changes scratches the itch of collecting things you can use
