### ISSUE TITLE
NK Provisioner shop

### ISSUE THREAD

**Issue by genkelvor** [IronWillGames/Dransik#562]
Add Carpentry sign outside of provisioner shop now that they both are in one building.
![image](https://user-images.githubusercontent.com/49921293/229324012-47df624a-eea1-48c2-ac20-89a50fb65932.png)

maybe have it look something like this
![image](https://user-images.githubusercontent.com/49921293/229324054-c1995b23-c53b-43d1-8948-570d9bb62800.png)

**Comment by Dev-Tyrant** [comment]
Updated
