### ISSUE TITLE
Item Identification quest wording issue

### ISSUE THREAD

**Issue by genkelvor** [IronWillGames/Dransik#565]
Starting the Item identification quest from Tallen'im west of NK along the shore line at the start of the quest once of the responses to the NPC is "Ol man, what troubles you the find day?" I believe that should be "Fine day"

![image](https://user-images.githubusercontent.com/49921293/229356103-75b6ef15-9acc-4f15-b661-828372b9c5cd.png)

**Comment by Dev-Tyrant** [comment]
adjusted
