### ISSUE TITLE
Dragging item to container header results in visual artifact/shadowed item in origin container

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#567]
1. Drag any item from any container to any other container by dropping it on the container's header/title bar.
2. Notice that the item is not placed in the container, nor is it returned to origin container (as it does when any item is dragged to every other window like map, player screen, skill window)
3. You must then click drag the item again in the origin container to make it draw correctly.

![image](https://user-images.githubusercontent.com/74884462/230902959-f087e10f-9835-4443-bb30-c07ef2b76218.png)
![image](https://user-images.githubusercontent.com/74884462/230902988-a6335851-5080-4d0f-9296-457dfb08ee79.png)

**Comment by davidjreese** [comment]
Fixed
