### ISSUE TITLE
Can add items to a placed world container obj to go past 20 items, but cannot retriever them once it reaches or exceeds 20 items

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#568]
1. Log in as a player
2. Find a world object (I used a dresser at 652,243,0).
3. Fill the object with items. I used blue stone daggers. Notice at 19 items you can still take things out of the object.
4. Once the object is holding 20 items, notice that you cannot take anything out of the object; message "Container is full" is printed to chat, however, you can still add to the container.

I'd expect containers to show the number of slots available and that you'd be able to remove things once the max # is reached.

**Comment by hgesler** [comment]
As a GM I can remove items that meet/exceed 20 limit

**Comment by hgesler** [comment]
Somehow this number 20 keeps changing and seems to be related to other players or objects. Not sure. After this test I was stuck at 16 objects, then 8. Was not able to pin down what is happening.

**Comment by davidjreese** [comment]
I cannot reproduce this issue. I tried the dresser and a barrel. 64 is the actual limit. Anything else you can come up with that would be the key to understanding it?

**Comment by davidjreese** [comment]
could it possibly be something to do with the dresser having a weird mass/capacity thing we dont know about?

**Comment by hgesler** [comment]
Not able to reproduce this. However, able to add to containers past 64 items: #574
