### ISSUE TITLE
Able to drag item to backpack from world and have 65 in inventory without VIP/Mega BP

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#569]
Remove VIP and megabackpack from store
Notice that when you reach 64 items, you can still click drag an item to your backpack to bring you to 65 items total.
Upon dragging item #66 to your backpack, notice that you get the warning message about container size/purchasing VIP megabackpack.

![image](https://user-images.githubusercontent.com/74884462/230906109-8c829b82-fbf6-499f-bb2a-a8c41c5253b9.png)

**Comment by hgesler** [comment]
Also able to Buy an item when at 64 items to reach 65 items; then after that the proper message appears that you must buy vip/mega bp.

**Comment by davidjreese** [comment]
1. Updating this to say please purchase VIP for the first 64. 
2. Shortened the messages to make the a bit easier to parse.
3. Corrected the logic to stop at 64 for shops and dragging.
