### ISSUE TITLE
Cant sell normal magic shield anywhere.

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#57]
From codecks: Cant sell normal magic shield anywhere.

**Comment by hgesler** [comment]
Still an issue. Probably not added to NPCs buyback table?

Magic Platemail, same issue.

**Comment by hgesler** [comment]
Neither are in the buyback menu.

**Comment by Dev-Tyrant** [comment]
Blocked, Shop Editor not working
It isn't saving any adjustments to the shop

**Comment by Dev-Tyrant** [comment]
@davidjreese If you can look at the Shop Editor to allow me to update the list of items the shop can buy. 
Currently, when I try to add more to the list, it appears not to be saving the change. 

![image](https://user-images.githubusercontent.com/74842329/211086298-2e7ab6c7-e1a0-4bd4-b62f-b98fac501813.png)

==================

Also there is a corrupt entry in the Shop List.. if you select it, it will test the Editor:
![image](https://user-images.githubusercontent.com/74842329/211086418-67c7eed2-7321-4bd0-8aab-5b5312d87627.png)

**Comment by davidjreese** [comment]
@Dev-Tyrant think you are good to go to fix this now

**Comment by Dev-Tyrant** [comment]
I still can't update the Armoury Shop to Sell/Buy Magic Platemail and Magic Shield

**Comment by Dev-Tyrant** [comment]
@davidjreese Any chance you can debug?

**Comment by davidjreese** [comment]
okay, i will look at that.

**Comment by davidjreese** [comment]
When editor deploys, you can now do this... wow what a bug.

**Comment by davidjreese** [comment]
You fixed this right @Dev-Tyrant ?

**Comment by Dev-Tyrant** [comment]
fixed now
