### ISSUE TITLE
Crafting allows you to exceed maximum inventory

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#570]
Testing VIP/Megabackpack limits

1. Fill player char's containers with max number of objects, including a stack of "Plank" and "Carpenters Tools"
2. Use the tools on the plank to create a club. At this point I'd expect a warning message about capacity.
3. Notice that when you succeed the item is placed in backpack and allows you to exceed the limit of items.

**Comment by hgesler** [comment]
Use CanHold to determine prior to craft and if can't craft, fail before crafting/do not consume, or destroy the output.

**Comment by davidjreese** [comment]
The design will have to deal with this one... do a CanHold check and if it returns false dont allow the crafting.. It's not pretty as it can probably be held in some edge cases but will cover the 90% calse and prevent over stuffing

**Comment by Dev-Tyrant** [comment]
Updated Crafting with CanHold checks
