### ISSUE TITLE
Able to trade past max inventory limit

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#571]
1. Log in with a character who has no VIP/megabackpack
2. Leave space in backpack but fill bank and backpack so that you are at maximum inventory (64)
3. Enter trade with another player.
4. Notice other player can send items to you and complete a trade, though you are not able to trade to them.

**Comment by davidjreese** [comment]
Requiring that you have up to 16 open slots to go into a trade. This seems reasonable since backpack can hold 64 items to me. This way you should be able to hold everything being traded.

**Comment by davidjreese** [comment]
1. fixed this and it tells you that VIP or Mega would help based on what you have
2. Also requires at least 16 open slots in your main backpack
