### ISSUE TITLE
Mega Backpack Icon is greyed out even when you have purchased it

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#572]
After purchasing Mega Backpack, the icon should appear colored in (as does VIP when it is active/purchased subscription). Currently it is always grey and difficult to tell if you have it or not.

**Comment by davidjreese** [comment]
Fixed - This worked for me. There was a bug not letting me buy the MegaBP in the in game store but once I fixed that and the purchase went through, it worked fine.
