### ISSUE TITLE
Able to stuff more than 64 items in a world container (barrel)

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#574]
1. Go to a barrel (I used barrel in Jeel at 264,885,0).
2. Fill the barrel with items. I assumed the container's max inventory was 64 items. I was able to continue to add items past 64. Did not test upper limit of this.

![image](https://user-images.githubusercontent.com/74884462/231621089-8ee2cc4d-41f4-46c1-a051-afa90fd819e4.png)

**Comment by davidjreese** [comment]
fixed
