### ISSUE TITLE
Would like to be able to see my player's current Race and racial bonuses

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#575]
To my knowledge there is not a way currently to check your current Race or racial bonuses while logged in on that player.

It would be nice to be able to tooltip over player avatar or have it printed in level area or somewhere of player screen. While transformed in an avatar, can't tell what you are. Don't remember your bonuses unless you go out, make a new char, or something like that.

**Comment by hgesler** [comment]
Still an issue unless I'm being very dense. Also, bonus to orbs is not shown either.

![image](https://github.com/IronWillGames/Dransik/assets/74884462/2d8d03a0-3e59-4fe4-bfc0-9f53e4a2ae69)

A tooltip over player could show the race and racial bonuses.

**Comment by davidjreese** [comment]
done
