### ISSUE TITLE
Dragging an item to a similar stack in a full inventory backpack results in max inventory message

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#576]
1. Fill backpack+bank to almost max inventory (tested with 499 items on a VIP + mega BP player char)
2. Place two stacks of the same collectable item on the ground (something you do not already have; I tested with apples but you could use apple seeds, etc)
3. Drag one stack into backpack to make 500 (max) items in inventory.
4. Drag the remaining stack onto that stack; notice you get a failure message about being full. I'd expect it to stack if it can.

I had to pull a stack out of a full backpack, combine it on the ground, then drag into backpack to get around this.

**Comment by davidjreese** [comment]
fixed
