### ISSUE TITLE
Crafting check needs to be reword so people dont craft if they cant hold

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#581]
Made some armor but then couldn't hold it so got destroyed.

https://discord.com/channels/695812967463256084/724274768169140224/1096627617198772306

**Comment by hgesler** [comment]
Not able to address this with current canhold logic. The trades that will need addressed specifically are those using trade/crafting menu (forging, carpentry). Those after CreateTradeObject call.

**Comment by davidjreese** [comment]
I updated all the CreateTradeObject stuff now using the right pattern in usecode.

@Dev-Tyrant / @hgesler  -> would you please do some double checking to make sure they work. One that was really crazy was tinering. The original usecode used the **Tinker Menu** but then used Create object off the **Carpentry menu** and its object selection was weird.

**Comment by hgesler** [comment]
Fixed up a few other places that don't use createtradeobject and tested all crafting at max inventory. Should be good to go.
