### ISSUE TITLE
Hailstrom Feedback (Weapon rebalancing)

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#583]
is it possible you guys forget to adjust hailstorm? lvl 85 needed with same damage as before. but angel bow is stronger now en need lvl 80 ^^ or is hailstorm just not supposed to be the strongest bow anymore?

https://discord.com/channels/695812967463256084/704769329744445502/1096688622549344367

**Comment by Dev-Tyrant** [comment]
As designed.
