### ISSUE TITLE
Forging low level stuff does not give the item

### ISSUE THREAD

**Issue by Jabelius** [IronWillGames/Dransik#589]
If you try to forge a "Battle Axe" or something else that requires only one iron bar it will never finish. 

"You begin to forge a Battle Axe..."

Nothing else happens. Ingot is lost tho. No item rewarded.

Edit: There should be message if it failed imo. After few tries it managed to forge axe successfully.

**Comment by hgesler** [comment]
Unsure if related; ticket open about forging with ice crystals:

"It said I made it but I did not get the Frost Plate.  It did however remove all 68 crystals from my backpack."

**Comment by davidjreese** [comment]
@Dev-Tyrant another one? close if you think its done for now

**Comment by davidjreese** [comment]
this is ancient - closing it out.
