### ISSUE TITLE
My forging in skills is vanishes

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#601]
Two people reported this - it comes back when you forge but weird that it vanishes....

Vanishes on each relog for some reason

https://discord.com/channels/695812967463256084/724274768169140224/1096863717838299277

**Comment by davidjreese** [comment]
Holy crap this was hard to figure out. Found, fixed and optimized some things on the server so it wont be as dumb about skill change messages to client.

**Comment by ghost** [comment]
this happens with cooking and other skills too, just a heads up
