### ISSUE TITLE
Players underground will shadow above

### ISSUE THREAD

**Issue by genkelvor** [IronWillGames/Dransik#606]
When a player goes underground, it will shadow them above ground making it so players can see whoever is underground but the people underground cant see the people above them.

I noticed this happen at the guild quest start area when a player went down the ladder into the cave I saw the player walking around and thru walls above ground.

Also it only shows them as long as the ladder destination is right below where they went down and you stay on screen with their shadow, if they leave your screen you wont see them anymore

**Comment by davidjreese** [comment]
Hah, nice one - fixed
