### ISSUE TITLE
Clicking certain elements windows will not pop window to front

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#621]
This is my OCD but I'm posting it here anyways!!

I like for the UI elements that I'm interacting with to be on top. I've noticed that a few elements of various windows did not let those windows pop to front when I clicked on them. 

Here are the times it did not work as expected...

In Backpack, if you click
- a yellow grid element (hard to do but I do more than I thought in normal use, which is how I went down this rabbit hole in the first place)
- the black bar that holds the inventory limits at top of window
- any item

In Skill window, if you click
- one of the tabs to sort the window
- the + or - buttons to expand/collapse nested skills etc

Any Chat Console, if you click
- Scroll bar
- Configure button

Map
- Clicking the filter button
- Clicking the scale up/down slider

Play Area
- Clicking scale up/down slider

Store
- Clicking filter tabs
- Clicking Use/Details/Buy buttons

**Comment by davidjreese** [comment]
Fixed - should work for most everything now
