### ISSUE TITLE
VIP Macro Check still happening?

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#631]
Check code, GM triggered is the only way I am aware this should happen right now. Otherwise bug

**Comment by hgesler** [comment]
Player Session Stream on Atreus reported it happening with woodworking (either lumberjack axe or carpenters tools).

There are definitely still macro checks in script; I assumed it was removed some other way perhaps, looks like those checks need to check for VIP flag.

**Comment by davidjreese** [comment]
Believe we have this fixed in new code

**Comment by ghost** [comment]
My macro cracker code still works lol...
