### ISSUE TITLE
Crasher - update is being modified while its being iterated over

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#637]
Happend 3 times now and it's always GOLD in the world at an X/Y.

My guess is creeper on CPP side? or player scooping it up / draging it... not sure.

![image](https://user-images.githubusercontent.com/669018/233650092-38e426e5-10f8-4565-923d-3603ec65ea4c.png)

**Comment by davidjreese** [comment]
I think I fixed this by simplifying the pause lock across the 2 threads. there was a very very remote possibility that something could happen based on timing and thread priortization (or so I think) that could allow both to run at same time when they were in syncrhonous mode.

**Comment by ghost** [comment]
that gold pile was up near gm island? thats the creeper count gold,
