### ISSUE TITLE
Update text on Vels vs mainlands when you bind

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#638]
i think that text shouldnt be there anymore now is it? Since we can freely move between vels and main

not relevant anymore I don't think

![image](https://user-images.githubusercontent.com/669018/233669540-4572f84d-a89f-466f-bb19-e19e8577afb7.png)

**Comment by Dev-Tyrant** [comment]
Commented out the print statements, but keeping the rest of the code to clean up flags

**Comment by ghost** [comment]
this was added cause of abuse, i actually added that code to get rid of silvesting ports and interland ports
