### ISSUE TITLE
Weird Animation - Blue Stone Dagger

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#639]
Blue Stone Dagger has some weird animation thing going on when being sold to shop/or being sold in shop. Cycles between Blue Stone Dagger, Triddle Spine and Kurian Dagger.

**Comment by Dev-Tyrant** [comment]
Not sure if it will help, but I re set the art tile in the editor to see if that resolves it.

**Comment by davidjreese** [comment]
Looks like you fixed this
