### ISSUE TITLE
Alignment ranges is confusing on equip requirements

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#649]
Good range can make it so it looks like you are able to wear something but you could not be good enough...

**Comment by davidjreese** [comment]
@GMRuizerion do you know if this is still an issue?

**Comment by GMRuizerion** [comment]
> @GMRuizerion do you know if this is still an issue?

Considering item stats, requirements to equip weapons etc were changed or removed I'd say fine where it's at. Can revisit if players have issues down the line. Maybe item tool tip displaying exact alignment required. Example Holy plate requires Good or higher. Not really needed though

**Comment by davidjreese** [comment]
closing this out then. thanks
