### ISSUE TITLE
Feeding other players beef pie results in bad stamina message, stamina gain above 100 cap

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#654]
I think feeding other players does need to be removed but evidently your stamina can get bugged feeding others a beef pie.
- stamina print is bad (shows negative number)
- player said they were able to go above 116 stamina

Not sure of repro steps yet, if it is just issue with beef pie, or what. I don't think that the player can go under, though perhaps they are going past 100.
https://discord.com/channels/695812967463256084/724274768169140224/1100592115454578759

**Comment by davidjreese** [comment]
I fixed this when I reworked food for autoconsumption and cleaned the f out of the script... was not written cleanly
