### ISSUE TITLE
Arrows/Bolts are unequipped on login, go to backpack

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#66]
From codecks: _Fix Arrows and bolts go to back backpack aswell when u log back online_

**Comment by hgesler** [comment]
Still happening

**Comment by davidjreese** [comment]
This doesnt seem to happen to me? does it happen to you still?

**Comment by hgesler** [comment]
Appears to be fixed. tested with pebbles, backed out to char select and back in, server select and back in, and exited client/back in.
