### ISSUE TITLE
Playerfloater and map tags config issue

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#674]
[PlayerFloater]  visible=true breaks it. (you can test this with the "lock" toggle next to hp in the player window.. with that toggled one way the map markers dont work, toggled the other way they do work

so it relates to this aswell: (which I also have)
Toggle for Health Floater doesn't work for me, been unable to remove it for a few days now.

**Comment by hgesler** [comment]
Confirmed that this is still an issue. If you have player HP floater visible you cannot make map markers.

**Comment by davidjreese** [comment]
Fixed
