### ISSUE TITLE
Racial bonuses to skills do not seem to be working properly - review

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#68]
From Discord:
jakari: _does Brimlock racial bonus work correctly? or is the forging bonus  only for iron? because tundrite dosen't seem to get to bonus._

Sesi: _100 (20) mining skills gives 13 ores, same amount as 100 without bonus
Smelting is same as well, didn't notice any chance on success rate while smelting
And didn't even get increased exp between brimlock boost / no boost_

pureluck: _forging has the same issue with the racial bonus_

**Comment by AESeryth** [comment]
Smelting and forging seem to have no effect while mining seems like it affects the success chance but not the number of ores.

**Comment by davidjreese** [comment]
Fixed in latest build
