### ISSUE TITLE
Terry in Jeel

### ISSUE THREAD

**Issue by Fluffp** [IronWillGames/Dransik#682]
![image](https://github.com/IronWillGames/Dransik/assets/133507757/6afa23f7-97b5-413f-97e4-99ccfd7c07bb)

Not sure why this quest got completed.
i never picked it up and i havent been in the catacombs

**Comment by hgesler** [comment]
Did you do Gratic's quest? It looks like doing that quest sets you on this one by accident due to copy/paste issue.

**Comment by hgesler** [comment]
Fixed incorrect stage ref in Gratic's quest which put player on Terry's quest.
