### ISSUE TITLE
Guild Quest - Book Three: Doesn't give any experience.

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#685]
As stated.

It looks like the only person who is given experience is the one reading the book/completing the quest. It is not given to everyone who helped. Need to confirm if that is happening.

**Comment by ghost** [comment]
this is cause it was in a silvest safe zone and wouldnt let people drop inventory, but as they where over sivest epool cap it wouldnt give anymore, and was never changed from the safezone as people would drop inventorys in the quest

**Comment by davidjreese** [comment]
fixed all this
