### ISSUE TITLE
Line break needed after failure message when attempting to purchase from shop without enough gold

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#688]
Try to purchase something without required gold.
Server informs you with error message in chat console that you don't have enough gold "Not enough gold."
That text needs a line break after it. If you do anything else (like purchase again, or speak to quest npc) the next line of text is stuck right next to it.

![image](https://github.com/IronWillGames/Dransik/assets/74884462/fa7d52e9-6845-4cf9-af74-ced9b458177e)

**Comment by hgesler** [comment]
Line breaks needed after Spire Spawned message as well:
![image](https://github.com/IronWillGames/Dransik/assets/74884462/f470fd24-0fad-4a52-950c-d099c99f505a)

**Comment by davidjreese** [comment]
I fixed this
