### ISSUE TITLE
Area of Effect procs not working on weapons that have it

### ISSUE THREAD

**Issue by PatrickKaHoTang** [IronWillGames/Dransik#695]
Rune Dagger, Rune Staff, and most likely the others (Tooth Staff, Bone Staff, Lich Staff, Staff of Impartiality, Staff of Nycadaemon) are missing their AoE specials

**Comment by jasonmcleod** [comment]
I can confirm this is still an issue with the Tooth Staff. Here are a few more notes:
- When I target something the outline goes away in about 1 second after hitting (I guess it's hitting?)
- No damage will ever be dealt if fighting 1 just target
- Damage will be dealt when there are at least 2 adjacent targets
**- No XP is given for any damage**

**Comment by davidjreese** [comment]
Function was no longer named properly. Made it work with new native engine
