### ISSUE TITLE
Unable to walk onto ladders to exit area

### ISSUE THREAD

**Issue by PatrickKaHoTang** [IronWillGames/Dransik#696]
Happens at the following coordinates:

- 2697,2249,1
- 2760,2249,1
- 2758,2188,1
- 2758,2178,1
- 2758,2150,1
- 2677,2166,1
- 2735,2203,1
- 3032,1360,1
- 3450,3038,1
- 3507,3027,1
- 932,552,1
- 820,1042,1
- 828,114,1
- 3863,2532,1
- 436,852,1
- 293,833,1
- 460,754,1
- 506,675,1
- 520,840,1
- 695,1002,1
- 696,1002,1
- 695,943,1
- 696,943,1
- 693,930,1
- 698,930,1
- 713,962,1
- 707,959,1
- 707,962,1
- 710,964,1
- 713,970,1
- 693,913,1
- 698,913,1
- 695,906,1
- 696,906,1
- 695,878,1
- 696,878,1
- 695,1112,1
- 633,1261,1
- 520,1064,1
- 905,1029,1

**Comment by davidjreese** [comment]
fixed - ladder up (114) was marked as solid
