### ISSUE TITLE
"Leaving Prison Zone" issue

### ISSUE THREAD

**Issue by PatrickKaHoTang** [IronWillGames/Dransik#697]
![Prison Zone](https://github.com/IronWillGames/Dransik/assets/30209039/efc368ef-9dc0-4fc2-b0d7-8765eeaa187d)
At around the 696,879,1 coordinates, you leave the "Prison Zone" area where you can do everything normally - dropping items, possibly go criminal, etc.

**Comment by davidjreese** [comment]
wow - crazy, no telling how long that bug was there ... probably forever
