### ISSUE TITLE
Unable to reopen Chat Console if you close it

### ISSUE THREAD

**Issue by PatrickKaHoTang** [IronWillGames/Dransik#699]
When you close the Chat Console, there's no way to re-enable it in game again, Only way to fix it out of game is to configure the charactername.cfg or deleting it.

Perhaps remove the option to be able to close it?

**Comment by hgesler** [comment]
Under [ConsoleChat] section set visible=true

**Comment by davidjreese** [comment]
closing - it's in the options if it ever gets closed
