### ISSUE TITLE
Broken Ladder at 247,1638,1

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#7]
Should lead to 173,1490,0

**Comment by hgesler** [comment]
Related to the script used to make sure that players weren't getting blocked while using linked ladders. This is the same issue preventing the ladder to BK castle/toxicum being used. One is a Ladder Down which always works, the other is Tele Ladder Exit which uses that blocking script to make sure players can't get walled in by enemies, etc.

**Comment by hgesler** [comment]
@AESeryth please check this out, it should be working now
