### ISSUE TITLE
Demon Seekers not craftable

### ISSUE THREAD

**Issue by Dev-Tyrant** [IronWillGames/Dransik#70]
![image](https://user-images.githubusercontent.com/74842329/190290979-08df86f4-2f11-4d19-9334-e1158a6eac7c.png)

**Comment by hgesler** [comment]
Check to see if it is working properly with base 75 carpentry

**Comment by hgesler** [comment]
Should be:

Shards - 2 demon bones, 50 carp skill
Seekers - 5 demon bones, 70 carp skill

**Comment by Dev-Tyrant** [comment]
fixed usecode
