### ISSUE TITLE
Demon Spire needs a table of coords to spawn into rather than random spawn

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#702]
Spawning into unreachable locations too often.

Can reuse AE's treasure map scripts to teleport it to a predefined x y table of ~100 locations.

Would need that list of locations.

**Comment by davidjreese** [comment]
@GMRuizerion - if you want to add 100 or so locations for the spire here, x,y,map I will use them when I fix this

**Comment by davidjreese** [comment]
I picked some locations. a couple of hundred
