### ISSUE TITLE
Resource and Tradeskill improvements

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#706]
- [x] Resources: Mining gives the most resources compared to Lumberjacking as I got 150+ Iron Ore vs 25 Logs in the same amount of time spent
- [x] Tradeskill Exp: Non Mining, Smelting, Blacksmithing tradeskills doesn't give enough exp
- [x] Roasting, Eating Food, Bandaging, etc: Display a line of text for where you want to start roasting/eating something. ie. Mining Pick text, "Where would you like to mine?"

**Comment by hgesler** [comment]
Took a swipe at the lumberjacking issue but it's not doing as well as I thought it would.

**Comment by davidjreese** [comment]
@Dev-Tyrant another one. close if you think this is done (for now)

**Comment by davidjreese** [comment]
Closing this out assuming its done @Dev-Tyrant until next phase of tradeskill
