### ISSUE TITLE
Show Quest Completion in Text Also

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#707]
(-) Quests: Show completion in text also

Pat recommended this get more info

**Comment by hgesler** [comment]
So old system used Print <player> to give updates; this is still used in kill counts to give updates on those types of quests. In AE we also print queststagedata calls to chat automatically, and I don't see that happening in DC.

**Comment by davidjreese** [comment]
i added a method on player generic (and called it from all the silvest quests) that prints out "Item received: " consistently. 

for completion, isn't this just making sure to add it to the usecode? we been doing that as we go. i don't think anything additional is need here.
