### ISSUE TITLE
Macro Check ban in DC is 24 hours? Geeeeez

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#71]
Probably need to really turn this down or consider removing it; just like AE. It only hurts people who aren't macroers.

**Comment by hgesler** [comment]
Maybe in game time not 24 hours of real time

**Comment by Jabelius** [comment]
+1

**Comment by davidjreese** [comment]
Removed macro check for VIP and showed time left in minutes. Its all usecode on player-generic
