### ISSUE TITLE
Banished Knights get stuck behind the moat at BK castle 

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#73]
There's no way for them to leave the ring around the castle at 219,1804,0

**Comment by AESeryth** [comment]
The entire inside of the castle seems to be impassable terrain so monsters are only spawning in the ring.

**Comment by hgesler** [comment]
The terrain is bad for some reason. Not sure if it's how it's set up or what. Going to repaint with tiles that do work until I figure out what's wrong with that tileset.

**Comment by hgesler** [comment]
Had to use a different tileset. Creatures now spawning there. The issue of getting there is a different problem.
