### ISSUE TITLE
Monsters/bosses hitting too often

### ISSUE THREAD

**Issue by PatrickKaHoTang** [IronWillGames/Dransik#736]
Tested out hunting at Tower as it was the final place to be added into the game. Was easy prior to update but is near impossible to hunt regardless of spec post update. If this is happening in Tower, it will happen in other areas too...

Initial findings in the overall sense are:

- Monsters are hitting too often even with high armour count to mitigate incoming damage (had 384)
- Area(s) was somewhat manageable from +TO HIT from resistance gear and berserker potion. No berserker active...no chance. Issue may be related to point above
- Damage output from monsters is too high for a very condensed area (specific to Tower, doesn't help when there's 3 elemental types and a non-elemental monster in there). Need to look at other areas such as Water Castle, BK Castle, etc. Also will need to look into longer respawn timers or reducing the amount that spawn in there. Can't image what it would be like if there was a spawn increase
- Bosses are too fast as they're at Balron speed. Reducing run speed slightly may make it more manageable

**Comment by PatrickKaHoTang** [comment]
Total hits in all 4 of these tests are not the same total, but it is to test between the 2 types of characters - pre-update and post-update. Will need more information on if there is a scaling for lower vs higher level characters, low vs higher armour counts, etc.

**Data from Triddle using pre-update character**

Level: 100
Base Stats: 100 Str / 100 Dex / 5 Int / 20 Con
Armour Count: 380
Equipment: BK Helmet, BK Plate, Rune Leggings, Etherial Shield, Nimble Shooting Gloves)

Missed Hits: 524
Hits Landed: 361
Total Hits: 885
Miss Chance: 59.20%

Level: 100
Base Stats: 100 Str / 100 Dex / 5 Int / 20 Con
Armour Count: 50
Equipment: None, armour count from dex

Missed Hits: 0
Hits Landed: 465
Total Hits: 465
Miss Chance: 0.00%

**Data from Triddle using post-update character**

Level: 1
Base Stats: 12 Str, 5 Dex, 5 Int, 5 Con
Armour Count: 17
Equipment: Leather Cap, Leather Gloves, Leather Armour, Leather Leggings, Small Shield

Missed Hits: 652
Hits Landed: 538
Total Hits: 1190
Miss Chance: 54.78%

Level: 1
Base Stats: 12 Str, 5 Dex, 5 Int, 5 Con
Armour Count: 2
Equipment: None, armour count from dex

Missed Hits: 229
Hits Landed: 284
Total Hits: 513
Miss Chance: 44.639%

**Comment by PatrickKaHoTang** [comment]
**Data from Triddle using pre-update character, level 16**

Level: 16
Base Stats: 42 Str / 5 Dex / 5 Int / 5 Con
Armour Count: 59
Equipment: Chainmail Coif, Golden Chainmail Gloves, Thepa Shield, Padded Leggings, Magic Padded Armour, +1 Sword (Some items provide additional dex to give armour count)

Missed Hits: 348
Hits Landed: 310
Total Hits: 658
Miss Chance: 55.88%

Level: 16
Base Stats: 42 Str / 5 Dex / 5 Int / 5 Con
Armour Count: 3
Equipment: +1 Sword, weapon's +1 dex = +1 armour

Missed Hits: 236
Hits Landed: 467
Total Hits: 703
Miss Chance: 33.57%

**Comment by davidjreese** [comment]
Found the AC issue
