### ISSUE TITLE
Potion shop at NPB stops working

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#74]
Trying to buy a stack of more than one Greater Healing Potion from the shop gives the error message, "One of your items is not available anymore from the store."  Single pots at a time works and so do all the other items.

This happens after the server's been up for a while.  Only affecting Atreus so far.

![image](https://user-images.githubusercontent.com/112813257/190955287-94d929fa-741c-449d-8e88-5c984473739a.png)

**Comment by AESeryth** [comment]
I sold a few stacks of potions to the NPC and now I can buy from him again. I sold 103 GHPs and was able to buy 600 right afterwards.

Seems to be a decently simple workaround.

**Comment by AESeryth** [comment]
So I can fix this issue in-game but don't know exactly how to reproduce it. It seems to happen with popular items at popular shops eventually whenever the server is up for a long time.  Maybe either a limited stock (65k or w/e) or a low low chance random thing. 

To fix it you can just sell more than 50 of the item back to the shop. After that you can buy as many as you want again.

**Comment by davidjreese** [comment]
I can't reproduce this. I am wondering if this is an old bug that has long since been fixed.
