### ISSUE TITLE
Unable to attack with range in underground Parian

### ISSUE THREAD

**Issue by PatrickKaHoTang** [IronWillGames/Dransik#749]
You can target monsters and attack normally with melee, but with range, it does not attack. It recognizes that the shot is being blocked though if you're side by side to a monster.

**Comment by davidjreese** [comment]
Fixed lots of mismarked tiles here. Seems to have been confusion

Tiles were marked Terrain, Building Terrain or both and also Walk Type FLAT. Should only use Terrain / WT_FLAT combo on walkable types with the exception being if you wan the tile to block arrows (like a tree or shrub), then use TerrainBuilding also
