### ISSUE TITLE
You have mined 0 Thrallenite

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#753]
Possible to get 0 ore while mining. Easy to reproduce.

**Comment by davidjreese** [comment]
This seemed concerning. nothing obviously wrong with the script. it was 0 initially, then started working so I couldn't debug it any further as to why it wasn't. i did change the script to get rid of the use of the variable that seemed to be broken.

going to test in stage again but I think its fixed

**Comment by davidjreese** [comment]
Confirmed in stage
