### ISSUE TITLE
Not getting boosted skill exp from power hour

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#765]
maybe checkout what happens to main too.

**Comment by PatrickKaHoTang** [comment]
Regardless of VIP, PPH or PH exp gain boosts, any skill damage while leveling up gains 1:1 exp when it should be boosted. Overall exp does gain boosted exp.

**Comment by davidjreese** [comment]
This one has been fixed for sure. Just a client visual error
