### ISSUE TITLE
Goblins in corner of Silvest cave don't count towards the kill quest for Guard Murphy

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#78]
Assuming this is the Guard Murphy quest they should count towards. Probably just need to expand the x/y range check in player generic

**Comment by hgesler** [comment]
It is checking if it is in newbie land, I'm assuming there's a few squares of that cave not zones properly.

**Comment by hgesler** [comment]
Zoning feature seems broken in this editor build so will have to check this out later.

**Comment by davidjreese** [comment]
Is there a ticket for the zoning editor bug? I am looking at that tnow

**Comment by hgesler** [comment]
Zoning issue is resolved.

The Goblin cave has been corrected with the appropriate flag.
