### ISSUE TITLE
Stuck in GM Lunchroom from portal in desert

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#8]
Stuck in GM lunchroom after entering portal in desert

Portal
![image](https://user-images.githubusercontent.com/669018/188333805-21da423e-6bc7-49c5-a51b-e6214dcbd4ec.png)

Lunchroom
![image](https://user-images.githubusercontent.com/669018/188333821-27a45a0a-a8bf-46a3-b7e5-bff6fb4674fe.png)

**Comment by AESeryth** [comment]
This portal got fixed by Zarq the other day.
