### ISSUE TITLE
Mining 0 Thrallenite

### ISSUE THREAD

**Issue by nevermd** [IronWillGames/Dransik#811]
If you successfully dig in an area that gives Tundrite or Brim then you can get either 1-iron, 2-iron plus thrall, or 3-iron/thrall plus tundrite/brim.  In the scenario 3 it is possible to get 0 Thrall. The text output says you have mined x iron, x tundrite, and 0 Thrall.  The 0 Thrall message does not show up unless you get iron plus a second type of ore.

**Comment by davidjreese** [comment]
this bug is evasive, thanks!

**Comment by davidjreese** [comment]
Fixed this - @hgesler and @Dev-Tyrant - just remember, Random can return 0 (see diff below)

https://github.com/IronWillGames/DransikData/commit/5ad0d484784ceb2c794f03a16e524e7fee3c72e5
