### ISSUE TITLE
Encumbered limit

### ISSUE THREAD

**Issue by nevermd** [IronWillGames/Dransik#812]
If you are encumbered and begin dropping items (like ore) on the ground then it is possible to get the encumbered message to go away but still have your movement slowed.  It seems like ores weigh 0.5 units.  If your weight limit is 711 and you are at 713, then you will start to see the Encumbered flashing message at the top of your backpack.  If you drop 3 ore then you essentially fall to 711.5 in weight and the Encumbered message goes away, but your movement is still restricted.  You have to drop the additional 0.5 units of weight in order to get your movement back to normal.  The movement and Encumbered message should follow the same logic.

**Comment by davidjreese** [comment]
I think I fixed this now. The client / server were out of sync on weight due to some hacks. i remove the hack and everything is data driven off the items weight now. i think this will solve this problem. please let me know if it keeps happening

**Comment by davidjreese** [comment]
Fix is in test now
