### ISSUE TITLE
Alignment not updating properly on client when player teleports while criminal

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#817]
1. Kill a static NPC (Lord Kargoth for example)
2. Teleport using a ladder/cave or use the teleport command in test env
3. The client shows player they are Demonic alignment with a solid dark red name, and no longer criminal with a flashing wanted name
4. Guards still treat player as wanted

Something similar happens in AE when player goes from criminal as a boat to criminal player on land. the player object on client is not updated properly if I remember correctly. It's just a visual issue on client.

**Comment by hgesler** [comment]
https://discord.com/channels/695812967463256084/706609766222528602/858926204807544872

**Comment by davidjreese** [comment]
fixed
