### ISSUE TITLE
Forging with a full backpack

### ISSUE THREAD

**Issue by nevermd** [IronWillGames/Dransik#818]
Forging does not recognize that all item slots in my backpack are filled.  The forging task uses the ingots and I receive the skill exp as normal.  The extra item does not show up in the backpack since all slots are filled but it does show up for me to sell.  

I tested this with iron battle helms.  4 slots in my backpack were taken up by gold, blacksmiths hammers, and ingots.  I crafted up to 65 helms (should have only had slots for 60), then crafted 3 more one at a time. Each time I noticed that I still received exp and when I went to the vendor all 67 helms showed up for me to sell.

**Comment by davidjreese** [comment]
@nevermd - did you check to see if the scrollbar appeared in your backpack?

When your backpack gets overstuffed it should show a scroll bar.

**Comment by nevermd** [comment]
Nope, I didn't even see the scroll bar!  Oops.

**Comment by davidjreese** [comment]
this is fixed now. scrolls to show the overflow
