### ISSUE TITLE
Demon Spire Change Request

### ISSUE THREAD

**Issue by GMRuizerion** [IronWillGames/Dransik#822]
Proposing the following changes to Demon Spires. To remove unwanted items from loot pool, increase spire difficulty while being rewarding. Two tiers of Demon Spires, level 1-80, and levels 80+. Players will be able to choose which spire via Demon Spire Statue. New choice could be labeled Elder Demon Spire or similar. Changes will need to be tested extensively. 

Spire A – levels 1-80
Keep current spire loot pool, while adding in loot and quantities from proposed excel sheet. These treasure rewards should be set at an extremely low % to drop. Cost remains at 1.5m gold. Retain spawned monster list but remove Balrons. Increase item drop from 1 on kill to 2.

Spire B – levels 80+
Increase cost to 3m gold to spawn. Increase spire health from 280k to 400k. Increase Spire attack speed from 6 seconds to 3 seconds. Increase spire to hit and damage to a range of 450-650 per hit. Randomize monster spawning instead of after 3-6 hits from player on spire. Use Elder version of spawned monsters, with new levels and Health. Increase spawned monster damage versus player (possibly increase mitigation from player attacks). Remove old spawn able monster list. Increase item drop upon kill from 1 to 3. Best items should naturally be lower % to drop, but considerably higher % than Spire A - due to increased difficulty and risk.

Would like to use random rolls loot distribution. As used in AE. Each monster treasure list has “pools” of loot. Around 6 items in a pool. Upon death random roll 1 selects the loot pool. Then random roll 2 selects the drop in that pool. The more rarer, desired items will be set to a lower chance. 

For Spire B - Keep current treasures while adding additional ones from excel spreadsheet. 

Implement both Spire A & B as selectable spawn able option through GM Demon Spire Attack Tool

**Comment by GMRuizerion** [comment]
[Revised Spire Loot Pool.xlsx](https://github.com/IronWillGames/Dransik/files/12602434/Revised.Spire.Loot.Pool.xlsx)

**Comment by GMRuizerion** [comment]
Proposed monster changes to "Elder" variation for level 80+ Demon Spire. 
Demon
Current Lvl 90
Current HP 2700
New Lvl 125
New HP 4000

HS
Current Lvl 90
Current HP 2700
New Lvl 130
New HP 4000

Balron 
Current Lvl 95
Current HP 2800
Current New Lvl 135
New HP 5500

Abishai
Current Lvl 37
Current HP 818
New Lvl 80
New HP 2500

Flaming Death
Current Lvl 17
Current HP 467
New Lvl 80
New HP 1500

Fire Fiend
Current Lvl 30
Current HP 798
New Lvl 80
New HP 2000

Hell Hound
Current Lvl 25
Current HP 706
New Lvl 80
New HP 2000

Horned Devil
Current Lvl 72
Current HP 1650
New Lvl 110
New HP 3500

Imp
Current lvl 7
Current HP 123
New Lvl 80
New HP 2000

Minion
Current Lvl 40
Current HP 908
New Lvl 80
New HP 2000

Nightmare
Current Lvl 24
Current HP 560
New Lvl 85
New HP 2000

Dretch
Current Lvl 34
Current HP 760
New Lvl 80
New HP 2000

**Comment by davidjreese** [comment]
v1 done here. i will continue to polish
