### ISSUE TITLE
Intro text says you can only hold 10 items

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#83]
From Steam 
![image](https://user-images.githubusercontent.com/112813257/192193742-f3b18a61-3dc8-43b2-8b25-731bed4f01f1.png)

This window pops up when you log in on a new char.

**Comment by davidjreese** [comment]
@hgesler - I think you fixed this. I remember seeing 100 somewhere. Is that right?

**Comment by hgesler** [comment]
Yes if I remember correctly I updated that information given to players. It’s still confusing though and could use some UI/visual support in the backpack itself.Sent from my iPhoneOn Dec 3, 2022, at 2:04 PM, David Reese ***@***.***> wrote:﻿
@hgesler - I think you fixed this. I remember seeing 100 somewhere. Is that right?

**Comment by davidjreese** [comment]
Closing this, can always make things better and another ticket
