### ISSUE TITLE
using a race change while having an avatar equiped removes it

### ISSUE THREAD

**Issue by ItzDeadBeast** [IronWillGames/Dransik#838]

**Comment by davidjreese** [comment]
@ItzDeadBeast - how long ago did you chant to that avatar (with the following details)
- which one
- how did you get it
- when did you get it and apply it

**Comment by davidjreese** [comment]
Think this is fixed
1. Race change wont wipe out current avatar if its different than your default for race
2. Avatar change allows you to change back to your original race type now too
