### ISSUE TITLE
Players can get trapped between guards and signs in Hothbra

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#84]
Had two separate pages so far from this same area, 510,1085:
![Dransik009](https://user-images.githubusercontent.com/112813257/192643627-720c3b19-3274-4587-acf8-39b8237f15ba.png)

**Comment by hgesler** [comment]
I'm confused about what's happening here. In the editor I don't see those grey blocks on the far left and right circles you drew, for one thing. Also I'm not sure how they're getting themselves into these spots, typically if you can get in you can path find out.

Is the same thing possible at other places where the signs are placed above a North entrance building?
I see Vrethpool has similar configuration of signs by guards there.
![image](https://user-images.githubusercontent.com/74884462/198304387-0dded714-df2b-4e9a-b7bc-b8953b3a472c.png)

**Comment by hgesler** [comment]
I reviewed a lot of towns and most that have this particular type of signpost design with the overhanging sign do not have these north entrance buildings, most likely because of this issue. Fixed the 3 in Hoth and 2 in Vrethpool.

**Comment by AESeryth** [comment]
The grey blocks are the GM walls to stop people from getting there. 

The guards are leaving to chase monsters and people are walking into those tiles in that time. Then the guard resets and they can't leave.
