### ISSUE TITLE
Unable to complete "Lost Goat" quest

### ISSUE THREAD

**Issue by PatrickKaHoTang** [IronWillGames/Dransik#851]
"Lost Goat" is missing on Elverum as the quest looks to be bugged. Unsure if it just didn't respawn due to someone turning it in to complete quest initially or someone turning it in by accident without having the quest then flagging it as completed.

**Comment by KaycJonesz** [comment]
Have witnessed the "lost goat" not respawn after someone completed it.
7 days passed and it was still missing.
The "lost goat" returned after a server crash, if the server did not crash it would still be MIA.

**Comment by hgesler** [comment]
I am not sure how it's getting set in this state, will have to rework the goat's invisible setting or let them tame an encounter spawned goat which was my original plan.

**Comment by KaycJonesz** [comment]
I can only assume that its across all Dransik servers not just PVE.
And that once you complete it via telling it to "stay" and talking to the NPC that there is no Hook to respawn it.

**Comment by hgesler** [comment]
There is a script that gets called after a short time after player tames the Lost Goat to make it visible again but it is not getting called, and I'm not sure why. It should be running in its own loop or whatever that is called but it seems to not execute at all.

**Comment by hgesler** [comment]
Changing this to only work one way; put hay on ground, then click on it. This was always an option but don't think anyone did this.
