### ISSUE TITLE
Items useable from bank

### ISSUE THREAD

**Issue by GMRuizerion** [IronWillGames/Dransik#852]
Player Stormwarrior used berserk potion that was in his bank. I thought this was changed to must have in backpack to use? Please confirm

**Comment by GMRuizerion** [comment]
Reproducible on test. Place Berserk potions in a container, place container in bank. Open container click potion - activates. 

If Berserk potions are NOT in a container within bank clicking them moves to inventory.

**Comment by davidjreese** [comment]
think this is fixed as well as bodies. lets test in test server Zerks, Stuff from bank/container and stuff from a body
