### ISSUE TITLE
Hovering over sign objects shows only part of the tooltip text

### ISSUE THREAD

**Issue by PatrickKaHoTang** [IronWillGames/Dransik#856]
Some screenshots from Kayc in Discord for reference:
![Dransik_ySKkM75h7O](https://github.com/IronWillGames/Dransik/assets/30209039/726058dd-c84d-40d4-856e-eea44c83030c)
![Dransik_NvyhHfeAQ0](https://github.com/IronWillGames/Dransik/assets/30209039/d953083d-3fd0-4cb7-a7bc-88418f74dca8)
![Dransik_174fAimTCh](https://github.com/IronWillGames/Dransik/assets/30209039/3e763231-7472-4d2d-bd7c-5cf81449b5e0)
![Dransik_Iowc4j04Mp](https://github.com/IronWillGames/Dransik/assets/30209039/d71d16ba-4962-46d6-8eb7-a6f3ab470e7e)

**Comment by davidjreese** [comment]
This has been fixed too I think @PatrickKaHoTang
