### ISSUE TITLE
Thanksgiving Event

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#859]
###  Have feast with indigenous people

Scenario, small farmhouse with a kitchen. The head of the house has fallen ill and needs help to make the Thanksgiving meal.
- secretly they are members of the Cult of Turducken, a branch of Necromancers and this ends in violence

Several subquests possibly
- the critters need to be back in the barn (taming/leadership skill?). farm animals are dispersed in the field. don't kill any!
   - **** TABLE SPAWNS
- the invitations need to get out to the guests (time limit to do this and get back? or require a 2nd person). 
   - The guests are maybe 1 of each of the starting races (the NPCs are dignitaries from each homeland?)
   - at this stage, make the table and chairs invisible (clearing is cleared from critters and guests are invited)
   - run and defeat the **Post Master General** so you can mail the invitations (and his watch out for mail bombs?)
   - **** CHAIRS SPAWN
- we don't have the key ingredients -> a turkey (kill it), cranberries (or some other stuff that needs to be harvested/foraging)
   - have the Meal Sized Turkey  be killed by Hand to Hand combat (otherwise its too damaged)
   - maybe a spawn mechanic (or you have to defend the turkey from ravenous creatures is another way to go)?\
   - **** PLACE SETTINGS, DECOR SPAWN
 - cook the meal
   - perhaps cooking skills required here for not overcooking the bird?
  - maybe have to make eggnog too???
  - ***** GUESTS ARRIVE
- Enjoy the meal
  - it smells so good, pilgrims start showing up 1,2 then 3,5 at a time
  - they get angry that there isn't enough food for them
  - then they start chanting and summon their god the Turducken?
  - Maybe if you remember to make stuffing you get a bonus spawn during battle? requires level 90+?
- At this point the guests turn into lich kings and its a brawl
- Turducken could spawn pilgrims or other fun things (turkeys, chickens and ducks that are mean)?

* have some violence around the farm perhaps? that respawn and drop some turkey event trinkets for turn in?

Possible spots for the feast
- 3373, 1379. 0

**Comment by hgesler** [comment]
Here's the inspiration for the boss: 
![image](https://github.com/IronWillGames/Dransik/assets/74884462/3d2c07d2-0682-4598-b0ce-d410cbaf18f4)

**Comment by davidjreese** [comment]
Nothing final, feel free to add/change the script. I am thinking it through a bit trying to keep it punch and action oriented so people arent just in dialogs

**Comment by davidjreese** [comment]
did a variation of this idea
