### ISSUE TITLE
Weapons unequip when leveling up

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#86]
If you're wearing a weapon that you only meet the skill requirement of after a racial passive (like a high level blunt weapon on a low blunt skill Brimlock), the weapon will be unequipped when you gain a level.  Not sure if this applies to stat bonuses and requirements also.

They also get unequipped when you first log in.

**Comment by hgesler** [comment]
Possibly related page:

_"bol is unequipped every time I log in"_

**Comment by davidjreese** [comment]
Fixed in new build !
