### ISSUE TITLE
Target protection let’s you still target people.

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#863]
Target protection let’s you still target people.

I think the target protection didn't work because the guy was a werewolf (animal).
Same thing happened to many of us yesterday. 

NOTE:  Was working fine before the update?

A player said TP shouldn't look at Player Alignment - just never allow target a player when enabled.

**Comment by KaycJonesz** [comment]
On the PVE server you can target players with TAB, and it will spam you with player protection is on message if you turn it on.
You can't hit them, but it still lets you target them with TAB.

**Comment by davidjreese** [comment]
- Tab doesn't allow any players to be selected on client. (confirmed)
- Fixed client case where clicking a player was looking at alignment (server would override it if it was non pvp server)
- Added knowledge of if PvP to client so it wont even allow targeting a player if its not a PvP server

Don't see anything else here that can cause issues.
