### ISSUE TITLE
Login message for players entering a past season (champion's realm)

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#868]
Add an onlogin message/print to players explaining the characters location and hint at future work for this map layer/past season chars.

**Comment by davidjreese** [comment]
@hgesler - didn't you do this already?

**Comment by hgesler** [comment]
I attempted but have not gotten it to work yet.Heidi Sent from my iPhoneOn Feb 23, 2024, at 9:29 AM, David Reese ***@***.***> wrote:﻿
@hgesler - didn't you do this already?

**Comment by davidjreese** [comment]
i fixed this a while back
