### ISSUE TITLE
"Channel" chat improvements/fixes

### ISSUE THREAD

**Issue by PatrickKaHoTang** [IronWillGames/Dransik#869]
Improvements:
- Create a prompt window to join channels instead of a new chat window
- When you're typing in a chat channel, display which channel you're typing before your name to avoid confusion

Fixes:
- When joining a channel and you want to view that channel in a non-Chat Console window, it doesn't show that you can stop listening to that channel in that window after a full relog. To find it, it's under "Chat Console"
ie. I have "Chats" and "Chat Console" as my chat windows. I want "global" under "Chats". After full relog, I can't turn off "Global" under "Chats", I can only perform that action under "Chat Console"

**Comment by davidjreese** [comment]
@PatrickKaHoTang - i think i dealt with these already, old ticket
