### ISSUE TITLE
Implement: Mesmer Set & Tra'vaals Monsters/Encounter Area

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#876]
### From Discord User
-  Enbar
### Weapons & Armor Needing Settings
These need to be setup (attributes) and added to NPCs for dropping
- [x] Mesmer Crown
- [x] Mesmer Gauntlets
- [x] Mesmer Chestpiece
- [x] Mesmer Shield
- [x] Mesmer Pants
- [x] Mesmer Sword
- [ ] Purple Hood (was Mesmer but now just extra item)

### Checklist of Tasks
- [x] All wands added to weapon/armor shopkeeper
- [ ] All stats set
- [x] Added to Generic Treasure Table
- [x] Added to Specific NPC types

### NPCs
These need to be setup (levels/dmg) and placed in the world, with lore/quests and drop new items. NOTE: Lore may need to be tweaked, I can't scale this art down without making it look like crap. So maybe we have 4 bosses to use vs having some of these be mundane creatures
- [x] Jailer (32x32 monster) - BOSS
- [x] Headhunter (32x32 monster) - BOSS
- [x] BloodSummoner (32x32 monster) - BOSS
- [x] Avatar of Tra'vaal (32x32 monster) - BOSS

### Summary
Tra'vaals Domain" the skull is sort of an old god being summoned by the red guys (Blood Summoners), and is called Avatar of Tra'vaal, since he's not fully manifested yet. The gray ones are called Headhunters. I got it all written down somewhere but that's a quick summary

### LORE/QUEST/TALKING TO NPC DIALOGUE:

The Headhunters attack our town at nightfall, their attacks have been getting more frequent as of late.
For almost a year we've suffered their unrelenting killings, slicing our townsfolk to pieces. 
Always accompanied by Tra'vaals Blood Summoners, siphoning the blood of our people with their blood magic. 
A worse faith still has been bestowed upon those captured alive by the Jailers. For what reason, I endure not speculate...

Not much knowledge of Tra'vaal remain in the realm, any recorded history regarding the Ancient Shapers is forbidden and most of it's been destroyed.
Tra'vaals name, ironically enough is only remembered because it was the one name that actually needed to be forgotten.

The Legends tell that Tra'vaals vision for the realm in it's creation became twisted and evil.
Too powerful to be imprisoned in his physical form,
the other Shapers banished Tra'vaals immortal soul between the two worlds, our own and his twisted creation, his domain.

The portal just appeared one day, the attacks started without warning and they were merciless. 
There are rumors among the townsfolk, the Blood Summoners are attempting to manifest the spirit of Tra'vaal. 
Where these rumors come from I do not know, I cannot imagine any adventurer brave or foolish enough to venture through that portal, 

or skilled enough to make it back out to tell their tale for that matter. 
All that is known for sure is, if Tra'vaal would to be returned to his domain it would not be long until he gathers enough strength to cross into 
our world to remake it, in death.

### VOICE(TEXT)LINE DURING BOSS FIGHT:

Jailer: There is no Escape, your soul will rot in this place.

Blood Summoner: Tra'vaal will feast on the remains of your world!

Avatar of Tra'vaal: Pathetic... 
Avatar of Tra'vaal: Insignificant.. 
Avatar of Tra'vaal: ALL OF YOU!!! (Last line triggers an AOE attack that kills all mobs on screen and does a very large %amount of damage to players. Mobs killed by this award no loot)

**Comment by davidjreese** [comment]
I pulled all the art in and created types for them, just need to be placed in world and finish setting up attributes.

NPCS are all setup as BOSSES with some very generic values. They will need tuning
EQUIPMENT is just setup as right type/slot but not with proper ac or other values

**Comment by PatrickKaHoTang** [comment]
Added requirements (temporary until dungeon comes out), attributes and armour count. Resistance after the plan for the dungeon direction

**Comment by davidjreese** [comment]
@PatrickKaHoTang - The different bosses drop the Mesmer set pieces. I am going to close this ticket. You may want to adjust stats still though, so this is just an FYI. Same goes for the various bosses and encounters related to this
