### ISSUE TITLE
Some gauntlet items are misspelled or abbreviated 

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#88]
Tundrite Chain Guants
Bronze Plate Guants
Brimidian Chain Guants

Brimidian Plate Gaunts
Bronze Chain Gaunts
Banished Knight Gaunts
Tundrite Plate Gaunts

All should be changed to Gauntlets.

**Comment by Dev-Tyrant** [comment]
If we change the name of the item, it will delete it from the players

**Comment by davidjreese** [comment]
Seriously? Can we verify this somewhere?

**Comment by Dev-Tyrant** [comment]
If I change the item's name in the editor, it will delete it from the player's inventory. 
We would need to do something server-side to ensure it doesn't do that.
