### ISSUE TITLE
Implement: Javalin and Taming Whips

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#887]
Types are made and all are setup as Thrown Weapons now

### Thrown Weapon Setup
- [x] Javalins

### Checklist For Thrown Weapons
- [x] Setup as Thrown Weapon
- [x] Added to Weapons and Weapon/Armor vendor (not on silvest)
- [x] Added to TC4 (quantity:3-5), TC5 (quantity:5-10) Treasure Tables 

### Training Whips Setup
- [x] Taming Whip
- [x] Sturdy Whip
- [x] Circus Whip
- [x] Ring Master Whip
- [x] Druid Master Whip

### Checklist For Whips
- [x] Setup as Default, with Health 100 and Resuse Delay 2 (like foraging stick)
- [x] Added to Provisioner and Silvest Provisioner
- [x] Added to T2 - T6 Treasure Tables 
- [x] Usecode added (just sketched out to select valid objects) -> FINISH LOGIC HERE

**Comment by KaycJonesz** [comment]
Am happy to see all the pixel art i offered is being added.
Originally designed the whips for a unique weapon for Throwing.

- Just wanted to go on record that I'm not sure how i feel about Whips being used for Taming.
- I dont know what to expect from the taming updates so i dont know if there are different types of taming.
- I applied on the website with a ticket to get invited to the test server, iv not heard back.

**Comment by davidjreese** [comment]
All this is in. @hgesler will be back from holiday next week and get you setup on test @KaycJonesz
