### ISSUE TITLE
Implement: Common Wands

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#889]
- Min/Max damage (Normal) is added added to base damage (pre calculation)
- Min/Max damage (Arcana type) is added for spell that is of that arcana type
- Speed is added to attack speed (lower is faster)
- HItModifier is added to fizzle change (higher is less chance to fizzle)

Note, can use a simple fuzz animation (for a gem slot or length of the staff/wand) to great a magic clow effect of different colors. When building these out, the tile can be converted to an anime and use that newly created fuzz frame to animate them

Set these up so mages can be properly balanced and spread out over all the various arcana

I Created wand types for all of these with the naming pattern below

- [x] name all the generic 1-7 wands
- [x] name all the damage type wands 1-7

### Checklist of Tasks
- [x] All wands added to Mage shopkeeper
- [x] Wands of Casting, Wand of Winds, Wand of FIre moved to Mage shopkeeper
- [x] All stats set
- [x] Added to Generic Treasure Table
- [x] Added to Specific NPC types

**Comment by davidjreese** [comment]
Pat is going to finish the Wnat of casting, wand of window etc.. and the generic wands

**Comment by PatrickKaHoTang** [comment]
Sent updated stats and renamed Wands

Head hurts from all of that...

**Comment by davidjreese** [comment]
looks great, thanks and thank your GF - love the stats
