### ISSUE TITLE
Suggestion to make potion and scroll of healing have same cooldown timers

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#89]
Suggestion from player in tickets - to make potion and scroll of healing have same cooldown timers. Currently potion of healing has shorter cooldown than scrolls. Not sure of the validity of this suggestion.

**Comment by Dev-Tyrant** [comment]
// Healing Potion
// val = 50 + Random(ConBonus)

// Greater Healing Potion
// val = 125 + Random(ConCheck)

POTIONTIMER = 2
===============================
//	Minor Scroll of Healing
//	Heals up to 250

//	Scroll of Healing
//	Heals up to 450

MAGECASTTIMER = 4 

=======================
=======================

Not adjusting MagecastTimer to match potiontimer, there is a payoff for using pots over scrolls for less stutter
