### ISSUE TITLE
Specific items unable to be traded

### ISSUE THREAD

**Issue by GMRuizerion** [IronWillGames/Dransik#894]
Player Williams Wallace conqueror's plate he is unable to trade it.  Item does not display as available item for trade, William does have a conqueror's plate equipped. Others have mentioned items exhibiting same behavior. I have noticed it with conqueror's plate on non gm account also.

**Comment by PatrickKaHoTang** [comment]
Most likely the same situation as https://github.com/IronWillGames/Dransik/issues/874

**Comment by davidjreese** [comment]
i think all this has been fixed. let me know if yu disagree @PatrickKaHoTang
