### ISSUE TITLE
Condense Titan Army spell print out text

### ISSUE THREAD

**Issue by GMRuizerion** [IronWillGames/Dransik#902]
Upon casting Titan Army spell it display 4 seperate messages in chat console. One for + defense, another + Attack. Both of these print twice (See screen grab). Suggest condensing to something like this.....
"Ruizerion's Titan Army boosts your attack and defenses by +10 for 60 seconds". 

***Also typo within spell print out (protectes) should be protects.***
![Capture](https://github.com/IronWillGames/Dransik/assets/130917491/6bdee23d-a942-4166-a49d-edd411372b43)

**Comment by davidjreese** [comment]
this is done
