### ISSUE TITLE
Roasting Skill has OP Exp Gain

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#908]
Maybe do this part of the overall crafting revamp but this at least tracks it

**Comment by davidjreese** [comment]
@hgesler - thought you may have already dealt with this?

**Comment by hgesler** [comment]
Do not recall, will have to review. But we also need a single call into player generic that streamlines and makes xp gain more consistent so it will likely get fixed or changed at that point anyways.Sent from my iPhoneOn Feb 23, 2024, at 9:30 AM, David Reese ***@***.***> wrote:﻿
@hgesler - thought you may have already dealt with this?

**Comment by davidjreese** [comment]
i refactored all of them
