### ISSUE TITLE
Farmer GIles Quest  & Librarin / Silvest Quests Issues

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#910]
- [x] Issue where Silvest Librarian gives quest before you agree
- [x] Issue with Farmer Giles (Screenshot below with player issue)

<img width="554" alt="Screenshot 2023-11-24 at 8 22 23 AM" src="https://github.com/IronWillGames/Dransik/assets/669018/2f9cc62d-a5f0-4309-ab4c-8766a8460743">

**Comment by hgesler** [comment]
Farmer Giles quest count for the seeds only resets when you relog it seems, but its just a visual reset, and the data is stored correctly/represented properly when they resume the quest. This issue only happens with repeat quests like Chaos Knights in AE - I have not had this issue with static stage quests in AE so I'm assuming the DC client is not behavior properly? Not sure. @davidjreese might want to see what client is doing with this queststagedata call when it loads?? maybe I'm saying that right? lol

Session 1: Player gathered 12 seeds.
Player Logs out
Session 2: Player logs in; sees he has collected 0/25 seeds. Player collects 1 seed, bringing him to 13 total seeds.

**Comment by davidjreese** [comment]
it sounds like its not sending (or using the proper count on login). k, ill debug that

**Comment by davidjreese** [comment]
this was fixed a while back
