### ISSUE TITLE
Crafted Dark Sword Bug

### ISSUE THREAD

**Issue by Galdelonian** [IronWillGames/Dransik#912]
The Dark Sword is bugged when crafted.
After crafting Hilt with the Blade the Dark Sword can be dragged to the weapon slot and equipped however it deals 3 damage statically at speed 1. (Same as the hilt) If you unequip it and try to equip it by clicking on it in the backpack instead of dragging it to the weapon slot it will give a timer saying "You cannot use that item for 1996.21 seconds" (the timer does start counting down.)

Troubleshooting:
Soft Relog (While client is still open) does not work.
Unequipping and re-equipping does not work.
Trading to someone else does not change whether they can or you can use it.
Dropping on the ground and picking it back up does not work.

Work around:
Full Relog works.

**Comment by PatrickKaHoTang** [comment]
Consolidating information,

Duplicate ticket created at https://github.com/IronWillGames/Dransik/issues/911. More information also found on https://github.com/IronWillGames/Dransik/issues/739 as it's possibly the same issue.

**Comment by hgesler** [comment]
Fixed by destroyed and recreating (similar to fix for the elemental stones)

**Comment by hgesler** [comment]
Confirmed fixed
