### ISSUE TITLE
Dark Ore drops from Serpent Men on Dragon Island (remove them?)

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#914]
With Serpent Men on Dragon Island with the Red Dragons you have introduced Dark Ore to the overworld when it was only available in the Tower. I suggest, if possible, removing it from the Serpent Men drop tables when they're outside the Tower. (I believe one way to do this would be to add another mob in who is an exact duplicate as "Serpent Man" and just remove the ore from his drop rate. I'm sure it's likely not the most efficient way but just an idea.)

**Comment by hgesler** [comment]
May not be ideal to add an identical type; will be confusing for kill counts/id skill etc. I'd suggest doing it in either player generic (not really ideal) or making a new type of serpent man (either lesser or greater) to be inside or outside the tower. Or just remove them from outside the tower.

**Comment by davidjreese** [comment]
I fixed this and its live already
