### ISSUE TITLE
Move Sand Cloth gear back to Gluttons and Spiker Silk to Anarius spider area

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#916]
Move Sand Cloth gear back to Gluttons. Move spidersilk gear to Spiders with the Spider Anarius or w/e

**Comment by hgesler** [comment]
Added Sand Cloth to regular gluttons

Added all spider silk items (hood/robe/boots/gloves/orb) to Venom Spiders & Anarius

**Comment by hgesler** [comment]
Added some of the spider silk to fungi lurkers

**Comment by hgesler** [comment]
Verified the drops are in (checked w gluttons)
