### ISSUE TITLE
Ranger Armor Setup In Game

### ISSUE THREAD

**Issue by davidjreese** [IronWillGames/Dransik#922]
Created type based on BK set, needs to be changed to be for ranger, added to drops, and shops to buy

- [ ] Ranger Chestpiece (added to shop)
- [ ] Ranger Hood (added to shop)
- [x] Ranger Pants (added to shop)
- [ ] Ranger Quiver (added to shop)

Following is just an anime for now (need to create types and then use, but first need to figure out what for)

- [x] Blood Orb
- [ ] Maw

**Comment by davidjreese** [comment]
@hgesler a few more things in editor now

**Comment by PatrickKaHoTang** [comment]
Updated Ranger items to be for the Nimble set

**Comment by davidjreese** [comment]
this was done a while back.
