### ISSUE TITLE
[Dransik 2.0] Map progression not persisted after logging in

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#93]
### Map progression not persisted after logging in

1. Log into a character
2. Walk around and reveal some of the map
3. Log off
4. Log back into the same character
5. Notice that your map progression did not save

#### Expected:
The map progression will be saved and loaded when logging in.

#### Actual:
The map progression is not saved after logging out and logging in.

**Comment by davidjreese** [comment]
Fixed - core issue was no local client configuration was being saved.
