### ISSUE TITLE
Wand - New Player

### ISSUE THREAD

**Issue by KaycJonesz** [IronWillGames/Dransik#933]
Was not able to get the new player Wand working from the ball the Kritsanna gives, i chose magic and received a wand that didnt work.

![1q3z4RaQfB](https://github.com/IronWillGames/Dransik/assets/147594953/ce9db350-0b53-4e99-8624-8c3af01d1981)

**Comment by hgesler** [comment]
I think you needed to know how to cast the spells. They work afaik. You have to open the spell book and train then click on the spell icon to cast while targeting a creature.
