### ISSUE TITLE
Book

### ISSUE THREAD

**Issue by genkelvor** [IronWillGames/Dransik#934]
Opening and closing books gives 1 exp each time, this can be abused for a slowly level up just leaving a marco running opening and closing it.

**Comment by davidjreese** [comment]
Note, this is a special level 1 thing for the Kristanna books area. it shouldn't be too abusable past that but will fix it for sure.

**Comment by davidjreese** [comment]
fixed, it would stop working if you got to level 1 of skill (25 points I think) but better now
