### ISSUE TITLE
Silvest Librarian

### ISSUE THREAD

**Issue by genkelvor** [IronWillGames/Dransik#935]
Quest in Silvest, from Silvest Librarian in the potion shop he will ask you to collect 5 bat carcasses but the quest text will only count up to 4/5 
Edit: Same is for the next part for bug swarms and the Large Slimes
![image](https://github.com/IronWillGames/Dransik/assets/49921293/58cd7519-d52d-4940-b023-a4d4d40b5b4c)

**Comment by davidjreese** [comment]
fixed now
