### ISSUE TITLE
[Dransik 2.0] After selecting server and clicking play, takes a while before characters shown

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#94]
### After selecting server and clicking play, takes a while before characters shown

1. Launch the client
2. Wait a couple minutes until the Server List shows up
3. Click on the server to join
4. Click Play
5. At this point, connecting to server dialog is shown for about 1min+.

#### Expected:
The connecting to server dialog would perform the action in a reasonable amount of time, or display some sort of indicator that it is actively working. Currently only showing stars, then freezes and waits until the character list loads.

#### Actual:
The connecting to server dialog shows Connecting Pantheon ***********, but then just hangs there until it's done connecting.

**Comment by davidjreese** [comment]
Issue is Windows only - for some reason IPv6 resolution on windows is really freaking weird... takes forever for the HTTPRequests to resolve. Disabling IPv6 on Windows Network Adapter is a work around for now.

**Comment by davidjreese** [comment]
Fixed - disabled IPv6 on server end until this isn't a problem.
