### ISSUE TITLE
Silvest Mugrawrw doesn't give saw for 2nd part of quest

### ISSUE THREAD

**Issue by GMRuizerion** [IronWillGames/Dransik#946]
NPC should give players saw

**Comment by hgesler** [comment]
Doesn't he do this on a later stage?

**Comment by GMRuizerion** [comment]
> Doesn't he do this on a later stage?

He's supposed to on 2nd stage. Players get print message about him handing you a saw to cut a plank. But you're actually not given a saw.

**Comment by davidjreese** [comment]
This is fixed right @GMRuizerion ?
