### ISSUE TITLE
[Dransik 2.0] Can't X out of Merchant window while scrolled down 

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#95]
After scrolling about halfway down the list, the X to close stops working. Need to scroll back to the top to leave the shop without buying.

https://user-images.githubusercontent.com/112813257/194646700-2cb65a76-c8e9-4c83-adeb-be6105c9557b.mp4

**Comment by davidjreese** [comment]
fixed this and other layering window click issues
