### ISSUE TITLE
Criminal Name Flashing Bug

### ISSUE THREAD

**Issue by Galdelonian** [IronWillGames/Dransik#953]
Whenever a character becomes a criminal by attacking an NPC, another player, or looting someone their name begins flashing. This flashing effect is confusing and messes with PVP.

Another issue with this is a true bug where the name will go from flashing to a flat non-flashing demonic color leading the criminal to believe they are no longer a criminal. Others still see the name as flashing.

This is especially important because the names can be difficult to read.

Please add a black outline to make it easier to see. The outline blends with the inside. Can it please have a solid black outline? Even if this was an optional that would be great.

**Comment by davidjreese** [comment]
i fixed this
