### ISSUE TITLE
Guild Quest Bugged

### ISSUE THREAD

**Issue by GMRuizerion** [IronWillGames/Dransik#956]
After completing the last book you're told to speak with Father Gweedo at the Abbey. Gweedo refuses to speak with you, therefore unable to click blood fountain to be ported to Holendar to finish guild quest or create a guild. Also had some reports of this step not awarding exp - may want to check this also.

**Comment by GusToughSon** [comment]
cause your supposed to do the part of the quest in the bottom right corner of the abby to activate that part, damn your a neb

**Comment by hgesler** [comment]
Not able to start. Player given following choices and none advance him.
![image](https://github.com/IronWillGames/Dransik/assets/74884462/00dbbf37-1228-4415-b496-767e1226a51a)

**Comment by davidjreese** [comment]
Fixed... the Object "Blood Fountain" conflicted with the Type "Blood Fountain" since they have the same name and so the usecode on the object was never getting called...
