### ISSUE TITLE
[Dransik 2.0] Window sizes and positioning not persisted after logging in

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#96]
### Window sizes and positioning not persisted after logging in

1. Log into a character
2. Move around some in game windows and change window sizes
3. Log off
4. Log back into the same character
5. Notice that your in game windows position and sizes are not persisted

#### Expected:
The positions and sizes of the in game windows will be saved and loaded when logging in. May also require saving the size of the client window to ensure positioning works.

#### Actual:
The positions and sizes of the in game windows are not saved and reset every time you log in.

**Comment by davidjreese** [comment]
Fixed - this was solved when I fixed local client config files not saving.
