### ISSUE TITLE
Alignment boost seems to not be working atm

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#968]
Alignment boost token shop item does not seem to be working; from tickets. Player Annihilator. Probably need a bit more info on alignment he had and avatar/race.

_I bought 4 (80 tokens) of them and my alignment never changed (No, I didn't have the lock on)._

**Comment by Galdelonian** [comment]
It did work when I used it recently but it didn't work well. If you keep using them it'll start changing them. I feel like it just doesn't move it enough.

**Comment by davidjreese** [comment]
fixed
