### ISSUE TITLE
[Dransik 2.0] When moving in game windows around, right and bottom edges of screen not stopping from going outside viewport

### ISSUE THREAD

**Issue by athacus** [IronWillGames/Dransik#97]
### When moving in game windows around, right and bottom edges of screen not stopping from going outside viewport

1. Log into a character
2. Grab the mini map in game window and move it to the top or left of the screen
3. Notice that it can't move outside of the viewport of the client window
4. Grab the mini map in game window and move it to the right or bottom of the screen
5. Notice that it can move outside of the viewport of the client window

#### Expected:
When moving in game windows around, all 4 sides of the client window should anchor the window inside of the viewport.

#### Actual:
When moving in game windows around, you can move windows outside of the right and bottom edges.

**Comment by davidjreese** [comment]
fixed
