### ISSUE TITLE
GUI elements cannot be clicked when drawn over a black/non visible area of game window (underground or in a closed room/home)

### ISSUE THREAD

**Issue by hgesler** [IronWillGames/Dransik#973]
Unable to select inside of Crafting Window (possibly any GUI element) that is drawn over a section of tiles player can't see, such as the black area outside a room/closed area (room with no windows and doors are shut; for ex near the door at 2738,2200,0 in garnea). This happens underground as well.

- Go to location mentioned: 2738,2200,0
- Make sure game window is in top left position of client. 
- Open crafting window (tried with carpenters tools > planks and scissors > cloth). 
- Crafting window will appear drawn over the play area/game window, and should be drawn to cover game area where there is black (no tiles drawing).
- Notice you cannot select anything in that window - not X button, filters etc. You can only select GUI elements that are drawing.
- To craft you have to go outside. In the ss, I cannot select anything above "bandages." I cannot filter, close the window, etc.

![image](https://github.com/IronWillGames/Dransik/assets/74884462/0ebd2848-607a-4587-9092-e2fee9bda46e)

**Comment by davidjreese** [comment]
fixed the initial issue

noticed an issue with the camera alignment of the occluder when zoom > 1 though
