### ISSUE TITLE
[Dransik 2.0] Some windows can be clicked through

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#98]
Some windows can be clicked through, using items, npcs, or UI elements that are not visible.

https://user-images.githubusercontent.com/112813257/194648003-d3a143a2-2ca3-4094-aabf-419ec7683af7.mp4

**Comment by davidjreese** [comment]
Fixed this everywhere i think. Also fixed the bring to top of windows when you click on the empty area.
