### ISSUE TITLE
[Dransik 2.0] The combat mode >> Attack <<  text is too big and can hide monsters, items

### ISSUE THREAD

**Issue by AESeryth** [IronWillGames/Dransik#99]
![20221007163936_1](https://user-images.githubusercontent.com/112813257/194649988-c7e57ca9-0941-4f8b-9a05-ddfe81db8fe6.jpg)

![20221007163940_1](https://user-images.githubusercontent.com/112813257/194650003-b7f883cb-9519-461d-ad7f-af0c19acc7e5.jpg)

**Comment by davidjreese** [comment]
removed this hack and put in real cursors
